// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeAccount is the FHIR resource type name for Account.
const ResourceTypeAccount = "Account"

// AccountCoverage represents a FHIR BackboneElement for Account.coverage.
type AccountCoverage struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The party(s), such as insurances, that may contribute to the payment of this account
	Coverage Reference `json:"coverage" fhir:"cardinality=1..1,required,summary"`
	// The priority of the coverage in the context of this account
	Priority *int `json:"priority,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
}

// AccountGuarantor represents a FHIR BackboneElement for Account.guarantor.
type AccountGuarantor struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Responsible entity
	Party Reference `json:"party" fhir:"cardinality=1..1,required"`
	// Credit or other hold applied
	OnHold *bool `json:"onHold,omitempty" fhir:"cardinality=0..1"`
	// Extension for OnHold
	OnHoldExt *primitives.PrimitiveExtension `json:"_onHold,omitempty" fhir:"cardinality=0..1"`
	// Guarantee account during
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
}

// AccountDiagnosis represents a FHIR BackboneElement for Account.diagnosis.
type AccountDiagnosis struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Ranking of the diagnosis (for each type)
	Sequence *int `json:"sequence,omitempty" fhir:"cardinality=0..1"`
	// Extension for Sequence
	SequenceExt *primitives.PrimitiveExtension `json:"_sequence,omitempty" fhir:"cardinality=0..1"`
	// The diagnosis relevant to the account
	Condition CodeableReference `json:"condition" fhir:"cardinality=1..1,required,summary"`
	// Date of the diagnosis (when coded diagnosis)
	DateOfDiagnosis *primitives.DateTime `json:"dateOfDiagnosis,omitempty" fhir:"cardinality=0..1"`
	// Extension for DateOfDiagnosis
	DateOfDiagnosisExt *primitives.PrimitiveExtension `json:"_dateOfDiagnosis,omitempty" fhir:"cardinality=0..1"`
	// Type that this diagnosis has relevant to the account (e.g. admission, billing, discharge …)
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*"`
	// Diagnosis present on Admission
	OnAdmission *bool `json:"onAdmission,omitempty" fhir:"cardinality=0..1"`
	// Extension for OnAdmission
	OnAdmissionExt *primitives.PrimitiveExtension `json:"_onAdmission,omitempty" fhir:"cardinality=0..1"`
	// Package Code specific for billing
	PackageCode []CodeableConcept `json:"packageCode,omitempty" fhir:"cardinality=0..*"`
}

// AccountProcedure represents a FHIR BackboneElement for Account.procedure.
type AccountProcedure struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Ranking of the procedure (for each type)
	Sequence *int `json:"sequence,omitempty" fhir:"cardinality=0..1"`
	// Extension for Sequence
	SequenceExt *primitives.PrimitiveExtension `json:"_sequence,omitempty" fhir:"cardinality=0..1"`
	// The procedure relevant to the account
	Code CodeableReference `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Date of the procedure (when coded procedure)
	DateOfService *primitives.DateTime `json:"dateOfService,omitempty" fhir:"cardinality=0..1"`
	// Extension for DateOfService
	DateOfServiceExt *primitives.PrimitiveExtension `json:"_dateOfService,omitempty" fhir:"cardinality=0..1"`
	// How this procedure value should be used in charging the account
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*"`
	// Package Code specific for billing
	PackageCode []CodeableConcept `json:"packageCode,omitempty" fhir:"cardinality=0..*"`
	// Any devices that were associated with the procedure
	Device []Reference `json:"device,omitempty" fhir:"cardinality=0..*,summary"`
}

// AccountRelatedAccount represents a FHIR BackboneElement for Account.relatedAccount.
type AccountRelatedAccount struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Relationship of the associated Account
	Relationship *CodeableConcept `json:"relationship,omitempty" fhir:"cardinality=0..1"`
	// Reference to an associated Account
	Account Reference `json:"account" fhir:"cardinality=1..1,required"`
}

// AccountBalance represents a FHIR BackboneElement for Account.balance.
type AccountBalance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Who is expected to pay this part of the balance
	Aggregate *CodeableConcept `json:"aggregate,omitempty" fhir:"cardinality=0..1"`
	// current | 30 | 60 | 90 | 120
	Term *CodeableConcept `json:"term,omitempty" fhir:"cardinality=0..1"`
	// Estimated balance
	Estimate *bool `json:"estimate,omitempty" fhir:"cardinality=0..1"`
	// Extension for Estimate
	EstimateExt *primitives.PrimitiveExtension `json:"_estimate,omitempty" fhir:"cardinality=0..1"`
	// Calculated amount
	Amount Money `json:"amount" fhir:"cardinality=1..1,required"`
}

// Account represents a FHIR Account.
type Account struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Account number
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// active | inactive | entered-in-error | on-hold | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Tracks the lifecycle of the account through the billing process
	BillingStatus *CodeableConcept `json:"billingStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// E.g. patient, expense, depreciation
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Human-readable label
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// The entity that caused the expenses
	Subject []Reference `json:"subject,omitempty" fhir:"cardinality=0..*,summary"`
	// Transaction window
	ServicePeriod *Period `json:"servicePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// The party(s) that are responsible for covering the payment of this account, and what order should they be applied to the account
	Coverage []AccountCoverage `json:"coverage,omitempty" fhir:"cardinality=0..*,summary"`
	// Entity managing the Account
	Owner *Reference `json:"owner,omitempty" fhir:"cardinality=0..1,summary"`
	// Explanation of purpose/use
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The parties ultimately responsible for balancing the Account
	Guarantor []AccountGuarantor `json:"guarantor,omitempty" fhir:"cardinality=0..*"`
	// The list of diagnoses relevant to this account
	Diagnosis []AccountDiagnosis `json:"diagnosis,omitempty" fhir:"cardinality=0..*,summary"`
	// The list of procedures relevant to this account
	Procedure []AccountProcedure `json:"procedure,omitempty" fhir:"cardinality=0..*,summary"`
	// Other associated accounts related to this account
	RelatedAccount []AccountRelatedAccount `json:"relatedAccount,omitempty" fhir:"cardinality=0..*"`
	// The base or default currency
	Currency *CodeableConcept `json:"currency,omitempty" fhir:"cardinality=0..1"`
	// Calculated account balance(s)
	Balance []AccountBalance `json:"balance,omitempty" fhir:"cardinality=0..*"`
	// Time the balance amount was calculated
	CalculatedAt *primitives.Instant `json:"calculatedAt,omitempty" fhir:"cardinality=0..1"`
	// Extension for CalculatedAt
	CalculatedAtExt *primitives.PrimitiveExtension `json:"_calculatedAt,omitempty" fhir:"cardinality=0..1"`
}
