// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// Annotation represents a FHIR Annotation.
type Annotation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Individual responsible for the annotation - Reference option
	AuthorReference *Reference `json:"authorReference,omitempty" fhir:"cardinality=0..1,summary,choice=author"`
	// Individual responsible for the annotation - string option
	AuthorString *string `json:"authorString,omitempty" fhir:"cardinality=0..1,summary,choice=author"`
	// Extension for AuthorString
	AuthorStringExt *primitives.PrimitiveExtension `json:"_authorString,omitempty" fhir:"cardinality=0..1"`
	// When the annotation was made
	Time *primitives.DateTime `json:"time,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Time
	TimeExt *primitives.PrimitiveExtension `json:"_time,omitempty" fhir:"cardinality=0..1"`
	// The annotation  - text content (as markdown)
	Text string `json:"text" fhir:"cardinality=1..1,required,summary"`
	// Extension for Text
	TextExt *primitives.PrimitiveExtension `json:"_text,omitempty" fhir:"cardinality=0..1"`
}
