// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeBasic is the FHIR resource type name for Basic.
const ResourceTypeBasic = "Basic"

// Basic represents a FHIR Basic.
type Basic struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Kind of Resource
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Identifies the focus of this resource
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// When created
	Created *primitives.DateTime `json:"created,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Created
	CreatedExt *primitives.PrimitiveExtension `json:"_created,omitempty" fhir:"cardinality=0..1"`
	// Who created
	Author *Reference `json:"author,omitempty" fhir:"cardinality=0..1,summary"`
}
