// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeBiologicallyDerivedProductDispense is the FHIR resource type name for BiologicallyDerivedProductDispense.
const ResourceTypeBiologicallyDerivedProductDispense = "BiologicallyDerivedProductDispense"

// BiologicallyDerivedProductDispensePerformer represents a FHIR BackboneElement for BiologicallyDerivedProductDispense.performer.
type BiologicallyDerivedProductDispensePerformer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifies the function of the performer during the dispense
	Function *CodeableConcept `json:"function,omitempty" fhir:"cardinality=0..1,summary"`
	// Who performed the action
	Actor Reference `json:"actor" fhir:"cardinality=1..1,required,summary"`
}

// BiologicallyDerivedProductDispense represents a FHIR BiologicallyDerivedProductDispense.
type BiologicallyDerivedProductDispense struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for this dispense
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// The order or request that this dispense is fulfilling
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Short description
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// preparation | in-progress | allocated | issued | unfulfilled | returned | entered-in-error | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Relationship between the donor and intended recipient
	OriginRelationshipType *CodeableConcept `json:"originRelationshipType,omitempty" fhir:"cardinality=0..1,summary"`
	// The BiologicallyDerivedProduct that is dispensed
	Product Reference `json:"product" fhir:"cardinality=1..1,required,summary"`
	// The intended recipient of the dispensed product
	Patient Reference `json:"patient" fhir:"cardinality=1..1,required,summary"`
	// Indicates the type of matching associated with the dispense
	MatchStatus *CodeableConcept `json:"matchStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// Indicates who or what performed an action
	Performer []BiologicallyDerivedProductDispensePerformer `json:"performer,omitempty" fhir:"cardinality=0..*,summary"`
	// Where the dispense occurred
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1,summary"`
	// Amount dispensed
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1,summary"`
	// When product was selected/matched
	PreparedDate *primitives.DateTime `json:"preparedDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for PreparedDate
	PreparedDateExt *primitives.PrimitiveExtension `json:"_preparedDate,omitempty" fhir:"cardinality=0..1"`
	// When the product was dispatched
	WhenHandedOver *primitives.DateTime `json:"whenHandedOver,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for WhenHandedOver
	WhenHandedOverExt *primitives.PrimitiveExtension `json:"_whenHandedOver,omitempty" fhir:"cardinality=0..1"`
	// Where the product was dispatched to
	Destination *Reference `json:"destination,omitempty" fhir:"cardinality=0..1,summary"`
	// Additional notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*,summary"`
	// Specific instructions for use
	UsageInstruction *string `json:"usageInstruction,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for UsageInstruction
	UsageInstructionExt *primitives.PrimitiveExtension `json:"_usageInstruction,omitempty" fhir:"cardinality=0..1"`
}
