// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeBodyStructure is the FHIR resource type name for BodyStructure.
const ResourceTypeBodyStructure = "BodyStructure"

// BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark represents a FHIR BackboneElement for BodyStructure.includedStructure.bodyLandmarkOrientation.distanceFromLandmark.
type BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Measurement device
	Device []CodeableReference `json:"device,omitempty" fhir:"cardinality=0..*"`
	// Measured distance from body landmark
	Value []Quantity `json:"value,omitempty" fhir:"cardinality=0..*"`
}

// BodyStructureIncludedStructureBodyLandmarkOrientation represents a FHIR BackboneElement for BodyStructure.includedStructure.bodyLandmarkOrientation.
type BodyStructureIncludedStructureBodyLandmarkOrientation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Body ]andmark description
	LandmarkDescription []CodeableConcept `json:"landmarkDescription,omitempty" fhir:"cardinality=0..*"`
	// Clockface orientation
	ClockFacePosition []CodeableConcept `json:"clockFacePosition,omitempty" fhir:"cardinality=0..*"`
	// Landmark relative location
	DistanceFromLandmark []BodyStructureIncludedStructureBodyLandmarkOrientationDistanceFromLandmark `json:"distanceFromLandmark,omitempty" fhir:"cardinality=0..*"`
	// Relative landmark surface orientation
	SurfaceOrientation []CodeableConcept `json:"surfaceOrientation,omitempty" fhir:"cardinality=0..*"`
}

// BodyStructureIncludedStructure represents a FHIR BackboneElement for BodyStructure.includedStructure.
type BodyStructureIncludedStructure struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code that represents the included structure
	Structure CodeableConcept `json:"structure" fhir:"cardinality=1..1,required,summary"`
	// Code that represents the included structure laterality
	Laterality *CodeableConcept `json:"laterality,omitempty" fhir:"cardinality=0..1"`
	// Landmark relative location
	BodyLandmarkOrientation []BodyStructureIncludedStructureBodyLandmarkOrientation `json:"bodyLandmarkOrientation,omitempty" fhir:"cardinality=0..*"`
	// Cartesian reference for structure
	SpatialReference []Reference `json:"spatialReference,omitempty" fhir:"cardinality=0..*"`
	// Code that represents the included structure qualifier
	Qualifier []CodeableConcept `json:"qualifier,omitempty" fhir:"cardinality=0..*"`
}

// BodyStructureExcludedStructure represents a FHIR BackboneElement for BodyStructure.excludedStructure.
type BodyStructureExcludedStructure struct {
}

// BodyStructure represents a FHIR BodyStructure.
type BodyStructure struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Bodystructure identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// Kind of Structure
	Morphology *CodeableConcept `json:"morphology,omitempty" fhir:"cardinality=0..1,summary"`
	// Included anatomic location(s)
	IncludedStructure []BodyStructureIncludedStructure `json:"includedStructure,omitempty" fhir:"cardinality=1..*,required"`
	// Excluded anatomic locations(s)
	ExcludedStructure []BodyStructureExcludedStructure `json:"excludedStructure,omitempty" fhir:"cardinality=0..*"`
	// Text description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Attached images
	Image []Attachment `json:"image,omitempty" fhir:"cardinality=0..*"`
	// Who this is about
	Patient Reference `json:"patient" fhir:"cardinality=1..1,required,summary"`
}
