// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"encoding/json"

	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeBundle is the FHIR resource type name for Bundle.
const ResourceTypeBundle = "Bundle"

// BundleLink represents a FHIR BackboneElement for Bundle.link.
type BundleLink struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// See http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1
	Relation string `json:"relation" fhir:"cardinality=1..1,required,summary"`
	// Extension for Relation
	RelationExt *primitives.PrimitiveExtension `json:"_relation,omitempty" fhir:"cardinality=0..1"`
	// Reference details for the link
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
}

// BundleEntryLink represents a FHIR BackboneElement for Bundle.entry.link.
type BundleEntryLink struct {
}

// BundleEntrySearch represents a FHIR BackboneElement for Bundle.entry.search.
type BundleEntrySearch struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// match | include - why this is in the result set
	Mode *string `json:"mode,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Mode
	ModeExt *primitives.PrimitiveExtension `json:"_mode,omitempty" fhir:"cardinality=0..1"`
	// Search ranking (between 0 and 1)
	Score *float64 `json:"score,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Score
	ScoreExt *primitives.PrimitiveExtension `json:"_score,omitempty" fhir:"cardinality=0..1"`
}

// BundleEntryRequest represents a FHIR BackboneElement for Bundle.entry.request.
type BundleEntryRequest struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// GET | HEAD | POST | PUT | DELETE | PATCH
	Method string `json:"method" fhir:"cardinality=1..1,required,summary"`
	// Extension for Method
	MethodExt *primitives.PrimitiveExtension `json:"_method,omitempty" fhir:"cardinality=0..1"`
	// URL for HTTP equivalent of this entry
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// For managing cache validation
	IfNoneMatch *string `json:"ifNoneMatch,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for IfNoneMatch
	IfNoneMatchExt *primitives.PrimitiveExtension `json:"_ifNoneMatch,omitempty" fhir:"cardinality=0..1"`
	// For managing cache currency
	IfModifiedSince *primitives.Instant `json:"ifModifiedSince,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for IfModifiedSince
	IfModifiedSinceExt *primitives.PrimitiveExtension `json:"_ifModifiedSince,omitempty" fhir:"cardinality=0..1"`
	// For managing update contention
	IfMatch *string `json:"ifMatch,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for IfMatch
	IfMatchExt *primitives.PrimitiveExtension `json:"_ifMatch,omitempty" fhir:"cardinality=0..1"`
	// For conditional creates
	IfNoneExist *string `json:"ifNoneExist,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for IfNoneExist
	IfNoneExistExt *primitives.PrimitiveExtension `json:"_ifNoneExist,omitempty" fhir:"cardinality=0..1"`
}

// BundleEntryResponse represents a FHIR BackboneElement for Bundle.entry.response.
type BundleEntryResponse struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Status response code (text optional)
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// The location (if the operation returns a location)
	Location *string `json:"location,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Location
	LocationExt *primitives.PrimitiveExtension `json:"_location,omitempty" fhir:"cardinality=0..1"`
	// The Etag for the resource (if relevant)
	Etag *string `json:"etag,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Etag
	EtagExt *primitives.PrimitiveExtension `json:"_etag,omitempty" fhir:"cardinality=0..1"`
	// Server's date time modified
	LastModified *primitives.Instant `json:"lastModified,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for LastModified
	LastModifiedExt *primitives.PrimitiveExtension `json:"_lastModified,omitempty" fhir:"cardinality=0..1"`
	// OperationOutcome with hints and warnings (for batch/transaction)
	Outcome json.RawMessage `json:"outcome" fhir:"cardinality=0..1,summary"`
	// Extension for Outcome
	OutcomeExt *primitives.PrimitiveExtension `json:"_outcome,omitempty" fhir:"cardinality=0..1"`
}

// BundleEntry represents a FHIR BackboneElement for Bundle.entry.
type BundleEntry struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Links related to this entry
	Link []BundleEntryLink `json:"link,omitempty" fhir:"cardinality=0..*,summary"`
	// URI for resource (e.g. the absolute URL server address, URI for UUID/OID, etc.)
	FullUrl *string `json:"fullUrl,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for FullUrl
	FullUrlExt *primitives.PrimitiveExtension `json:"_fullUrl,omitempty" fhir:"cardinality=0..1"`
	// A resource in the bundle
	Resource json.RawMessage `json:"resource" fhir:"cardinality=0..1,summary"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
	// Search related information
	Search *BundleEntrySearch `json:"search,omitempty" fhir:"cardinality=0..1,summary"`
	// Additional execution information (transaction/batch/history)
	Request *BundleEntryRequest `json:"request,omitempty" fhir:"cardinality=0..1,summary"`
	// Results of execution (transaction/batch/history)
	Response *BundleEntryResponse `json:"response,omitempty" fhir:"cardinality=0..1,summary"`
}

// Bundle represents a FHIR Bundle.
type Bundle struct {
	fhir.Resource
	// Persistent identifier for the bundle
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// document | message | transaction | transaction-response | batch | batch-response | history | searchset | collection | subscription-notification
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// When the bundle was assembled
	Timestamp *primitives.Instant `json:"timestamp,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Timestamp
	TimestampExt *primitives.PrimitiveExtension `json:"_timestamp,omitempty" fhir:"cardinality=0..1"`
	// If search, the total number of matches
	Total *uint `json:"total,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Total
	TotalExt *primitives.PrimitiveExtension `json:"_total,omitempty" fhir:"cardinality=0..1"`
	// Links related to this Bundle
	Link []BundleLink `json:"link,omitempty" fhir:"cardinality=0..*,summary"`
	// Entry in the bundle - will have a resource or information
	Entry []BundleEntry `json:"entry,omitempty" fhir:"cardinality=0..*,summary"`
	// Digital Signature
	Signature *Signature `json:"signature,omitempty" fhir:"cardinality=0..1,summary"`
	// Issues with the Bundle
	Issues json.RawMessage `json:"issues" fhir:"cardinality=0..1,summary"`
	// Extension for Issues
	IssuesExt *primitives.PrimitiveExtension `json:"_issues,omitempty" fhir:"cardinality=0..1"`
}
