// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeClinicalImpression is the FHIR resource type name for ClinicalImpression.
const ResourceTypeClinicalImpression = "ClinicalImpression"

// ClinicalImpressionFinding represents a FHIR BackboneElement for ClinicalImpression.finding.
type ClinicalImpressionFinding struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// What was found
	Item *CodeableReference `json:"item,omitempty" fhir:"cardinality=0..1"`
	// Which investigations support finding
	Basis *string `json:"basis,omitempty" fhir:"cardinality=0..1"`
	// Extension for Basis
	BasisExt *primitives.PrimitiveExtension `json:"_basis,omitempty" fhir:"cardinality=0..1"`
}

// ClinicalImpression represents a FHIR ClinicalImpression.
type ClinicalImpression struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1"`
	// Why/how the assessment was performed
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Patient or group assessed
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// The Encounter during which this ClinicalImpression was created
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Time of assessment - dateTime option
	EffectiveDateTime *primitives.DateTime `json:"effectiveDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// Extension for EffectiveDateTime
	EffectiveDateTimeExt *primitives.PrimitiveExtension `json:"_effectiveDateTime,omitempty" fhir:"cardinality=0..1"`
	// Time of assessment - Period option
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=effective"`
	// When the assessment was documented
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// The clinician performing the assessment
	Performer *Reference `json:"performer,omitempty" fhir:"cardinality=0..1,summary"`
	// Reference to last assessment
	Previous *Reference `json:"previous,omitempty" fhir:"cardinality=0..1"`
	// Relevant impressions of patient state
	Problem []Reference `json:"problem,omitempty" fhir:"cardinality=0..*,summary"`
	// Change in the status/pattern of a subject's condition since previously assessed, such as worsening, improving, or no change
	ChangePattern *CodeableConcept `json:"changePattern,omitempty" fhir:"cardinality=0..1"`
	// Clinical Protocol followed
	Protocol []string `json:"protocol,omitempty" fhir:"cardinality=0..*"`
	// Extension for Protocol
	ProtocolExt *primitives.PrimitiveExtension `json:"_protocol,omitempty" fhir:"cardinality=0..1"`
	// Summary of the assessment
	Summary *string `json:"summary,omitempty" fhir:"cardinality=0..1"`
	// Extension for Summary
	SummaryExt *primitives.PrimitiveExtension `json:"_summary,omitempty" fhir:"cardinality=0..1"`
	// Possible or likely findings and diagnoses
	Finding []ClinicalImpressionFinding `json:"finding,omitempty" fhir:"cardinality=0..*"`
	// Estimate of likely outcome
	PrognosisCodeableConcept []CodeableConcept `json:"prognosisCodeableConcept,omitempty" fhir:"cardinality=0..*"`
	// RiskAssessment expressing likely outcome
	PrognosisReference []Reference `json:"prognosisReference,omitempty" fhir:"cardinality=0..*"`
	// Information supporting the clinical impression
	SupportingInfo []Reference `json:"supportingInfo,omitempty" fhir:"cardinality=0..*"`
	// Comments made about the ClinicalImpression
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
