// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// CodeableReference represents a FHIR CodeableReference.
type CodeableReference struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Reference to a concept (by class)
	Concept *CodeableConcept `json:"concept,omitempty" fhir:"cardinality=0..1,summary"`
	// Reference to a resource (by instance)
	Reference *Reference `json:"reference,omitempty" fhir:"cardinality=0..1,summary"`
}
