// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeConditionDefinition is the FHIR resource type name for ConditionDefinition.
const ResourceTypeConditionDefinition = "ConditionDefinition"

// ConditionDefinitionObservation represents a FHIR BackboneElement for ConditionDefinition.observation.
type ConditionDefinitionObservation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Category that is relevant
	Category *CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..1"`
	// Code for relevant Observation
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
}

// ConditionDefinitionMedication represents a FHIR BackboneElement for ConditionDefinition.medication.
type ConditionDefinitionMedication struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Category that is relevant
	Category *CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..1"`
	// Code for relevant Medication
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
}

// ConditionDefinitionPrecondition represents a FHIR BackboneElement for ConditionDefinition.precondition.
type ConditionDefinitionPrecondition struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// sensitive | specific
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Code for relevant Observation
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required"`
	// Value of Observation - CodeableConcept option
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of Observation - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,choice=value"`
}

// ConditionDefinitionQuestionnaire represents a FHIR BackboneElement for ConditionDefinition.questionnaire.
type ConditionDefinitionQuestionnaire struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// preadmit | diff-diagnosis | outcome
	Purpose string `json:"purpose" fhir:"cardinality=1..1,required"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Specific Questionnaire
	Reference Reference `json:"reference" fhir:"cardinality=1..1,required"`
}

// ConditionDefinitionPlan represents a FHIR BackboneElement for ConditionDefinition.plan.
type ConditionDefinitionPlan struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Use for the plan
	Role *CodeableConcept `json:"role,omitempty" fhir:"cardinality=0..1"`
	// The actual plan
	Reference Reference `json:"reference" fhir:"cardinality=1..1,required"`
}

// ConditionDefinition represents a FHIR ConditionDefinition.
type ConditionDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this condition definition, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the condition definition
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the condition definition
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this condition definition (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this condition definition (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Subordinate title of the event definition
	Subtitle *string `json:"subtitle,omitempty" fhir:"cardinality=0..1"`
	// Extension for Subtitle
	SubtitleExt *primitives.PrimitiveExtension `json:"_subtitle,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the condition definition
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for condition definition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Identification of the condition, problem or diagnosis
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Subjective severity of condition
	Severity *CodeableConcept `json:"severity,omitempty" fhir:"cardinality=0..1,summary"`
	// Anatomical location, if relevant
	BodySite *CodeableConcept `json:"bodySite,omitempty" fhir:"cardinality=0..1,summary"`
	// Stage/grade, usually assessed formally
	Stage *CodeableConcept `json:"stage,omitempty" fhir:"cardinality=0..1,summary"`
	// Whether Severity is appropriate
	HasSeverity *bool `json:"hasSeverity,omitempty" fhir:"cardinality=0..1"`
	// Extension for HasSeverity
	HasSeverityExt *primitives.PrimitiveExtension `json:"_hasSeverity,omitempty" fhir:"cardinality=0..1"`
	// Whether bodySite is appropriate
	HasBodySite *bool `json:"hasBodySite,omitempty" fhir:"cardinality=0..1"`
	// Extension for HasBodySite
	HasBodySiteExt *primitives.PrimitiveExtension `json:"_hasBodySite,omitempty" fhir:"cardinality=0..1"`
	// Whether stage is appropriate
	HasStage *bool `json:"hasStage,omitempty" fhir:"cardinality=0..1"`
	// Extension for HasStage
	HasStageExt *primitives.PrimitiveExtension `json:"_hasStage,omitempty" fhir:"cardinality=0..1"`
	// Formal Definition for the condition
	Definition []string `json:"definition,omitempty" fhir:"cardinality=0..*"`
	// Extension for Definition
	DefinitionExt *primitives.PrimitiveExtension `json:"_definition,omitempty" fhir:"cardinality=0..1"`
	// Observations particularly relevant to this condition
	Observation []ConditionDefinitionObservation `json:"observation,omitempty" fhir:"cardinality=0..*"`
	// Medications particularly relevant for this condition
	Medication []ConditionDefinitionMedication `json:"medication,omitempty" fhir:"cardinality=0..*"`
	// Observation that suggets this condition
	Precondition []ConditionDefinitionPrecondition `json:"precondition,omitempty" fhir:"cardinality=0..*"`
	// Appropriate team for this condition
	Team []Reference `json:"team,omitempty" fhir:"cardinality=0..*"`
	// Questionnaire for this condition
	Questionnaire []ConditionDefinitionQuestionnaire `json:"questionnaire,omitempty" fhir:"cardinality=0..*"`
	// Plan that is appropriate
	Plan []ConditionDefinitionPlan `json:"plan,omitempty" fhir:"cardinality=0..*"`
}
