// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ContactPoint represents a FHIR ContactPoint.
type ContactPoint struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// phone | fax | email | pager | url | sms | other
	System *string `json:"system,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for System
	SystemExt *primitives.PrimitiveExtension `json:"_system,omitempty" fhir:"cardinality=0..1"`
	// The actual contact point details
	Value *string `json:"value,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// home | work | temp | old | mobile - purpose of this contact point
	Use *string `json:"use,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Use
	UseExt *primitives.PrimitiveExtension `json:"_use,omitempty" fhir:"cardinality=0..1"`
	// Specify preferred order of use (1 = highest)
	Rank *int `json:"rank,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Rank
	RankExt *primitives.PrimitiveExtension `json:"_rank,omitempty" fhir:"cardinality=0..1"`
	// Time period when the contact point was/is in use
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
}
