// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeDeviceRequest is the FHIR resource type name for DeviceRequest.
const ResourceTypeDeviceRequest = "DeviceRequest"

// DeviceRequestParameter represents a FHIR BackboneElement for DeviceRequest.parameter.
type DeviceRequestParameter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Device detail
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Value of detail - CodeableConcept option
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of detail - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of detail - Range option
	ValueRange *Range `json:"valueRange,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of detail - boolean option
	ValueBoolean *bool `json:"valueBoolean,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
}

// DeviceRequest represents a FHIR DeviceRequest.
type DeviceRequest struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Request identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// What request fulfills
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// What request replaces
	Replaces []Reference `json:"replaces,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifier of composite request
	GroupIdentifier *Identifier `json:"groupIdentifier,omitempty" fhir:"cardinality=0..1,summary"`
	// draft | active | on-hold | revoked | completed | entered-in-error | unknown
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// proposal | plan | directive | order | original-order | reflex-order | filler-order | instance-order | option
	Intent string `json:"intent" fhir:"cardinality=1..1,required,summary"`
	// Extension for Intent
	IntentExt *primitives.PrimitiveExtension `json:"_intent,omitempty" fhir:"cardinality=0..1"`
	// routine | urgent | asap | stat
	Priority *string `json:"priority,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// True if the request is to stop or not to start using the device
	DoNotPerform *bool `json:"doNotPerform,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DoNotPerform
	DoNotPerformExt *primitives.PrimitiveExtension `json:"_doNotPerform,omitempty" fhir:"cardinality=0..1"`
	// Device requested
	Code CodeableReference `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Quantity of devices to supply
	Quantity *int `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Extension for Quantity
	QuantityExt *primitives.PrimitiveExtension `json:"_quantity,omitempty" fhir:"cardinality=0..1"`
	// Device details
	Parameter []DeviceRequestParameter `json:"parameter,omitempty" fhir:"cardinality=0..*"`
	// Focus of request
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Encounter motivating request
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Desired time or schedule for use - dateTime option
	OccurrenceDateTime *primitives.DateTime `json:"occurrenceDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Extension for OccurrenceDateTime
	OccurrenceDateTimeExt *primitives.PrimitiveExtension `json:"_occurrenceDateTime,omitempty" fhir:"cardinality=0..1"`
	// Desired time or schedule for use - Period option
	OccurrencePeriod *Period `json:"occurrencePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Desired time or schedule for use - Timing option
	OccurrenceTiming *Timing `json:"occurrenceTiming,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When recorded
	AuthoredOn *primitives.DateTime `json:"authoredOn,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AuthoredOn
	AuthoredOnExt *primitives.PrimitiveExtension `json:"_authoredOn,omitempty" fhir:"cardinality=0..1"`
	// Who/what submitted the device request
	Requester *Reference `json:"requester,omitempty" fhir:"cardinality=0..1,summary"`
	// Requested Filler
	Performer *CodeableReference `json:"performer,omitempty" fhir:"cardinality=0..1,summary"`
	// Coded/Linked Reason for request
	Reason []CodeableReference `json:"reason,omitempty" fhir:"cardinality=0..*,summary"`
	// PRN status of request
	AsNeeded *bool `json:"asNeeded,omitempty" fhir:"cardinality=0..1"`
	// Extension for AsNeeded
	AsNeededExt *primitives.PrimitiveExtension `json:"_asNeeded,omitempty" fhir:"cardinality=0..1"`
	// Device usage reason
	AsNeededFor *CodeableConcept `json:"asNeededFor,omitempty" fhir:"cardinality=0..1"`
	// Associated insurance coverage
	Insurance []Reference `json:"insurance,omitempty" fhir:"cardinality=0..*"`
	// Additional clinical information
	SupportingInfo []Reference `json:"supportingInfo,omitempty" fhir:"cardinality=0..*"`
	// Notes or comments
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Request provenance
	RelevantHistory []Reference `json:"relevantHistory,omitempty" fhir:"cardinality=0..*"`
}
