// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeDeviceMetric is the FHIR resource type name for DeviceMetric.
const ResourceTypeDeviceMetric = "DeviceMetric"

// DeviceMetricCalibration represents a FHIR BackboneElement for DeviceMetric.calibration.
type DeviceMetricCalibration struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// unspecified | offset | gain | two-point
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// not-calibrated | calibration-required | calibrated | unspecified
	State *string `json:"state,omitempty" fhir:"cardinality=0..1"`
	// Extension for State
	StateExt *primitives.PrimitiveExtension `json:"_state,omitempty" fhir:"cardinality=0..1"`
	// Describes the time last calibration has been performed
	Time *primitives.Instant `json:"time,omitempty" fhir:"cardinality=0..1"`
	// Extension for Time
	TimeExt *primitives.PrimitiveExtension `json:"_time,omitempty" fhir:"cardinality=0..1"`
}

// DeviceMetric represents a FHIR DeviceMetric.
type DeviceMetric struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Instance identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Identity of metric, for example Heart Rate or PEEP Setting
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Unit of Measure for the Metric
	Unit *CodeableConcept `json:"unit,omitempty" fhir:"cardinality=0..1,summary"`
	// Describes the link to the Device
	Device Reference `json:"device" fhir:"cardinality=1..1,required,summary"`
	// on | off | standby | entered-in-error
	OperationalStatus *string `json:"operationalStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for OperationalStatus
	OperationalStatusExt *primitives.PrimitiveExtension `json:"_operationalStatus,omitempty" fhir:"cardinality=0..1"`
	// Color name (from CSS4) or #RRGGBB code
	Color *string `json:"color,omitempty" fhir:"cardinality=0..1"`
	// Extension for Color
	ColorExt *primitives.PrimitiveExtension `json:"_color,omitempty" fhir:"cardinality=0..1"`
	// measurement | setting | calculation | unspecified
	Category string `json:"category" fhir:"cardinality=1..1,required,summary"`
	// Extension for Category
	CategoryExt *primitives.PrimitiveExtension `json:"_category,omitempty" fhir:"cardinality=0..1"`
	// Indicates how often the metric is taken or recorded
	MeasurementFrequency *Quantity `json:"measurementFrequency,omitempty" fhir:"cardinality=0..1"`
	// Describes the calibrations that have been performed or that are required to be performed
	Calibration []DeviceMetricCalibration `json:"calibration,omitempty" fhir:"cardinality=0..*"`
}
