// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeDeviceDispense is the FHIR resource type name for DeviceDispense.
const ResourceTypeDeviceDispense = "DeviceDispense"

// DeviceDispensePerformer represents a FHIR BackboneElement for DeviceDispense.performer.
type DeviceDispensePerformer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Who performed the dispense and what they did
	Function *CodeableConcept `json:"function,omitempty" fhir:"cardinality=0..1"`
	// Individual who was performing
	Actor Reference `json:"actor" fhir:"cardinality=1..1,required"`
}

// DeviceDispense represents a FHIR DeviceDispense.
type DeviceDispense struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for this dispensation
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// The order or request that this dispense is fulfilling
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*"`
	// The bigger event that this dispense is a part of
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*"`
	// preparation | in-progress | cancelled | on-hold | completed | entered-in-error | stopped | declined | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Why a dispense was or was not performed
	StatusReason *CodeableReference `json:"statusReason,omitempty" fhir:"cardinality=0..1"`
	// Type of device dispense
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*"`
	// What device was supplied
	Device CodeableReference `json:"device" fhir:"cardinality=1..1,required,summary"`
	// Who the dispense is for
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Who collected the device or where the medication was delivered
	Receiver *Reference `json:"receiver,omitempty" fhir:"cardinality=0..1"`
	// Encounter associated with event
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1"`
	// Information that supports the dispensing of the device
	SupportingInformation []Reference `json:"supportingInformation,omitempty" fhir:"cardinality=0..*"`
	// Who performed event
	Performer []DeviceDispensePerformer `json:"performer,omitempty" fhir:"cardinality=0..*"`
	// Where the dispense occurred
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1"`
	// Trial fill, partial fill, emergency fill, etc
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Amount dispensed
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// When product was packaged and reviewed
	PreparedDate *primitives.DateTime `json:"preparedDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for PreparedDate
	PreparedDateExt *primitives.PrimitiveExtension `json:"_preparedDate,omitempty" fhir:"cardinality=0..1"`
	// When product was given out
	WhenHandedOver *primitives.DateTime `json:"whenHandedOver,omitempty" fhir:"cardinality=0..1"`
	// Extension for WhenHandedOver
	WhenHandedOverExt *primitives.PrimitiveExtension `json:"_whenHandedOver,omitempty" fhir:"cardinality=0..1"`
	// Where the device was sent or should be sent
	Destination *Reference `json:"destination,omitempty" fhir:"cardinality=0..1"`
	// Information about the dispense
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Full representation of the usage instructions
	UsageInstruction *string `json:"usageInstruction,omitempty" fhir:"cardinality=0..1"`
	// Extension for UsageInstruction
	UsageInstructionExt *primitives.PrimitiveExtension `json:"_usageInstruction,omitempty" fhir:"cardinality=0..1"`
	// A list of relevant lifecycle events
	EventHistory []Reference `json:"eventHistory,omitempty" fhir:"cardinality=0..*"`
}
