// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// Distance represents a FHIR Distance.
type Distance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Numerical value (with implicit precision)
	Value *float64 `json:"value,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// < | <= | >= | > | ad - how to understand the value
	Comparator *string `json:"comparator,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Comparator
	ComparatorExt *primitives.PrimitiveExtension `json:"_comparator,omitempty" fhir:"cardinality=0..1"`
	// Unit representation
	Unit *string `json:"unit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Unit
	UnitExt *primitives.PrimitiveExtension `json:"_unit,omitempty" fhir:"cardinality=0..1"`
	// System that defines coded unit form
	System *string `json:"system,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for System
	SystemExt *primitives.PrimitiveExtension `json:"_system,omitempty" fhir:"cardinality=0..1"`
	// Coded form of the unit
	Code *string `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
}
