// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeDocumentReference is the FHIR resource type name for DocumentReference.
const ResourceTypeDocumentReference = "DocumentReference"

// DocumentReferenceAttester represents a FHIR BackboneElement for DocumentReference.attester.
type DocumentReferenceAttester struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// personal | professional | legal | official
	Mode CodeableConcept `json:"mode" fhir:"cardinality=1..1,required"`
	// When the document was attested
	Time *primitives.DateTime `json:"time,omitempty" fhir:"cardinality=0..1"`
	// Extension for Time
	TimeExt *primitives.PrimitiveExtension `json:"_time,omitempty" fhir:"cardinality=0..1"`
	// Who attested the document
	Party *Reference `json:"party,omitempty" fhir:"cardinality=0..1"`
}

// DocumentReferenceRelatesTo represents a FHIR BackboneElement for DocumentReference.relatesTo.
type DocumentReferenceRelatesTo struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The relationship type with another document
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Target of the relationship
	Target Reference `json:"target" fhir:"cardinality=1..1,required,summary"`
}

// DocumentReferenceContentProfile represents a FHIR BackboneElement for DocumentReference.content.profile.
type DocumentReferenceContentProfile struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code|uri|canonical - Coding option
	ValueCoding Coding `json:"valueCoding" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Code|uri|canonical - uri option
	ValueURI string `json:"valueURI" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueURI
	ValueURIExt *primitives.PrimitiveExtension `json:"_valueURI,omitempty" fhir:"cardinality=0..1"`
	// Code|uri|canonical - canonical option
	ValueCanonical string `json:"valueCanonical" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueCanonical
	ValueCanonicalExt *primitives.PrimitiveExtension `json:"_valueCanonical,omitempty" fhir:"cardinality=0..1"`
}

// DocumentReferenceContent represents a FHIR BackboneElement for DocumentReference.content.
type DocumentReferenceContent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Where to access the document
	Attachment Attachment `json:"attachment" fhir:"cardinality=1..1,required,summary"`
	// Content profile rules for the document
	Profile []DocumentReferenceContentProfile `json:"profile,omitempty" fhir:"cardinality=0..*,summary"`
}

// DocumentReference represents a FHIR DocumentReference.
type DocumentReference struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifiers for the document
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// An explicitly assigned identifer of a variation of the content in the DocumentReference
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Procedure that caused this media to be created
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*"`
	// current | superseded | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// registered | partial | preliminary | final | amended | corrected | appended | cancelled | entered-in-error | deprecated | unknown
	DocStatus *string `json:"docStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DocStatus
	DocStatusExt *primitives.PrimitiveExtension `json:"_docStatus,omitempty" fhir:"cardinality=0..1"`
	// Imaging modality used
	Modality []CodeableConcept `json:"modality,omitempty" fhir:"cardinality=0..*,summary"`
	// Kind of document (LOINC if possible)
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Categorization of document
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Who/what is the subject of the document
	Subject *Reference `json:"subject,omitempty" fhir:"cardinality=0..1,summary"`
	// Context of the document content
	Context []Reference `json:"context,omitempty" fhir:"cardinality=0..*"`
	// Main clinical acts documented
	Event []CodeableReference `json:"event,omitempty" fhir:"cardinality=0..*"`
	// Body part included
	BodySite []CodeableReference `json:"bodySite,omitempty" fhir:"cardinality=0..*,summary"`
	// Kind of facility where patient was seen
	FacilityType *CodeableConcept `json:"facilityType,omitempty" fhir:"cardinality=0..1"`
	// Additional details about where the content was created (e.g. clinical specialty)
	PracticeSetting *CodeableConcept `json:"practiceSetting,omitempty" fhir:"cardinality=0..1"`
	// Time of service that is being documented
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// When this document reference was created
	Date *primitives.Instant `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Who and/or what authored the document
	Author []Reference `json:"author,omitempty" fhir:"cardinality=0..*,summary"`
	// Attests to accuracy of the document
	Attester []DocumentReferenceAttester `json:"attester,omitempty" fhir:"cardinality=0..*"`
	// Organization which maintains the document
	Custodian *Reference `json:"custodian,omitempty" fhir:"cardinality=0..1"`
	// Relationships to other documents
	RelatesTo []DocumentReferenceRelatesTo `json:"relatesTo,omitempty" fhir:"cardinality=0..*,summary"`
	// Human-readable description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Document security-tags
	SecurityLabel []CodeableConcept `json:"securityLabel,omitempty" fhir:"cardinality=0..*,summary"`
	// Document referenced
	Content []DocumentReferenceContent `json:"content,omitempty" fhir:"cardinality=1..*,required,summary"`
}
