// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeEnrollmentResponse is the FHIR resource type name for EnrollmentResponse.
const ResourceTypeEnrollmentResponse = "EnrollmentResponse"

// EnrollmentResponse represents a FHIR EnrollmentResponse.
type EnrollmentResponse struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business Identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// active | cancelled | draft | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Claim reference
	Request *Reference `json:"request,omitempty" fhir:"cardinality=0..1"`
	// queued | complete | error | partial
	Outcome *string `json:"outcome,omitempty" fhir:"cardinality=0..1"`
	// Extension for Outcome
	OutcomeExt *primitives.PrimitiveExtension `json:"_outcome,omitempty" fhir:"cardinality=0..1"`
	// Disposition Message
	Disposition *string `json:"disposition,omitempty" fhir:"cardinality=0..1"`
	// Extension for Disposition
	DispositionExt *primitives.PrimitiveExtension `json:"_disposition,omitempty" fhir:"cardinality=0..1"`
	// Creation date
	Created *primitives.DateTime `json:"created,omitempty" fhir:"cardinality=0..1"`
	// Extension for Created
	CreatedExt *primitives.PrimitiveExtension `json:"_created,omitempty" fhir:"cardinality=0..1"`
	// Insurer
	Organization *Reference `json:"organization,omitempty" fhir:"cardinality=0..1"`
	// Responsible practitioner
	RequestProvider *Reference `json:"requestProvider,omitempty" fhir:"cardinality=0..1"`
}
