// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeEnrollmentRequest is the FHIR resource type name for EnrollmentRequest.
const ResourceTypeEnrollmentRequest = "EnrollmentRequest"

// EnrollmentRequest represents a FHIR EnrollmentRequest.
type EnrollmentRequest struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business Identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// active | cancelled | draft | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Creation date
	Created *primitives.DateTime `json:"created,omitempty" fhir:"cardinality=0..1"`
	// Extension for Created
	CreatedExt *primitives.PrimitiveExtension `json:"_created,omitempty" fhir:"cardinality=0..1"`
	// Target
	Insurer *Reference `json:"insurer,omitempty" fhir:"cardinality=0..1"`
	// Responsible practitioner
	Provider *Reference `json:"provider,omitempty" fhir:"cardinality=0..1"`
	// The subject to be enrolled
	Candidate *Reference `json:"candidate,omitempty" fhir:"cardinality=0..1"`
	// Insurance information
	Coverage *Reference `json:"coverage,omitempty" fhir:"cardinality=0..1"`
}
