// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeEvidenceVariable is the FHIR resource type name for EvidenceVariable.
const ResourceTypeEvidenceVariable = "EvidenceVariable"

// EvidenceVariableCharacteristicDefinitionByTypeAndValue represents a FHIR BackboneElement for EvidenceVariable.characteristic.definitionByTypeAndValue.
type EvidenceVariableCharacteristicDefinitionByTypeAndValue struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Expresses the type of characteristic
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Method for how the characteristic value was determined
	Method []CodeableConcept `json:"method,omitempty" fhir:"cardinality=0..*"`
	// Device used for determining characteristic
	Device *Reference `json:"device,omitempty" fhir:"cardinality=0..1"`
	// Defines the characteristic when coupled with characteristic.type - CodeableConcept option
	ValueCodeableConcept CodeableConcept `json:"valueCodeableConcept" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Defines the characteristic when coupled with characteristic.type - boolean option
	ValueBoolean bool `json:"valueBoolean" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Defines the characteristic when coupled with characteristic.type - Quantity option
	ValueQuantity Quantity `json:"valueQuantity" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Defines the characteristic when coupled with characteristic.type - Range option
	ValueRange Range `json:"valueRange" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Defines the characteristic when coupled with characteristic.type - Reference option
	ValueReference Reference `json:"valueReference" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Defines the characteristic when coupled with characteristic.type - id option
	ValueID string `json:"valueID" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueID
	ValueIDExt *primitives.PrimitiveExtension `json:"_valueID,omitempty" fhir:"cardinality=0..1"`
	// Reference point for valueQuantity or valueRange
	Offset *CodeableConcept `json:"offset,omitempty" fhir:"cardinality=0..1"`
}

// EvidenceVariableCharacteristicDefinitionByCombinationCharacteristic represents a FHIR BackboneElement for EvidenceVariable.characteristic.definitionByCombination.characteristic.
type EvidenceVariableCharacteristicDefinitionByCombinationCharacteristic struct {
}

// EvidenceVariableCharacteristicDefinitionByCombination represents a FHIR BackboneElement for EvidenceVariable.characteristic.definitionByCombination.
type EvidenceVariableCharacteristicDefinitionByCombination struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// all-of | any-of | at-least | at-most | statistical | net-effect | dataset
	Code string `json:"code" fhir:"cardinality=1..1,required"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Provides the value of "n" when "at-least" or "at-most" codes are used
	Threshold *int `json:"threshold,omitempty" fhir:"cardinality=0..1"`
	// Extension for Threshold
	ThresholdExt *primitives.PrimitiveExtension `json:"_threshold,omitempty" fhir:"cardinality=0..1"`
	// A defining factor of the characteristic
	Characteristic []EvidenceVariableCharacteristicDefinitionByCombinationCharacteristic `json:"characteristic,omitempty" fhir:"cardinality=1..*,required"`
}

// EvidenceVariableCharacteristicTimeFromEvent represents a FHIR BackboneElement for EvidenceVariable.characteristic.timeFromEvent.
type EvidenceVariableCharacteristicTimeFromEvent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Human readable description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// The event used as a base point (reference point) in time - CodeableConcept option
	EventCodeableConcept *CodeableConcept `json:"eventCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=event"`
	// The event used as a base point (reference point) in time - Reference option
	EventReference *Reference `json:"eventReference,omitempty" fhir:"cardinality=0..1,choice=event"`
	// The event used as a base point (reference point) in time - dateTime option
	EventDateTime *primitives.DateTime `json:"eventDateTime,omitempty" fhir:"cardinality=0..1,choice=event"`
	// Extension for EventDateTime
	EventDateTimeExt *primitives.PrimitiveExtension `json:"_eventDateTime,omitempty" fhir:"cardinality=0..1"`
	// The event used as a base point (reference point) in time - id option
	EventID *string `json:"eventID,omitempty" fhir:"cardinality=0..1,choice=event"`
	// Extension for EventID
	EventIDExt *primitives.PrimitiveExtension `json:"_eventID,omitempty" fhir:"cardinality=0..1"`
	// Used to express the observation at a defined amount of time before or after the event
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Used to express the observation within a period before and/or after the event
	Range *Range `json:"range,omitempty" fhir:"cardinality=0..1"`
}

// EvidenceVariableCharacteristic represents a FHIR BackboneElement for EvidenceVariable.characteristic.
type EvidenceVariableCharacteristic struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for internal linking
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// Natural language description of the characteristic
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Whether the characteristic is an inclusion criterion or exclusion criterion
	Exclude *bool `json:"exclude,omitempty" fhir:"cardinality=0..1"`
	// Extension for Exclude
	ExcludeExt *primitives.PrimitiveExtension `json:"_exclude,omitempty" fhir:"cardinality=0..1"`
	// Defines the characteristic (without using type and value) by a Reference
	DefinitionReference *Reference `json:"definitionReference,omitempty" fhir:"cardinality=0..1,summary"`
	// Defines the characteristic (without using type and value) by a Canonical
	DefinitionCanonical *string `json:"definitionCanonical,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DefinitionCanonical
	DefinitionCanonicalExt *primitives.PrimitiveExtension `json:"_definitionCanonical,omitempty" fhir:"cardinality=0..1"`
	// Defines the characteristic (without using type and value) by a CodeableConcept
	DefinitionCodeableConcept *CodeableConcept `json:"definitionCodeableConcept,omitempty" fhir:"cardinality=0..1,summary"`
	// Defines the characteristic (without using type and value) by an expression
	DefinitionExpression *Expression `json:"definitionExpression,omitempty" fhir:"cardinality=0..1,summary"`
	// Defines the characteristic (without using type and value) by an id
	DefinitionId *string `json:"definitionId,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DefinitionId
	DefinitionIdExt *primitives.PrimitiveExtension `json:"_definitionId,omitempty" fhir:"cardinality=0..1"`
	// Defines the characteristic using type and value
	DefinitionByTypeAndValue *EvidenceVariableCharacteristicDefinitionByTypeAndValue `json:"definitionByTypeAndValue,omitempty" fhir:"cardinality=0..1,summary"`
	// Used to specify how two or more characteristics are combined
	DefinitionByCombination *EvidenceVariableCharacteristicDefinitionByCombination `json:"definitionByCombination,omitempty" fhir:"cardinality=0..1"`
	// Number of occurrences meeting the characteristic - Quantity option
	InstancesQuantity *Quantity `json:"instancesQuantity,omitempty" fhir:"cardinality=0..1,choice=instances"`
	// Number of occurrences meeting the characteristic - Range option
	InstancesRange *Range `json:"instancesRange,omitempty" fhir:"cardinality=0..1,choice=instances"`
	// Length of time in which the characteristic is met - Quantity option
	DurationQuantity *Quantity `json:"durationQuantity,omitempty" fhir:"cardinality=0..1,choice=duration"`
	// Length of time in which the characteristic is met - Range option
	DurationRange *Range `json:"durationRange,omitempty" fhir:"cardinality=0..1,choice=duration"`
	// Timing in which the characteristic is determined
	TimeFromEvent []EvidenceVariableCharacteristicTimeFromEvent `json:"timeFromEvent,omitempty" fhir:"cardinality=0..*"`
}

// EvidenceVariableCategory represents a FHIR BackboneElement for EvidenceVariable.category.
type EvidenceVariableCategory struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of the grouping
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Definition of the grouping - CodeableConcept option
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Definition of the grouping - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Definition of the grouping - Range option
	ValueRange *Range `json:"valueRange,omitempty" fhir:"cardinality=0..1,choice=value"`
}

// EvidenceVariable represents a FHIR EvidenceVariable.
type EvidenceVariable struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this evidence variable, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the evidence variable
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the evidence variable
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this evidence variable (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this evidence variable (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Title for use in informal contexts
	ShortTitle *string `json:"shortTitle,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ShortTitle
	ShortTitleExt *primitives.PrimitiveExtension `json:"_shortTitle,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the evidence variable
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Used for footnotes or explanatory notes
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this EvidenceVariable is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// When the resource was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the resource was last reviewed by the publisher
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the resource is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1"`
	// Who authored the content
	Author []ContactDetail `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who edited the content
	Editor []ContactDetail `json:"editor,omitempty" fhir:"cardinality=0..*"`
	// Who reviewed the content
	Reviewer []ContactDetail `json:"reviewer,omitempty" fhir:"cardinality=0..*"`
	// Who endorsed the content
	Endorser []ContactDetail `json:"endorser,omitempty" fhir:"cardinality=0..*"`
	// Additional documentation, citations, etc
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// Actual or conceptual
	Actual *bool `json:"actual,omitempty" fhir:"cardinality=0..1"`
	// Extension for Actual
	ActualExt *primitives.PrimitiveExtension `json:"_actual,omitempty" fhir:"cardinality=0..1"`
	// A defining factor of the EvidenceVariable
	Characteristic []EvidenceVariableCharacteristic `json:"characteristic,omitempty" fhir:"cardinality=0..*,summary"`
	// continuous | dichotomous | ordinal | polychotomous
	Handling *string `json:"handling,omitempty" fhir:"cardinality=0..1"`
	// Extension for Handling
	HandlingExt *primitives.PrimitiveExtension `json:"_handling,omitempty" fhir:"cardinality=0..1"`
	// A grouping for ordinal or polychotomous variables
	Category []EvidenceVariableCategory `json:"category,omitempty" fhir:"cardinality=0..*"`
}
