// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeFlag is the FHIR resource type name for Flag.
const ResourceTypeFlag = "Flag"

// Flag represents a FHIR Flag.
type Flag struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// active | inactive | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Clinical, administrative, etc
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Coded or textual message to display to user
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required,summary"`
	// Who/What is flag about?
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Time period when flag is active
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Alert relevant during encounter
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Flag creator
	Author *Reference `json:"author,omitempty" fhir:"cardinality=0..1,summary"`
}
