// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeGoal is the FHIR resource type name for Goal.
const ResourceTypeGoal = "Goal"

// GoalTarget represents a FHIR BackboneElement for Goal.target.
type GoalTarget struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The parameter whose value is being tracked
	Measure *CodeableConcept `json:"measure,omitempty" fhir:"cardinality=0..1,summary"`
	// The target value to be achieved - Quantity option
	DetailQuantity *Quantity `json:"detailQuantity,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// The target value to be achieved - Range option
	DetailRange *Range `json:"detailRange,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// The target value to be achieved - CodeableConcept option
	DetailCodeableConcept *CodeableConcept `json:"detailCodeableConcept,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// The target value to be achieved - string option
	DetailString *string `json:"detailString,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// Extension for DetailString
	DetailStringExt *primitives.PrimitiveExtension `json:"_detailString,omitempty" fhir:"cardinality=0..1"`
	// The target value to be achieved - boolean option
	DetailBoolean *bool `json:"detailBoolean,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// Extension for DetailBoolean
	DetailBooleanExt *primitives.PrimitiveExtension `json:"_detailBoolean,omitempty" fhir:"cardinality=0..1"`
	// The target value to be achieved - integer option
	DetailInteger *int `json:"detailInteger,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// Extension for DetailInteger
	DetailIntegerExt *primitives.PrimitiveExtension `json:"_detailInteger,omitempty" fhir:"cardinality=0..1"`
	// The target value to be achieved - Ratio option
	DetailRatio *Ratio `json:"detailRatio,omitempty" fhir:"cardinality=0..1,summary,choice=detail"`
	// Reach goal on or before - date option
	DueDate *primitives.Date `json:"dueDate,omitempty" fhir:"cardinality=0..1,summary,choice=due"`
	// Extension for DueDate
	DueDateExt *primitives.PrimitiveExtension `json:"_dueDate,omitempty" fhir:"cardinality=0..1"`
	// Reach goal on or before - Duration option
	DueDuration *Duration `json:"dueDuration,omitempty" fhir:"cardinality=0..1,summary,choice=due"`
}

// Goal represents a FHIR Goal.
type Goal struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Ids for this goal
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// proposed | planned | accepted | active | on-hold | completed | cancelled | entered-in-error | rejected
	LifecycleStatus string `json:"lifecycleStatus" fhir:"cardinality=1..1,required,summary"`
	// Extension for LifecycleStatus
	LifecycleStatusExt *primitives.PrimitiveExtension `json:"_lifecycleStatus,omitempty" fhir:"cardinality=0..1"`
	// in-progress | improving | worsening | no-change | achieved | sustaining | not-achieved | no-progress | not-attainable
	AchievementStatus *CodeableConcept `json:"achievementStatus,omitempty" fhir:"cardinality=0..1,summary"`
	// E.g. Treatment, dietary, behavioral, etc
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// After meeting the goal, ongoing activity is needed to sustain the goal objective
	Continuous *bool `json:"continuous,omitempty" fhir:"cardinality=0..1"`
	// Extension for Continuous
	ContinuousExt *primitives.PrimitiveExtension `json:"_continuous,omitempty" fhir:"cardinality=0..1"`
	// high-priority | medium-priority | low-priority
	Priority *CodeableConcept `json:"priority,omitempty" fhir:"cardinality=0..1,summary"`
	// Code or text describing goal
	Description CodeableConcept `json:"description" fhir:"cardinality=1..1,required,summary"`
	// Who this goal is intended for
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// When goal pursuit begins - date option
	StartDate *primitives.Date `json:"startDate,omitempty" fhir:"cardinality=0..1,summary,choice=start"`
	// Extension for StartDate
	StartDateExt *primitives.PrimitiveExtension `json:"_startDate,omitempty" fhir:"cardinality=0..1"`
	// When goal pursuit begins - CodeableConcept option
	StartCodeableConcept *CodeableConcept `json:"startCodeableConcept,omitempty" fhir:"cardinality=0..1,summary,choice=start"`
	// Target outcome for the goal
	Target []GoalTarget `json:"target,omitempty" fhir:"cardinality=0..*"`
	// When goal status took effect
	StatusDate *primitives.Date `json:"statusDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for StatusDate
	StatusDateExt *primitives.PrimitiveExtension `json:"_statusDate,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *string `json:"statusReason,omitempty" fhir:"cardinality=0..1"`
	// Extension for StatusReason
	StatusReasonExt *primitives.PrimitiveExtension `json:"_statusReason,omitempty" fhir:"cardinality=0..1"`
	// Who's responsible for creating Goal?
	Source *Reference `json:"source,omitempty" fhir:"cardinality=0..1,summary"`
	// Issues addressed by this goal
	Addresses []Reference `json:"addresses,omitempty" fhir:"cardinality=0..*"`
	// Comments about the goal
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// What result was achieved regarding the goal?
	Outcome []CodeableReference `json:"outcome,omitempty" fhir:"cardinality=0..*"`
}
