// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeGraphDefinition is the FHIR resource type name for GraphDefinition.
const ResourceTypeGraphDefinition = "GraphDefinition"

// GraphDefinitionNode represents a FHIR BackboneElement for GraphDefinition.node.
type GraphDefinitionNode struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Internal ID - target for link references
	NodeId string `json:"nodeId" fhir:"cardinality=1..1,required"`
	// Extension for NodeId
	NodeIdExt *primitives.PrimitiveExtension `json:"_nodeId,omitempty" fhir:"cardinality=0..1"`
	// Why this node is specified
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Type of resource this link refers to
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Profile for the target resource
	Profile *string `json:"profile,omitempty" fhir:"cardinality=0..1"`
	// Extension for Profile
	ProfileExt *primitives.PrimitiveExtension `json:"_profile,omitempty" fhir:"cardinality=0..1"`
}

// GraphDefinitionLinkCompartment represents a FHIR BackboneElement for GraphDefinition.link.compartment.
type GraphDefinitionLinkCompartment struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// where | requires
	Use string `json:"use" fhir:"cardinality=1..1,required"`
	// Extension for Use
	UseExt *primitives.PrimitiveExtension `json:"_use,omitempty" fhir:"cardinality=0..1"`
	// identical | matching | different | custom
	Rule string `json:"rule" fhir:"cardinality=1..1,required"`
	// Extension for Rule
	RuleExt *primitives.PrimitiveExtension `json:"_rule,omitempty" fhir:"cardinality=0..1"`
	// Patient | Encounter | RelatedPerson | Practitioner | Device | EpisodeOfCare
	Code string `json:"code" fhir:"cardinality=1..1,required"`
	// Extension for Code
	CodeExt *primitives.PrimitiveExtension `json:"_code,omitempty" fhir:"cardinality=0..1"`
	// Custom rule, as a FHIRPath expression
	Expression *string `json:"expression,omitempty" fhir:"cardinality=0..1"`
	// Extension for Expression
	ExpressionExt *primitives.PrimitiveExtension `json:"_expression,omitempty" fhir:"cardinality=0..1"`
	// Documentation for FHIRPath expression
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// GraphDefinitionLink represents a FHIR BackboneElement for GraphDefinition.link.
type GraphDefinitionLink struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this link is specified
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Minimum occurrences for this link
	Min *int `json:"min,omitempty" fhir:"cardinality=0..1"`
	// Extension for Min
	MinExt *primitives.PrimitiveExtension `json:"_min,omitempty" fhir:"cardinality=0..1"`
	// Maximum occurrences for this link
	Max *string `json:"max,omitempty" fhir:"cardinality=0..1"`
	// Extension for Max
	MaxExt *primitives.PrimitiveExtension `json:"_max,omitempty" fhir:"cardinality=0..1"`
	// Source Node for this link
	SourceId string `json:"sourceId" fhir:"cardinality=1..1,required"`
	// Extension for SourceId
	SourceIdExt *primitives.PrimitiveExtension `json:"_sourceId,omitempty" fhir:"cardinality=0..1"`
	// Path in the resource that contains the link
	Path *string `json:"path,omitempty" fhir:"cardinality=0..1"`
	// Extension for Path
	PathExt *primitives.PrimitiveExtension `json:"_path,omitempty" fhir:"cardinality=0..1"`
	// Which slice (if profiled)
	SliceName *string `json:"sliceName,omitempty" fhir:"cardinality=0..1"`
	// Extension for SliceName
	SliceNameExt *primitives.PrimitiveExtension `json:"_sliceName,omitempty" fhir:"cardinality=0..1"`
	// Target Node for this link
	TargetId string `json:"targetId" fhir:"cardinality=1..1,required"`
	// Extension for TargetId
	TargetIdExt *primitives.PrimitiveExtension `json:"_targetId,omitempty" fhir:"cardinality=0..1"`
	// Criteria for reverse lookup
	Params *string `json:"params,omitempty" fhir:"cardinality=0..1"`
	// Extension for Params
	ParamsExt *primitives.PrimitiveExtension `json:"_params,omitempty" fhir:"cardinality=0..1"`
	// Compartment Consistency Rules
	Compartment []GraphDefinitionLinkCompartment `json:"compartment,omitempty" fhir:"cardinality=0..*"`
}

// GraphDefinition represents a FHIR GraphDefinition.
type GraphDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this graph definition, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the GraphDefinition (business identifier)
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the graph definition
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this graph definition (computer friendly)
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this graph definition (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the graph definition
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for graph definition (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this graph definition is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Starting Node
	Start *string `json:"start,omitempty" fhir:"cardinality=0..1"`
	// Extension for Start
	StartExt *primitives.PrimitiveExtension `json:"_start,omitempty" fhir:"cardinality=0..1"`
	// Potential target for the link
	Node []GraphDefinitionNode `json:"node,omitempty" fhir:"cardinality=0..*"`
	// Links this graph makes rules about
	Link []GraphDefinitionLink `json:"link,omitempty" fhir:"cardinality=0..*"`
}
