// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeHealthcareService is the FHIR resource type name for HealthcareService.
const ResourceTypeHealthcareService = "HealthcareService"

// HealthcareServiceEligibility represents a FHIR BackboneElement for HealthcareService.eligibility.
type HealthcareServiceEligibility struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Coded value for the eligibility
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Describes the eligibility conditions for the service
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
}

// HealthcareService represents a FHIR HealthcareService.
type HealthcareService struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External identifiers for this item
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this HealthcareService record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// Organization that provides this service
	ProvidedBy *Reference `json:"providedBy,omitempty" fhir:"cardinality=0..1,summary"`
	// The service within which this service is offered
	OfferedIn []Reference `json:"offeredIn,omitempty" fhir:"cardinality=0..*"`
	// Broad category of service being performed or delivered
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of service that may be delivered or performed
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// Specialties handled by the HealthcareService
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// Location(s) where service may be provided
	Location []Reference `json:"location,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of service as presented to a consumer while searching
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Additional description and/or any specific issues not covered elsewhere
	Comment *string `json:"comment,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Comment
	CommentExt *primitives.PrimitiveExtension `json:"_comment,omitempty" fhir:"cardinality=0..1"`
	// Extra details about the service that can't be placed in the other fields
	ExtraDetails *string `json:"extraDetails,omitempty" fhir:"cardinality=0..1"`
	// Extension for ExtraDetails
	ExtraDetailsExt *primitives.PrimitiveExtension `json:"_extraDetails,omitempty" fhir:"cardinality=0..1"`
	// Facilitates quick identification of the service
	Photo *Attachment `json:"photo,omitempty" fhir:"cardinality=0..1,summary"`
	// Official contact details for the HealthcareService
	Contact []ExtendedContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*"`
	// Location(s) service is intended for/available to
	CoverageArea []Reference `json:"coverageArea,omitempty" fhir:"cardinality=0..*"`
	// Conditions under which service is available/offered
	ServiceProvisionCode []CodeableConcept `json:"serviceProvisionCode,omitempty" fhir:"cardinality=0..*"`
	// Specific eligibility requirements required to use the service
	Eligibility []HealthcareServiceEligibility `json:"eligibility,omitempty" fhir:"cardinality=0..*"`
	// Programs that this service is applicable to
	Program []CodeableConcept `json:"program,omitempty" fhir:"cardinality=0..*"`
	// Collection of characteristics (attributes)
	Characteristic []CodeableConcept `json:"characteristic,omitempty" fhir:"cardinality=0..*"`
	// The language that this service is offered in
	Communication []CodeableConcept `json:"communication,omitempty" fhir:"cardinality=0..*"`
	// Ways that the service accepts referrals
	ReferralMethod []CodeableConcept `json:"referralMethod,omitempty" fhir:"cardinality=0..*"`
	// If an appointment is required for access to this service
	AppointmentRequired *bool `json:"appointmentRequired,omitempty" fhir:"cardinality=0..1"`
	// Extension for AppointmentRequired
	AppointmentRequiredExt *primitives.PrimitiveExtension `json:"_appointmentRequired,omitempty" fhir:"cardinality=0..1"`
	// Times the healthcare service is available (including exceptions)
	Availability []Availability `json:"availability,omitempty" fhir:"cardinality=0..*"`
	// Technical endpoints providing access to electronic services operated for the healthcare service
	Endpoint []Reference `json:"endpoint,omitempty" fhir:"cardinality=0..*"`
}
