// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeMeasure is the FHIR resource type name for Measure.
const ResourceTypeMeasure = "Measure"

// MeasureTerm represents a FHIR BackboneElement for Measure.term.
type MeasureTerm struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// What term?
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Meaning of the term
	Definition *string `json:"definition,omitempty" fhir:"cardinality=0..1"`
	// Extension for Definition
	DefinitionExt *primitives.PrimitiveExtension `json:"_definition,omitempty" fhir:"cardinality=0..1"`
}

// MeasureGroupPopulation represents a FHIR BackboneElement for Measure.group.population.
type MeasureGroupPopulation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Unique id for population in measure
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// initial-population | numerator | numerator-exclusion | denominator | denominator-exclusion | denominator-exception | measure-population | measure-population-exclusion | measure-observation
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// The human readable description of this population criteria
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The criteria that defines this population
	Criteria *Expression `json:"criteria,omitempty" fhir:"cardinality=0..1"`
	// A group resource that defines this population
	GroupDefinition *Reference `json:"groupDefinition,omitempty" fhir:"cardinality=0..1"`
	// Which population
	InputPopulationId *string `json:"inputPopulationId,omitempty" fhir:"cardinality=0..1"`
	// Extension for InputPopulationId
	InputPopulationIdExt *primitives.PrimitiveExtension `json:"_inputPopulationId,omitempty" fhir:"cardinality=0..1"`
	// Aggregation method for a measure score (e.g. sum, average, median, minimum, maximum, count)
	AggregateMethod *CodeableConcept `json:"aggregateMethod,omitempty" fhir:"cardinality=0..1"`
}

// MeasureGroupStratifierComponent represents a FHIR BackboneElement for Measure.group.stratifier.component.
type MeasureGroupStratifierComponent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Unique id for stratifier component in measure
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// Meaning of the stratifier component
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// The human readable description of this stratifier component
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Component of how the measure should be stratified
	Criteria *Expression `json:"criteria,omitempty" fhir:"cardinality=0..1"`
	// A group resource that defines this population
	GroupDefinition *Reference `json:"groupDefinition,omitempty" fhir:"cardinality=0..1"`
}

// MeasureGroupStratifier represents a FHIR BackboneElement for Measure.group.stratifier.
type MeasureGroupStratifier struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Unique id for stratifier in measure
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// Meaning of the stratifier
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// The human readable description of this stratifier
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// How the measure should be stratified
	Criteria *Expression `json:"criteria,omitempty" fhir:"cardinality=0..1"`
	// A group resource that defines this population
	GroupDefinition *Reference `json:"groupDefinition,omitempty" fhir:"cardinality=0..1"`
	// Stratifier criteria component for the measure
	Component []MeasureGroupStratifierComponent `json:"component,omitempty" fhir:"cardinality=0..*"`
}

// MeasureGroup represents a FHIR BackboneElement for Measure.group.
type MeasureGroup struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Unique id for group in measure
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// Meaning of the group
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Summary description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// process | outcome | structure | patient-reported-outcome | composite
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// E.g. Patient, Practitioner, RelatedPerson, Organization, Location, Device - CodeableConcept option
	SubjectCodeableConcept *CodeableConcept `json:"subjectCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// E.g. Patient, Practitioner, RelatedPerson, Organization, Location, Device - Reference option
	SubjectReference *Reference `json:"subjectReference,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// Population basis
	Basis *string `json:"basis,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Basis
	BasisExt *primitives.PrimitiveExtension `json:"_basis,omitempty" fhir:"cardinality=0..1"`
	// proportion | ratio | continuous-variable | cohort
	Scoring *CodeableConcept `json:"scoring,omitempty" fhir:"cardinality=0..1,summary"`
	// What units?
	ScoringUnit *CodeableConcept `json:"scoringUnit,omitempty" fhir:"cardinality=0..1,summary"`
	// How is rate aggregation performed for this measure
	RateAggregation *string `json:"rateAggregation,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for RateAggregation
	RateAggregationExt *primitives.PrimitiveExtension `json:"_rateAggregation,omitempty" fhir:"cardinality=0..1"`
	// increase | decrease
	ImprovementNotation *CodeableConcept `json:"improvementNotation,omitempty" fhir:"cardinality=0..1,summary"`
	// Logic used by the measure group
	Library []string `json:"library,omitempty" fhir:"cardinality=0..*"`
	// Extension for Library
	LibraryExt *primitives.PrimitiveExtension `json:"_library,omitempty" fhir:"cardinality=0..1"`
	// Population criteria
	Population []MeasureGroupPopulation `json:"population,omitempty" fhir:"cardinality=0..*"`
	// Stratifier criteria for the measure
	Stratifier []MeasureGroupStratifier `json:"stratifier,omitempty" fhir:"cardinality=0..*"`
}

// MeasureSupplementalData represents a FHIR BackboneElement for Measure.supplementalData.
type MeasureSupplementalData struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Unique id for supplementalData in measure
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// Meaning of the supplemental data
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// supplemental-data | risk-adjustment-factor
	Usage []CodeableConcept `json:"usage,omitempty" fhir:"cardinality=0..*"`
	// The human readable description of this supplemental data
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Expression describing additional data to be reported
	Criteria Expression `json:"criteria" fhir:"cardinality=1..1,required"`
}

// Measure represents a FHIR Measure.
type Measure struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this measure, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the measure
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the measure
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this measure (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this measure (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Subordinate title of the measure
	Subtitle *string `json:"subtitle,omitempty" fhir:"cardinality=0..1"`
	// Extension for Subtitle
	SubtitleExt *primitives.PrimitiveExtension `json:"_subtitle,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// E.g. Patient, Practitioner, RelatedPerson, Organization, Location, Device - CodeableConcept option
	SubjectCodeableConcept *CodeableConcept `json:"subjectCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// E.g. Patient, Practitioner, RelatedPerson, Organization, Location, Device - Reference option
	SubjectReference *Reference `json:"subjectReference,omitempty" fhir:"cardinality=0..1,choice=subject"`
	// Population basis
	Basis *string `json:"basis,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Basis
	BasisExt *primitives.PrimitiveExtension `json:"_basis,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the measure
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for measure (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this measure is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Describes the clinical usage of the measure
	Usage *string `json:"usage,omitempty" fhir:"cardinality=0..1"`
	// Extension for Usage
	UsageExt *primitives.PrimitiveExtension `json:"_usage,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// When the measure was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the measure was last reviewed by the publisher
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the measure is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// The category of the measure, such as Education, Treatment, Assessment, etc
	Topic []CodeableConcept `json:"topic,omitempty" fhir:"cardinality=0..*"`
	// Who authored the content
	Author []ContactDetail `json:"author,omitempty" fhir:"cardinality=0..*"`
	// Who edited the content
	Editor []ContactDetail `json:"editor,omitempty" fhir:"cardinality=0..*"`
	// Who reviewed the content
	Reviewer []ContactDetail `json:"reviewer,omitempty" fhir:"cardinality=0..*"`
	// Who endorsed the content
	Endorser []ContactDetail `json:"endorser,omitempty" fhir:"cardinality=0..*"`
	// Additional documentation, citations, etc
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// Logic used by the measure
	Library []string `json:"library,omitempty" fhir:"cardinality=0..*"`
	// Extension for Library
	LibraryExt *primitives.PrimitiveExtension `json:"_library,omitempty" fhir:"cardinality=0..1"`
	// Disclaimer for use of the measure or its referenced content
	Disclaimer *string `json:"disclaimer,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Disclaimer
	DisclaimerExt *primitives.PrimitiveExtension `json:"_disclaimer,omitempty" fhir:"cardinality=0..1"`
	// proportion | ratio | continuous-variable | cohort
	Scoring *CodeableConcept `json:"scoring,omitempty" fhir:"cardinality=0..1,summary"`
	// What units?
	ScoringUnit *CodeableConcept `json:"scoringUnit,omitempty" fhir:"cardinality=0..1,summary"`
	// opportunity | all-or-nothing | linear | weighted
	CompositeScoring *CodeableConcept `json:"compositeScoring,omitempty" fhir:"cardinality=0..1,summary"`
	// process | outcome | structure | patient-reported-outcome | composite
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// How risk adjustment is applied for this measure
	RiskAdjustment *string `json:"riskAdjustment,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for RiskAdjustment
	RiskAdjustmentExt *primitives.PrimitiveExtension `json:"_riskAdjustment,omitempty" fhir:"cardinality=0..1"`
	// How is rate aggregation performed for this measure
	RateAggregation *string `json:"rateAggregation,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for RateAggregation
	RateAggregationExt *primitives.PrimitiveExtension `json:"_rateAggregation,omitempty" fhir:"cardinality=0..1"`
	// Detailed description of why the measure exists
	Rationale *string `json:"rationale,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Rationale
	RationaleExt *primitives.PrimitiveExtension `json:"_rationale,omitempty" fhir:"cardinality=0..1"`
	// Summary of clinical guidelines
	ClinicalRecommendationStatement *string `json:"clinicalRecommendationStatement,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ClinicalRecommendationStatement
	ClinicalRecommendationStatementExt *primitives.PrimitiveExtension `json:"_clinicalRecommendationStatement,omitempty" fhir:"cardinality=0..1"`
	// increase | decrease
	ImprovementNotation *CodeableConcept `json:"improvementNotation,omitempty" fhir:"cardinality=0..1,summary"`
	// Defined terms used in the measure documentation
	Term []MeasureTerm `json:"term,omitempty" fhir:"cardinality=0..*"`
	// Additional guidance for implementers (deprecated)
	Guidance *string `json:"guidance,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Guidance
	GuidanceExt *primitives.PrimitiveExtension `json:"_guidance,omitempty" fhir:"cardinality=0..1"`
	// Population criteria group
	Group []MeasureGroup `json:"group,omitempty" fhir:"cardinality=0..*"`
	// What other data should be reported with the measure
	SupplementalData []MeasureSupplementalData `json:"supplementalData,omitempty" fhir:"cardinality=0..*"`
}
