// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeMedicationRequest is the FHIR resource type name for MedicationRequest.
const ResourceTypeMedicationRequest = "MedicationRequest"

// MedicationRequestDispenseRequestInitialFill represents a FHIR BackboneElement for MedicationRequest.dispenseRequest.initialFill.
type MedicationRequestDispenseRequestInitialFill struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// First fill quantity
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// First fill duration
	Duration *Duration `json:"duration,omitempty" fhir:"cardinality=0..1"`
}

// MedicationRequestDispenseRequest represents a FHIR BackboneElement for MedicationRequest.dispenseRequest.
type MedicationRequestDispenseRequest struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// First fill details
	InitialFill *MedicationRequestDispenseRequestInitialFill `json:"initialFill,omitempty" fhir:"cardinality=0..1"`
	// Minimum period of time between dispenses
	DispenseInterval *Duration `json:"dispenseInterval,omitempty" fhir:"cardinality=0..1"`
	// Time period supply is authorized for
	ValidityPeriod *Period `json:"validityPeriod,omitempty" fhir:"cardinality=0..1"`
	// Number of refills authorized
	NumberOfRepeatsAllowed *uint `json:"numberOfRepeatsAllowed,omitempty" fhir:"cardinality=0..1"`
	// Extension for NumberOfRepeatsAllowed
	NumberOfRepeatsAllowedExt *primitives.PrimitiveExtension `json:"_numberOfRepeatsAllowed,omitempty" fhir:"cardinality=0..1"`
	// Amount of medication to supply per dispense
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// Number of days supply per dispense
	ExpectedSupplyDuration *Duration `json:"expectedSupplyDuration,omitempty" fhir:"cardinality=0..1"`
	// Intended performer of dispense
	Dispenser *Reference `json:"dispenser,omitempty" fhir:"cardinality=0..1"`
	// Additional information for the dispenser
	DispenserInstruction []Annotation `json:"dispenserInstruction,omitempty" fhir:"cardinality=0..*"`
	// Type of adherence packaging to use for the dispense
	DoseAdministrationAid *CodeableConcept `json:"doseAdministrationAid,omitempty" fhir:"cardinality=0..1"`
}

// MedicationRequestSubstitution represents a FHIR BackboneElement for MedicationRequest.substitution.
type MedicationRequestSubstitution struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether substitution is allowed or not - boolean option
	AllowedBoolean bool `json:"allowedBoolean" fhir:"cardinality=1..1,required,choice=allowed"`
	// Extension for AllowedBoolean
	AllowedBooleanExt *primitives.PrimitiveExtension `json:"_allowedBoolean,omitempty" fhir:"cardinality=0..1"`
	// Whether substitution is allowed or not - CodeableConcept option
	AllowedCodeableConcept CodeableConcept `json:"allowedCodeableConcept" fhir:"cardinality=1..1,required,choice=allowed"`
	// Why should (not) substitution be made
	Reason *CodeableConcept `json:"reason,omitempty" fhir:"cardinality=0..1"`
}

// MedicationRequest represents a FHIR MedicationRequest.
type MedicationRequest struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External ids for this request
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// A plan or request that is fulfilled in whole or in part by this medication request
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Reference to an order/prescription that is being replaced by this MedicationRequest
	PriorPrescription *Reference `json:"priorPrescription,omitempty" fhir:"cardinality=0..1"`
	// Composite request this is part of
	GroupIdentifier *Identifier `json:"groupIdentifier,omitempty" fhir:"cardinality=0..1,summary"`
	// active | on-hold | ended | stopped | completed | cancelled | entered-in-error | draft | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1"`
	// When the status was changed
	StatusChanged *primitives.DateTime `json:"statusChanged,omitempty" fhir:"cardinality=0..1"`
	// Extension for StatusChanged
	StatusChangedExt *primitives.PrimitiveExtension `json:"_statusChanged,omitempty" fhir:"cardinality=0..1"`
	// proposal | plan | order | original-order | reflex-order | filler-order | instance-order | option
	Intent string `json:"intent" fhir:"cardinality=1..1,required,summary"`
	// Extension for Intent
	IntentExt *primitives.PrimitiveExtension `json:"_intent,omitempty" fhir:"cardinality=0..1"`
	// Grouping or category of medication request
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*"`
	// routine | urgent | asap | stat
	Priority *string `json:"priority,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// True if patient is to stop taking or not to start taking the medication
	DoNotPerform *bool `json:"doNotPerform,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DoNotPerform
	DoNotPerformExt *primitives.PrimitiveExtension `json:"_doNotPerform,omitempty" fhir:"cardinality=0..1"`
	// Medication to be taken
	Medication CodeableReference `json:"medication" fhir:"cardinality=1..1,required,summary"`
	// Individual or group for whom the medication has been requested
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// The person or organization who provided the information about this request, if the source is someone other than the requestor
	InformationSource []Reference `json:"informationSource,omitempty" fhir:"cardinality=0..*"`
	// Encounter created as part of encounter/admission/stay
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1"`
	// Information to support fulfilling of the medication
	SupportingInformation []Reference `json:"supportingInformation,omitempty" fhir:"cardinality=0..*"`
	// When request was initially authored
	AuthoredOn *primitives.DateTime `json:"authoredOn,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AuthoredOn
	AuthoredOnExt *primitives.PrimitiveExtension `json:"_authoredOn,omitempty" fhir:"cardinality=0..1"`
	// Who/What requested the Request
	Requester *Reference `json:"requester,omitempty" fhir:"cardinality=0..1,summary"`
	// Reported rather than primary record
	Reported *bool `json:"reported,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Reported
	ReportedExt *primitives.PrimitiveExtension `json:"_reported,omitempty" fhir:"cardinality=0..1"`
	// Desired kind of performer of the medication administration
	PerformerType *CodeableConcept `json:"performerType,omitempty" fhir:"cardinality=0..1,summary"`
	// Intended performer of administration
	Performer []Reference `json:"performer,omitempty" fhir:"cardinality=0..*"`
	// Intended type of device for the administration
	Device []CodeableReference `json:"device,omitempty" fhir:"cardinality=0..*"`
	// Person who entered the request
	Recorder *Reference `json:"recorder,omitempty" fhir:"cardinality=0..1"`
	// Reason or indication for ordering or not ordering the medication
	Reason []CodeableReference `json:"reason,omitempty" fhir:"cardinality=0..*"`
	// Overall pattern of medication administration
	CourseOfTherapyType *CodeableConcept `json:"courseOfTherapyType,omitempty" fhir:"cardinality=0..1"`
	// Associated insurance coverage
	Insurance []Reference `json:"insurance,omitempty" fhir:"cardinality=0..*"`
	// Information about the prescription
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Full representation of the dosage instructions
	RenderedDosageInstruction *string `json:"renderedDosageInstruction,omitempty" fhir:"cardinality=0..1"`
	// Extension for RenderedDosageInstruction
	RenderedDosageInstructionExt *primitives.PrimitiveExtension `json:"_renderedDosageInstruction,omitempty" fhir:"cardinality=0..1"`
	// Period over which the medication is to be taken
	EffectiveDosePeriod *Period `json:"effectiveDosePeriod,omitempty" fhir:"cardinality=0..1"`
	// Specific instructions for how the medication should be taken
	DosageInstruction []Dosage `json:"dosageInstruction,omitempty" fhir:"cardinality=0..*"`
	// Medication supply authorization
	DispenseRequest *MedicationRequestDispenseRequest `json:"dispenseRequest,omitempty" fhir:"cardinality=0..1"`
	// Any restrictions on medication substitution
	Substitution *MedicationRequestSubstitution `json:"substitution,omitempty" fhir:"cardinality=0..1"`
	// A list of events of interest in the lifecycle
	EventHistory []Reference `json:"eventHistory,omitempty" fhir:"cardinality=0..*"`
}
