// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeMedicinalProductDefinition is the FHIR resource type name for MedicinalProductDefinition.
const ResourceTypeMedicinalProductDefinition = "MedicinalProductDefinition"

// MedicinalProductDefinitionContact represents a FHIR BackboneElement for MedicinalProductDefinition.contact.
type MedicinalProductDefinitionContact struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Allows the contact to be classified, for example QPPV, Pharmacovigilance Enquiry Information
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// A product specific contact, person (in a role), or an organization
	Contact Reference `json:"contact" fhir:"cardinality=1..1,required,summary"`
}

// MedicinalProductDefinitionNamePart represents a FHIR BackboneElement for MedicinalProductDefinition.name.part.
type MedicinalProductDefinitionNamePart struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// A fragment of a product name
	Part string `json:"part" fhir:"cardinality=1..1,required,summary"`
	// Extension for Part
	PartExt *primitives.PrimitiveExtension `json:"_part,omitempty" fhir:"cardinality=0..1"`
	// Identifying type for this part of the name (e.g. strength part)
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required,summary"`
}

// MedicinalProductDefinitionNameUsage represents a FHIR BackboneElement for MedicinalProductDefinition.name.usage.
type MedicinalProductDefinitionNameUsage struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Country code for where this name applies
	Country CodeableConcept `json:"country" fhir:"cardinality=1..1,required,summary"`
	// Jurisdiction code for where this name applies
	Jurisdiction *CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..1,summary"`
	// Language code for this name
	Language CodeableConcept `json:"language" fhir:"cardinality=1..1,required,summary"`
}

// MedicinalProductDefinitionName represents a FHIR BackboneElement for MedicinalProductDefinition.name.
type MedicinalProductDefinitionName struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The full product name
	ProductName string `json:"productName" fhir:"cardinality=1..1,required,summary"`
	// Extension for ProductName
	ProductNameExt *primitives.PrimitiveExtension `json:"_productName,omitempty" fhir:"cardinality=0..1"`
	// Type of product name, such as rINN, BAN, Proprietary, Non-Proprietary
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Coding words or phrases of the name
	Part []MedicinalProductDefinitionNamePart `json:"part,omitempty" fhir:"cardinality=0..*,summary"`
	// Country and jurisdiction where the name applies
	Usage []MedicinalProductDefinitionNameUsage `json:"usage,omitempty" fhir:"cardinality=0..*,summary"`
}

// MedicinalProductDefinitionCrossReference represents a FHIR BackboneElement for MedicinalProductDefinition.crossReference.
type MedicinalProductDefinitionCrossReference struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Reference to another product, e.g. for linking authorised to investigational product
	Product CodeableReference `json:"product" fhir:"cardinality=1..1,required,summary"`
	// The type of relationship, for instance branded to generic or virtual to actual product
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
}

// MedicinalProductDefinitionOperation represents a FHIR BackboneElement for MedicinalProductDefinition.operation.
type MedicinalProductDefinitionOperation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The type of manufacturing operation e.g. manufacturing itself, re-packaging
	Type *CodeableReference `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Date range of applicability
	EffectiveDate *Period `json:"effectiveDate,omitempty" fhir:"cardinality=0..1,summary"`
	// The organization responsible for the particular process, e.g. the manufacturer or importer
	Organization []Reference `json:"organization,omitempty" fhir:"cardinality=0..*,summary"`
	// Specifies whether this process is considered proprietary or confidential
	ConfidentialityIndicator *CodeableConcept `json:"confidentialityIndicator,omitempty" fhir:"cardinality=0..1,summary"`
}

// MedicinalProductDefinitionCharacteristic represents a FHIR BackboneElement for MedicinalProductDefinition.characteristic.
type MedicinalProductDefinitionCharacteristic struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// A code expressing the type of characteristic
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required,summary"`
	// A value for the characteristic - CodeableConcept option
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// A value for the characteristic - markdown option
	ValueMarkdown *string `json:"valueMarkdown,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// Extension for ValueMarkdown
	ValueMarkdownExt *primitives.PrimitiveExtension `json:"_valueMarkdown,omitempty" fhir:"cardinality=0..1"`
	// A value for the characteristic - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// A value for the characteristic - integer option
	ValueInteger *int `json:"valueInteger,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// A value for the characteristic - date option
	ValueDate *primitives.Date `json:"valueDate,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// A value for the characteristic - boolean option
	ValueBoolean *bool `json:"valueBoolean,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// A value for the characteristic - Attachment option
	ValueAttachment *Attachment `json:"valueAttachment,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
}

// MedicinalProductDefinition represents a FHIR MedicinalProductDefinition.
type MedicinalProductDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for this product. Could be an MPID
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Regulatory type, e.g. Investigational or Authorized
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// If this medicine applies to human or veterinary uses
	Domain *CodeableConcept `json:"domain,omitempty" fhir:"cardinality=0..1,summary"`
	// A business identifier relating to a specific version of the product
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// The status within the lifecycle of this product record
	Status *CodeableConcept `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// The date at which the given status became applicable
	StatusDate *primitives.DateTime `json:"statusDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for StatusDate
	StatusDateExt *primitives.PrimitiveExtension `json:"_statusDate,omitempty" fhir:"cardinality=0..1"`
	// General description of this product
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The dose form for a single part product, or combined form of a multiple part product
	CombinedPharmaceuticalDoseForm *CodeableConcept `json:"combinedPharmaceuticalDoseForm,omitempty" fhir:"cardinality=0..1,summary"`
	// The path by which the product is taken into or makes contact with the body
	Route []CodeableConcept `json:"route,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of indication(s) for this product, used when structured indications are not required
	Indication *string `json:"indication,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Indication
	IndicationExt *primitives.PrimitiveExtension `json:"_indication,omitempty" fhir:"cardinality=0..1"`
	// The legal status of supply of the medicinal product as classified by the regulator
	LegalStatusOfSupply *CodeableConcept `json:"legalStatusOfSupply,omitempty" fhir:"cardinality=0..1,summary"`
	// Whether the Medicinal Product is subject to additional monitoring for regulatory reasons
	AdditionalMonitoringIndicator *CodeableConcept `json:"additionalMonitoringIndicator,omitempty" fhir:"cardinality=0..1,summary"`
	// Whether the Medicinal Product is subject to special measures for regulatory reasons
	SpecialMeasures []CodeableConcept `json:"specialMeasures,omitempty" fhir:"cardinality=0..*,summary"`
	// If authorised for use in children
	PediatricUseIndicator *CodeableConcept `json:"pediatricUseIndicator,omitempty" fhir:"cardinality=0..1,summary"`
	// Allows the product to be classified by various systems
	Classification []CodeableConcept `json:"classification,omitempty" fhir:"cardinality=0..*,summary"`
	// Marketing status of the medicinal product, in contrast to marketing authorization
	MarketingStatus []MarketingStatus `json:"marketingStatus,omitempty" fhir:"cardinality=0..*,summary"`
	// Package type for the product
	PackagedMedicinalProduct []CodeableConcept `json:"packagedMedicinalProduct,omitempty" fhir:"cardinality=0..*,summary"`
	// Types of medicinal manufactured items and/or devices that this product consists of, such as tablets, capsule, or syringes
	ComprisedOf []Reference `json:"comprisedOf,omitempty" fhir:"cardinality=0..*,summary"`
	// The ingredients of this medicinal product - when not detailed in other resources
	Ingredient []CodeableConcept `json:"ingredient,omitempty" fhir:"cardinality=0..*,summary"`
	// Any component of the drug product which is not the chemical entity defined as the drug substance, or an excipient in the drug product
	Impurity []CodeableReference `json:"impurity,omitempty" fhir:"cardinality=0..*,summary"`
	// Additional documentation about the medicinal product
	AttachedDocument []Reference `json:"attachedDocument,omitempty" fhir:"cardinality=0..*,summary"`
	// A master file for the medicinal product (e.g. Pharmacovigilance System Master File)
	MasterFile []Reference `json:"masterFile,omitempty" fhir:"cardinality=0..*,summary"`
	// A product specific contact, person (in a role), or an organization
	Contact []MedicinalProductDefinitionContact `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Clinical trials or studies that this product is involved in
	ClinicalTrial []Reference `json:"clinicalTrial,omitempty" fhir:"cardinality=0..*,summary"`
	// A code that this product is known by, within some formal terminology
	Code []Coding `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// The product's name, including full name and possibly coded parts
	Name []MedicinalProductDefinitionName `json:"name,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Reference to another product, e.g. for linking authorised to investigational product
	CrossReference []MedicinalProductDefinitionCrossReference `json:"crossReference,omitempty" fhir:"cardinality=0..*,summary"`
	// A manufacturing or administrative process for the medicinal product
	Operation []MedicinalProductDefinitionOperation `json:"operation,omitempty" fhir:"cardinality=0..*,summary"`
	// Key product features such as "sugar free", "modified release"
	Characteristic []MedicinalProductDefinitionCharacteristic `json:"characteristic,omitempty" fhir:"cardinality=0..*,summary"`
}
