// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeMedication is the FHIR resource type name for Medication.
const ResourceTypeMedication = "Medication"

// MedicationIngredient represents a FHIR BackboneElement for Medication.ingredient.
type MedicationIngredient struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The ingredient (substance or medication) that the ingredient.strength relates to
	Item CodeableReference `json:"item" fhir:"cardinality=1..1,required"`
	// Active ingredient indicator
	IsActive *bool `json:"isActive,omitempty" fhir:"cardinality=0..1"`
	// Extension for IsActive
	IsActiveExt *primitives.PrimitiveExtension `json:"_isActive,omitempty" fhir:"cardinality=0..1"`
	// Quantity of ingredient present - Ratio option
	StrengthRatio *Ratio `json:"strengthRatio,omitempty" fhir:"cardinality=0..1,choice=strength"`
	// Quantity of ingredient present - CodeableConcept option
	StrengthCodeableConcept *CodeableConcept `json:"strengthCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=strength"`
	// Quantity of ingredient present - Quantity option
	StrengthQuantity *Quantity `json:"strengthQuantity,omitempty" fhir:"cardinality=0..1,choice=strength"`
}

// MedicationBatch represents a FHIR BackboneElement for Medication.batch.
type MedicationBatch struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifier assigned to batch
	LotNumber *string `json:"lotNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for LotNumber
	LotNumberExt *primitives.PrimitiveExtension `json:"_lotNumber,omitempty" fhir:"cardinality=0..1"`
	// When batch will expire
	ExpirationDate *primitives.DateTime `json:"expirationDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ExpirationDate
	ExpirationDateExt *primitives.PrimitiveExtension `json:"_expirationDate,omitempty" fhir:"cardinality=0..1"`
}

// Medication represents a FHIR Medication.
type Medication struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for this medication
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Codes that identify this medication
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// active | inactive | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Organization that has authorization to market medication
	MarketingAuthorizationHolder *Reference `json:"marketingAuthorizationHolder,omitempty" fhir:"cardinality=0..1,summary"`
	// powder | tablets | capsule +
	DoseForm *CodeableConcept `json:"doseForm,omitempty" fhir:"cardinality=0..1"`
	// When the specified product code does not infer a package size, this is the specific amount of drug in the product
	TotalVolume *Quantity `json:"totalVolume,omitempty" fhir:"cardinality=0..1,summary"`
	// Active or inactive ingredient
	Ingredient []MedicationIngredient `json:"ingredient,omitempty" fhir:"cardinality=0..*"`
	// Details about packaged medications
	Batch *MedicationBatch `json:"batch,omitempty" fhir:"cardinality=0..1"`
	// Knowledge about this medication
	Definition *Reference `json:"definition,omitempty" fhir:"cardinality=0..1"`
}
