// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// MonetaryComponent represents a FHIR MonetaryComponent.
type MonetaryComponent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// base | surcharge | deduction | discount | tax | informational
	Type string `json:"type" fhir:"cardinality=1..1,required,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Codes may be used to differentiate between kinds of taxes, surcharges, discounts etc.
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Factor used for calculating this component
	Factor *float64 `json:"factor,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Factor
	FactorExt *primitives.PrimitiveExtension `json:"_factor,omitempty" fhir:"cardinality=0..1"`
	// Explicit value amount to be used
	Amount *Money `json:"amount,omitempty" fhir:"cardinality=0..1,summary"`
}
