// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeNutritionProduct is the FHIR resource type name for NutritionProduct.
const ResourceTypeNutritionProduct = "NutritionProduct"

// NutritionProductNutrient represents a FHIR BackboneElement for NutritionProduct.nutrient.
type NutritionProductNutrient struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The (relevant) nutrients in the product
	Item *CodeableReference `json:"item,omitempty" fhir:"cardinality=0..1"`
	// The amount of nutrient expressed in one or more units: X per pack / per serving / per dose
	Amount []Ratio `json:"amount,omitempty" fhir:"cardinality=0..*"`
}

// NutritionProductIngredient represents a FHIR BackboneElement for NutritionProduct.ingredient.
type NutritionProductIngredient struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The ingredient contained in the product
	Item CodeableReference `json:"item" fhir:"cardinality=1..1,required,summary"`
	// The amount of ingredient that is in the product
	Amount []Ratio `json:"amount,omitempty" fhir:"cardinality=0..*,summary"`
}

// NutritionProductCharacteristic represents a FHIR BackboneElement for NutritionProduct.characteristic.
type NutritionProductCharacteristic struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Code specifying the type of characteristic
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required"`
	// The value of the characteristic - CodeableConcept option
	ValueCodeableConcept CodeableConcept `json:"valueCodeableConcept" fhir:"cardinality=1..1,required,choice=value"`
	// The value of the characteristic - string option
	ValueString string `json:"valueString" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// The value of the characteristic - Quantity option
	ValueQuantity Quantity `json:"valueQuantity" fhir:"cardinality=1..1,required,choice=value"`
	// The value of the characteristic - base64Binary option
	ValueBase64Binary string `json:"valueBase64Binary" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBase64Binary
	ValueBase64BinaryExt *primitives.PrimitiveExtension `json:"_valueBase64Binary,omitempty" fhir:"cardinality=0..1"`
	// The value of the characteristic - Attachment option
	ValueAttachment Attachment `json:"valueAttachment" fhir:"cardinality=1..1,required,choice=value"`
	// The value of the characteristic - boolean option
	ValueBoolean bool `json:"valueBoolean" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
}

// NutritionProductInstance represents a FHIR BackboneElement for NutritionProduct.instance.
type NutritionProductInstance struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The amount of items or instances
	Quantity *Quantity `json:"quantity,omitempty" fhir:"cardinality=0..1"`
	// The identifier for the physical instance, typically a serial number or manufacturer number
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// The name for the specific product
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// The identification of the batch or lot of the product
	LotNumber *string `json:"lotNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for LotNumber
	LotNumberExt *primitives.PrimitiveExtension `json:"_lotNumber,omitempty" fhir:"cardinality=0..1"`
	// The expiry date or date and time for the product
	Expiry *primitives.DateTime `json:"expiry,omitempty" fhir:"cardinality=0..1"`
	// Extension for Expiry
	ExpiryExt *primitives.PrimitiveExtension `json:"_expiry,omitempty" fhir:"cardinality=0..1"`
	// The date until which the product is expected to be good for consumption
	UseBy *primitives.DateTime `json:"useBy,omitempty" fhir:"cardinality=0..1"`
	// Extension for UseBy
	UseByExt *primitives.PrimitiveExtension `json:"_useBy,omitempty" fhir:"cardinality=0..1"`
	// An identifier that supports traceability to the event during which material in this product from one or more biological entities was obtained or pooled
	BiologicalSourceEvent *Identifier `json:"biologicalSourceEvent,omitempty" fhir:"cardinality=0..1"`
}

// NutritionProduct represents a FHIR NutritionProduct.
type NutritionProduct struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// A code that can identify the detailed nutrients and ingredients in a specific food product
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// active | inactive | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Broad product groups or categories used to classify the product, such as Legume and Legume Products, Beverages, or Beef Products
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Manufacturer, representative or officially responsible for the product
	Manufacturer []Reference `json:"manufacturer,omitempty" fhir:"cardinality=0..*,summary"`
	// The product's nutritional information expressed by the nutrients
	Nutrient []NutritionProductNutrient `json:"nutrient,omitempty" fhir:"cardinality=0..*,summary"`
	// Ingredients contained in this product
	Ingredient []NutritionProductIngredient `json:"ingredient,omitempty" fhir:"cardinality=0..*"`
	// Known or suspected allergens that are a part of this product
	KnownAllergen []CodeableReference `json:"knownAllergen,omitempty" fhir:"cardinality=0..*"`
	// Specifies descriptive properties of the nutrition product
	Characteristic []NutritionProductCharacteristic `json:"characteristic,omitempty" fhir:"cardinality=0..*"`
	// One or several physical instances or occurrences of the nutrition product
	Instance []NutritionProductInstance `json:"instance,omitempty" fhir:"cardinality=0..*"`
	// Comments made about the product
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
}
