// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeOrganizationAffiliation is the FHIR resource type name for OrganizationAffiliation.
const ResourceTypeOrganizationAffiliation = "OrganizationAffiliation"

// OrganizationAffiliation represents a FHIR OrganizationAffiliation.
type OrganizationAffiliation struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business identifiers that are specific to this role
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this organization affiliation record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// The period during which the participatingOrganization is affiliated with the primary organization
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Organization where the role is available
	Organization *Reference `json:"organization,omitempty" fhir:"cardinality=0..1,summary"`
	// Organization that provides/performs the role (e.g. providing services or is a member of)
	ParticipatingOrganization *Reference `json:"participatingOrganization,omitempty" fhir:"cardinality=0..1,summary"`
	// The network in which the participatingOrganization provides the role's services (if defined) at the indicated locations (if defined)
	Network []Reference `json:"network,omitempty" fhir:"cardinality=0..*,summary"`
	// Definition of the role the participatingOrganization plays
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// Specific specialty of the participatingOrganization in the context of the role
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// The location(s) at which the role occurs
	Location []Reference `json:"location,omitempty" fhir:"cardinality=0..*,summary"`
	// Healthcare services provided through the role
	HealthcareService []Reference `json:"healthcareService,omitempty" fhir:"cardinality=0..*"`
	// Official contact details at the participatingOrganization relevant to this Affiliation
	Contact []ExtendedContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*"`
	// Technical endpoints providing access to services operated for this role
	Endpoint []Reference `json:"endpoint,omitempty" fhir:"cardinality=0..*"`
}
