// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypePackagedProductDefinition is the FHIR resource type name for PackagedProductDefinition.
const ResourceTypePackagedProductDefinition = "PackagedProductDefinition"

// PackagedProductDefinitionLegalStatusOfSupply represents a FHIR BackboneElement for PackagedProductDefinition.legalStatusOfSupply.
type PackagedProductDefinitionLegalStatusOfSupply struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The actual status of supply. In what situation this package type may be supplied for use
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// The place where the legal status of supply applies
	Jurisdiction *CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..1,summary"`
}

// PackagedProductDefinitionPackagingProperty represents a FHIR BackboneElement for PackagedProductDefinition.packaging.property.
type PackagedProductDefinitionPackagingProperty struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// A code expressing the type of characteristic
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required,summary"`
	// A value for the characteristic - CodeableConcept option
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// A value for the characteristic - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// A value for the characteristic - date option
	ValueDate *primitives.Date `json:"valueDate,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// A value for the characteristic - boolean option
	ValueBoolean *bool `json:"valueBoolean,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// A value for the characteristic - Attachment option
	ValueAttachment *Attachment `json:"valueAttachment,omitempty" fhir:"cardinality=0..1,summary,choice=value"`
}

// PackagedProductDefinitionPackagingContainedItem represents a FHIR BackboneElement for PackagedProductDefinition.packaging.containedItem.
type PackagedProductDefinitionPackagingContainedItem struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The actual item(s) of medication, as manufactured, or a device, or other medically related item (food, biologicals, raw materials, medical fluids, gases etc.), as contained in the package
	Item CodeableReference `json:"item" fhir:"cardinality=1..1,required,summary"`
	// The number of this type of item within this packaging or for continuous items such as liquids it is the quantity (for example 25ml). See also PackagedProductDefinition.containedItemQuantity (especially the long definition)
	Amount *Quantity `json:"amount,omitempty" fhir:"cardinality=0..1,summary"`
}

// PackagedProductDefinitionPackagingPackaging represents a FHIR BackboneElement for PackagedProductDefinition.packaging.packaging.
type PackagedProductDefinitionPackagingPackaging struct {
}

// PackagedProductDefinitionPackaging represents a FHIR BackboneElement for PackagedProductDefinition.packaging.
type PackagedProductDefinitionPackaging struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// An identifier that is specific to this particular part of the packaging. Including possibly a Data Carrier Identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// The physical type of the container of the items
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Is this a part of the packaging (e.g. a cap or bottle stopper), rather than the packaging itself (e.g. a bottle or vial)
	ComponentPart *bool `json:"componentPart,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ComponentPart
	ComponentPartExt *primitives.PrimitiveExtension `json:"_componentPart,omitempty" fhir:"cardinality=0..1"`
	// The quantity of this level of packaging in the package that contains it (with the outermost level being 1)
	Quantity *int `json:"quantity,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Quantity
	QuantityExt *primitives.PrimitiveExtension `json:"_quantity,omitempty" fhir:"cardinality=0..1"`
	// Material type of the package item
	Material []CodeableConcept `json:"material,omitempty" fhir:"cardinality=0..*,summary"`
	// A possible alternate material for this part of the packaging, that is allowed to be used instead of the usual material
	AlternateMaterial []CodeableConcept `json:"alternateMaterial,omitempty" fhir:"cardinality=0..*,summary"`
	// Shelf Life and storage information
	ShelfLifeStorage []ProductShelfLife `json:"shelfLifeStorage,omitempty" fhir:"cardinality=0..*,summary"`
	// Manufacturer of this packaging item (multiple means these are all potential manufacturers)
	Manufacturer []Reference `json:"manufacturer,omitempty" fhir:"cardinality=0..*,summary"`
	// General characteristics of this item
	Property []PackagedProductDefinitionPackagingProperty `json:"property,omitempty" fhir:"cardinality=0..*,summary"`
	// The item(s) within the packaging
	ContainedItem []PackagedProductDefinitionPackagingContainedItem `json:"containedItem,omitempty" fhir:"cardinality=0..*,summary"`
	// Allows containers (and parts of containers) within containers, still as a part of single packaged product
	Packaging []PackagedProductDefinitionPackagingPackaging `json:"packaging,omitempty" fhir:"cardinality=0..*,summary"`
}

// PackagedProductDefinitionCharacteristic represents a FHIR BackboneElement for PackagedProductDefinition.characteristic.
type PackagedProductDefinitionCharacteristic struct {
}

// PackagedProductDefinition represents a FHIR PackagedProductDefinition.
type PackagedProductDefinition struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// A unique identifier for this package as whole - not for the content of the package
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// A name for this package. Typically as listed in a drug formulary, catalogue, inventory etc
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// A high level category e.g. medicinal product, raw material, shipping container etc
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// The product that this is a pack for
	PackageFor []Reference `json:"packageFor,omitempty" fhir:"cardinality=0..*,summary"`
	// The status within the lifecycle of this item. High level - not intended to duplicate details elsewhere e.g. legal status, or authorization/marketing status
	Status *CodeableConcept `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// The date at which the given status became applicable
	StatusDate *primitives.DateTime `json:"statusDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for StatusDate
	StatusDateExt *primitives.PrimitiveExtension `json:"_statusDate,omitempty" fhir:"cardinality=0..1"`
	// A total of the complete count of contained items of a particular type/form, independent of sub-packaging or organization. This can be considered as the pack size. See also packaging.containedItem.amount (especially the long definition)
	ContainedItemQuantity []Quantity `json:"containedItemQuantity,omitempty" fhir:"cardinality=0..*,summary"`
	// Textual description. Note that this is not the name of the package or product
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The legal status of supply of the packaged item as classified by the regulator
	LegalStatusOfSupply []PackagedProductDefinitionLegalStatusOfSupply `json:"legalStatusOfSupply,omitempty" fhir:"cardinality=0..*,summary"`
	// Allows specifying that an item is on the market for sale, or that it is not available, and the dates and locations associated
	MarketingStatus []MarketingStatus `json:"marketingStatus,omitempty" fhir:"cardinality=0..*,summary"`
	// Identifies if the drug product is supplied with another item such as a diluent or adjuvant
	CopackagedIndicator *bool `json:"copackagedIndicator,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for CopackagedIndicator
	CopackagedIndicatorExt *primitives.PrimitiveExtension `json:"_copackagedIndicator,omitempty" fhir:"cardinality=0..1"`
	// Manufacturer of this package type (multiple means these are all possible manufacturers)
	Manufacturer []Reference `json:"manufacturer,omitempty" fhir:"cardinality=0..*,summary"`
	// Additional information or supporting documentation about the packaged product
	AttachedDocument []Reference `json:"attachedDocument,omitempty" fhir:"cardinality=0..*,summary"`
	// A packaging item, as a container for medically related items, possibly with other packaging items within, or a packaging component, such as bottle cap
	Packaging *PackagedProductDefinitionPackaging `json:"packaging,omitempty" fhir:"cardinality=0..1,summary"`
	// Allows the key features to be recorded, such as "hospital pack", "nurse prescribable"
	Characteristic []PackagedProductDefinitionCharacteristic `json:"characteristic,omitempty" fhir:"cardinality=0..*,summary"`
}
