// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypePractitioner is the FHIR resource type name for Practitioner.
const ResourceTypePractitioner = "Practitioner"

// PractitionerQualification represents a FHIR BackboneElement for Practitioner.qualification.
type PractitionerQualification struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// An identifier for this qualification for the practitioner
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// Coded representation of the qualification
	Code CodeableConcept `json:"code" fhir:"cardinality=1..1,required"`
	// Period during which the qualification is valid
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
	// Organization that regulates and issues the qualification
	Issuer *Reference `json:"issuer,omitempty" fhir:"cardinality=0..1"`
}

// PractitionerCommunication represents a FHIR BackboneElement for Practitioner.communication.
type PractitionerCommunication struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The language code used to communicate with the practitioner
	Language CodeableConcept `json:"language" fhir:"cardinality=1..1,required"`
	// Language preference indicator
	Preferred *bool `json:"preferred,omitempty" fhir:"cardinality=0..1"`
	// Extension for Preferred
	PreferredExt *primitives.PrimitiveExtension `json:"_preferred,omitempty" fhir:"cardinality=0..1"`
}

// Practitioner represents a FHIR Practitioner.
type Practitioner struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// An identifier for the person as this agent
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this practitioner's record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// The name(s) associated with the practitioner
	Name []HumanName `json:"name,omitempty" fhir:"cardinality=0..*,summary"`
	// A contact detail for the practitioner (that apply to all roles)
	Telecom []ContactPoint `json:"telecom,omitempty" fhir:"cardinality=0..*,summary"`
	// male | female | other | unknown
	Gender *string `json:"gender,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Gender
	GenderExt *primitives.PrimitiveExtension `json:"_gender,omitempty" fhir:"cardinality=0..1"`
	// The date  on which the practitioner was born
	BirthDate *primitives.Date `json:"birthDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for BirthDate
	BirthDateExt *primitives.PrimitiveExtension `json:"_birthDate,omitempty" fhir:"cardinality=0..1"`
	// Indicates if the practitioner is deceased or not - boolean option
	DeceasedBoolean *bool `json:"deceasedBoolean,omitempty" fhir:"cardinality=0..1,summary,choice=deceased"`
	// Extension for DeceasedBoolean
	DeceasedBooleanExt *primitives.PrimitiveExtension `json:"_deceasedBoolean,omitempty" fhir:"cardinality=0..1"`
	// Indicates if the practitioner is deceased or not - dateTime option
	DeceasedDateTime *primitives.DateTime `json:"deceasedDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=deceased"`
	// Extension for DeceasedDateTime
	DeceasedDateTimeExt *primitives.PrimitiveExtension `json:"_deceasedDateTime,omitempty" fhir:"cardinality=0..1"`
	// Address(es) of the practitioner that are not role specific (typically home address)
	Address []Address `json:"address,omitempty" fhir:"cardinality=0..*,summary"`
	// Image of the person
	Photo []Attachment `json:"photo,omitempty" fhir:"cardinality=0..*"`
	// Qualifications, certifications, accreditations, licenses, training, etc. pertaining to the provision of care
	Qualification []PractitionerQualification `json:"qualification,omitempty" fhir:"cardinality=0..*"`
	// A language which may be used to communicate with the practitioner
	Communication []PractitionerCommunication `json:"communication,omitempty" fhir:"cardinality=0..*"`
}
