// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypePractitionerRole is the FHIR resource type name for PractitionerRole.
const ResourceTypePractitionerRole = "PractitionerRole"

// PractitionerRole represents a FHIR PractitionerRole.
type PractitionerRole struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Identifiers for a role/location
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether this practitioner role record is in active use
	Active *bool `json:"active,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Active
	ActiveExt *primitives.PrimitiveExtension `json:"_active,omitempty" fhir:"cardinality=0..1"`
	// The period during which the practitioner is authorized to perform in these role(s)
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Practitioner that provides services for the organization
	Practitioner *Reference `json:"practitioner,omitempty" fhir:"cardinality=0..1,summary"`
	// Organization where the roles are available
	Organization *Reference `json:"organization,omitempty" fhir:"cardinality=0..1,summary"`
	// Roles which this practitioner may perform
	Code []CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// Specific specialty of the practitioner
	Specialty []CodeableConcept `json:"specialty,omitempty" fhir:"cardinality=0..*,summary"`
	// Location(s) where the practitioner provides care
	Location []Reference `json:"location,omitempty" fhir:"cardinality=0..*,summary"`
	// Healthcare services provided for this role's Organization/Location(s)
	HealthcareService []Reference `json:"healthcareService,omitempty" fhir:"cardinality=0..*"`
	// Official contact details relating to this PractitionerRole
	Contact []ExtendedContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*"`
	// Collection of characteristics (attributes)
	Characteristic []CodeableConcept `json:"characteristic,omitempty" fhir:"cardinality=0..*"`
	// A language the practitioner (in this role) can use in patient communication
	Communication []CodeableConcept `json:"communication,omitempty" fhir:"cardinality=0..*"`
	// Times the Practitioner is available at this location and/or healthcare service (including exceptions)
	Availability []Availability `json:"availability,omitempty" fhir:"cardinality=0..*"`
	// Endpoints for interacting with the practitioner in this role
	Endpoint []Reference `json:"endpoint,omitempty" fhir:"cardinality=0..*"`
}
