// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeProcedure is the FHIR resource type name for Procedure.
const ResourceTypeProcedure = "Procedure"

// ProcedurePerformer represents a FHIR BackboneElement for Procedure.performer.
type ProcedurePerformer struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type of performance
	Function *CodeableConcept `json:"function,omitempty" fhir:"cardinality=0..1,summary"`
	// Who performed the procedure
	Actor Reference `json:"actor" fhir:"cardinality=1..1,required,summary"`
	// Organization the device or practitioner was acting for
	OnBehalfOf *Reference `json:"onBehalfOf,omitempty" fhir:"cardinality=0..1"`
	// When the performer performed the procedure
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
}

// ProcedureFocalDevice represents a FHIR BackboneElement for Procedure.focalDevice.
type ProcedureFocalDevice struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Kind of change to device
	Action *CodeableConcept `json:"action,omitempty" fhir:"cardinality=0..1"`
	// Device that was changed
	Manipulated Reference `json:"manipulated" fhir:"cardinality=1..1,required"`
}

// Procedure represents a FHIR Procedure.
type Procedure struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External Identifiers for this procedure
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Instantiates FHIR protocol or definition
	InstantiatesCanonical []string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Instantiates external protocol or definition
	InstantiatesUri []string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// A request for this procedure
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1,summary"`
	// Classification of the procedure
	Category []CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..*,summary"`
	// Identification of the procedure
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Individual or entity the procedure was performed on
	Subject Reference `json:"subject" fhir:"cardinality=1..1,required,summary"`
	// Who is the target of the procedure when it is not the subject of record only
	Focus *Reference `json:"focus,omitempty" fhir:"cardinality=0..1,summary"`
	// The Encounter during which this Procedure was created
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// When the procedure occurred or is occurring - dateTime option
	OccurrenceDateTime *primitives.DateTime `json:"occurrenceDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Extension for OccurrenceDateTime
	OccurrenceDateTimeExt *primitives.PrimitiveExtension `json:"_occurrenceDateTime,omitempty" fhir:"cardinality=0..1"`
	// When the procedure occurred or is occurring - Period option
	OccurrencePeriod *Period `json:"occurrencePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When the procedure occurred or is occurring - string option
	OccurrenceString *string `json:"occurrenceString,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Extension for OccurrenceString
	OccurrenceStringExt *primitives.PrimitiveExtension `json:"_occurrenceString,omitempty" fhir:"cardinality=0..1"`
	// When the procedure occurred or is occurring - Age option
	OccurrenceAge *Age `json:"occurrenceAge,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When the procedure occurred or is occurring - Range option
	OccurrenceRange *Range `json:"occurrenceRange,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When the procedure occurred or is occurring - Timing option
	OccurrenceTiming *Timing `json:"occurrenceTiming,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When the procedure was first captured in the subject's record
	Recorded *primitives.DateTime `json:"recorded,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Recorded
	RecordedExt *primitives.PrimitiveExtension `json:"_recorded,omitempty" fhir:"cardinality=0..1"`
	// Who recorded the procedure
	Recorder *Reference `json:"recorder,omitempty" fhir:"cardinality=0..1,summary"`
	// Reported rather than primary record - boolean option
	ReportedBoolean *bool `json:"reportedBoolean,omitempty" fhir:"cardinality=0..1,summary,choice=reported"`
	// Extension for ReportedBoolean
	ReportedBooleanExt *primitives.PrimitiveExtension `json:"_reportedBoolean,omitempty" fhir:"cardinality=0..1"`
	// Reported rather than primary record - Reference option
	ReportedReference *Reference `json:"reportedReference,omitempty" fhir:"cardinality=0..1,summary,choice=reported"`
	// Who performed the procedure and what they did
	Performer []ProcedurePerformer `json:"performer,omitempty" fhir:"cardinality=0..*,summary"`
	// Where the procedure happened
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1,summary"`
	// The justification that the procedure was performed
	Reason []CodeableReference `json:"reason,omitempty" fhir:"cardinality=0..*,summary"`
	// Target body sites
	BodySite []CodeableConcept `json:"bodySite,omitempty" fhir:"cardinality=0..*,summary"`
	// The result of procedure
	Outcome *CodeableConcept `json:"outcome,omitempty" fhir:"cardinality=0..1,summary"`
	// Any report resulting from the procedure
	Report []Reference `json:"report,omitempty" fhir:"cardinality=0..*"`
	// Complication following the procedure
	Complication []CodeableReference `json:"complication,omitempty" fhir:"cardinality=0..*"`
	// Instructions for follow up
	FollowUp []CodeableConcept `json:"followUp,omitempty" fhir:"cardinality=0..*"`
	// Additional information about the procedure
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Manipulated, implanted, or removed device
	FocalDevice []ProcedureFocalDevice `json:"focalDevice,omitempty" fhir:"cardinality=0..*"`
	// Items used during procedure
	Used []CodeableReference `json:"used,omitempty" fhir:"cardinality=0..*"`
	// Extra information relevant to the procedure
	SupportingInfo []Reference `json:"supportingInfo,omitempty" fhir:"cardinality=0..*"`
}
