// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeQuestionnaire is the FHIR resource type name for Questionnaire.
const ResourceTypeQuestionnaire = "Questionnaire"

// QuestionnaireItemEnableWhen represents a FHIR BackboneElement for Questionnaire.item.enableWhen.
type QuestionnaireItemEnableWhen struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The linkId of question that determines whether item is enabled/disabled
	Question string `json:"question" fhir:"cardinality=1..1,required"`
	// Extension for Question
	QuestionExt *primitives.PrimitiveExtension `json:"_question,omitempty" fhir:"cardinality=0..1"`
	// exists | = | != | > | < | >= | <=
	Operator string `json:"operator" fhir:"cardinality=1..1,required"`
	// Extension for Operator
	OperatorExt *primitives.PrimitiveExtension `json:"_operator,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - boolean option
	AnswerBoolean bool `json:"answerBoolean" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerBoolean
	AnswerBooleanExt *primitives.PrimitiveExtension `json:"_answerBoolean,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - decimal option
	AnswerDecimal float64 `json:"answerDecimal" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerDecimal
	AnswerDecimalExt *primitives.PrimitiveExtension `json:"_answerDecimal,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - integer option
	AnswerInteger int `json:"answerInteger" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerInteger
	AnswerIntegerExt *primitives.PrimitiveExtension `json:"_answerInteger,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - date option
	AnswerDate primitives.Date `json:"answerDate" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerDate
	AnswerDateExt *primitives.PrimitiveExtension `json:"_answerDate,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - dateTime option
	AnswerDateTime primitives.DateTime `json:"answerDateTime" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerDateTime
	AnswerDateTimeExt *primitives.PrimitiveExtension `json:"_answerDateTime,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - time option
	AnswerTime primitives.Time `json:"answerTime" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerTime
	AnswerTimeExt *primitives.PrimitiveExtension `json:"_answerTime,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - string option
	AnswerString string `json:"answerString" fhir:"cardinality=1..1,required,choice=answer"`
	// Extension for AnswerString
	AnswerStringExt *primitives.PrimitiveExtension `json:"_answerString,omitempty" fhir:"cardinality=0..1"`
	// Value for question comparison based on operator - Coding option
	AnswerCoding Coding `json:"answerCoding" fhir:"cardinality=1..1,required,choice=answer"`
	// Value for question comparison based on operator - Quantity option
	AnswerQuantity Quantity `json:"answerQuantity" fhir:"cardinality=1..1,required,choice=answer"`
	// Value for question comparison based on operator - Reference option
	AnswerReference Reference `json:"answerReference" fhir:"cardinality=1..1,required,choice=answer"`
}

// QuestionnaireItemAnswerOption represents a FHIR BackboneElement for Questionnaire.item.answerOption.
type QuestionnaireItemAnswerOption struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Answer value - integer option
	ValueInteger int `json:"valueInteger" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Answer value - date option
	ValueDate primitives.Date `json:"valueDate" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// Answer value - time option
	ValueTime primitives.Time `json:"valueTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueTime
	ValueTimeExt *primitives.PrimitiveExtension `json:"_valueTime,omitempty" fhir:"cardinality=0..1"`
	// Answer value - string option
	ValueString string `json:"valueString" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Answer value - Coding option
	ValueCoding Coding `json:"valueCoding" fhir:"cardinality=1..1,required,choice=value"`
	// Answer value - Reference option
	ValueReference Reference `json:"valueReference" fhir:"cardinality=1..1,required,choice=value"`
	// Whether option is selected by default
	InitialSelected *bool `json:"initialSelected,omitempty" fhir:"cardinality=0..1"`
	// Extension for InitialSelected
	InitialSelectedExt *primitives.PrimitiveExtension `json:"_initialSelected,omitempty" fhir:"cardinality=0..1"`
}

// QuestionnaireItemInitial represents a FHIR BackboneElement for Questionnaire.item.initial.
type QuestionnaireItemInitial struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Actual value for initializing the question - boolean option
	ValueBoolean bool `json:"valueBoolean" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - decimal option
	ValueDecimal float64 `json:"valueDecimal" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDecimal
	ValueDecimalExt *primitives.PrimitiveExtension `json:"_valueDecimal,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - integer option
	ValueInteger int `json:"valueInteger" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - date option
	ValueDate primitives.Date `json:"valueDate" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - dateTime option
	ValueDateTime primitives.DateTime `json:"valueDateTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDateTime
	ValueDateTimeExt *primitives.PrimitiveExtension `json:"_valueDateTime,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - time option
	ValueTime primitives.Time `json:"valueTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueTime
	ValueTimeExt *primitives.PrimitiveExtension `json:"_valueTime,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - string option
	ValueString string `json:"valueString" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - uri option
	ValueURI string `json:"valueURI" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueURI
	ValueURIExt *primitives.PrimitiveExtension `json:"_valueURI,omitempty" fhir:"cardinality=0..1"`
	// Actual value for initializing the question - Attachment option
	ValueAttachment Attachment `json:"valueAttachment" fhir:"cardinality=1..1,required,choice=value"`
	// Actual value for initializing the question - Coding option
	ValueCoding Coding `json:"valueCoding" fhir:"cardinality=1..1,required,choice=value"`
	// Actual value for initializing the question - Quantity option
	ValueQuantity Quantity `json:"valueQuantity" fhir:"cardinality=1..1,required,choice=value"`
	// Actual value for initializing the question - Reference option
	ValueReference Reference `json:"valueReference" fhir:"cardinality=1..1,required,choice=value"`
}

// QuestionnaireItemItem represents a FHIR BackboneElement for Questionnaire.item.item.
type QuestionnaireItemItem struct {
}

// QuestionnaireItem represents a FHIR BackboneElement for Questionnaire.item.
type QuestionnaireItem struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Unique id for item in questionnaire
	LinkId string `json:"linkId" fhir:"cardinality=1..1,required"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// ElementDefinition - details for the item
	Definition *string `json:"definition,omitempty" fhir:"cardinality=0..1"`
	// Extension for Definition
	DefinitionExt *primitives.PrimitiveExtension `json:"_definition,omitempty" fhir:"cardinality=0..1"`
	// Corresponding concept for this item in a terminology
	Code []Coding `json:"code,omitempty" fhir:"cardinality=0..*"`
	// E.g. "1(a)", "2.5.3"
	Prefix *string `json:"prefix,omitempty" fhir:"cardinality=0..1"`
	// Extension for Prefix
	PrefixExt *primitives.PrimitiveExtension `json:"_prefix,omitempty" fhir:"cardinality=0..1"`
	// Primary text for the item
	Text *string `json:"text,omitempty" fhir:"cardinality=0..1"`
	// Extension for Text
	TextExt *primitives.PrimitiveExtension `json:"_text,omitempty" fhir:"cardinality=0..1"`
	// group | display | boolean | decimal | integer | date | dateTime +
	Type string `json:"type" fhir:"cardinality=1..1,required"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Only allow data when
	EnableWhen []QuestionnaireItemEnableWhen `json:"enableWhen,omitempty" fhir:"cardinality=0..*"`
	// all | any
	EnableBehavior *string `json:"enableBehavior,omitempty" fhir:"cardinality=0..1"`
	// Extension for EnableBehavior
	EnableBehaviorExt *primitives.PrimitiveExtension `json:"_enableBehavior,omitempty" fhir:"cardinality=0..1"`
	// hidden | protected
	DisabledDisplay *string `json:"disabledDisplay,omitempty" fhir:"cardinality=0..1"`
	// Extension for DisabledDisplay
	DisabledDisplayExt *primitives.PrimitiveExtension `json:"_disabledDisplay,omitempty" fhir:"cardinality=0..1"`
	// Whether the item must be included in data results
	Required *bool `json:"required,omitempty" fhir:"cardinality=0..1"`
	// Extension for Required
	RequiredExt *primitives.PrimitiveExtension `json:"_required,omitempty" fhir:"cardinality=0..1"`
	// Whether the item may repeat
	Repeats *bool `json:"repeats,omitempty" fhir:"cardinality=0..1"`
	// Extension for Repeats
	RepeatsExt *primitives.PrimitiveExtension `json:"_repeats,omitempty" fhir:"cardinality=0..1"`
	// Don't allow human editing
	ReadOnly *bool `json:"readOnly,omitempty" fhir:"cardinality=0..1"`
	// Extension for ReadOnly
	ReadOnlyExt *primitives.PrimitiveExtension `json:"_readOnly,omitempty" fhir:"cardinality=0..1"`
	// No more than these many characters
	MaxLength *int `json:"maxLength,omitempty" fhir:"cardinality=0..1"`
	// Extension for MaxLength
	MaxLengthExt *primitives.PrimitiveExtension `json:"_maxLength,omitempty" fhir:"cardinality=0..1"`
	// optionsOnly | optionsOrType | optionsOrString
	AnswerConstraint *string `json:"answerConstraint,omitempty" fhir:"cardinality=0..1"`
	// Extension for AnswerConstraint
	AnswerConstraintExt *primitives.PrimitiveExtension `json:"_answerConstraint,omitempty" fhir:"cardinality=0..1"`
	// ValueSet containing permitted answers
	AnswerValueSet *string `json:"answerValueSet,omitempty" fhir:"cardinality=0..1"`
	// Extension for AnswerValueSet
	AnswerValueSetExt *primitives.PrimitiveExtension `json:"_answerValueSet,omitempty" fhir:"cardinality=0..1"`
	// Permitted answer
	AnswerOption []QuestionnaireItemAnswerOption `json:"answerOption,omitempty" fhir:"cardinality=0..*"`
	// Initial value(s) when item is first rendered
	Initial []QuestionnaireItemInitial `json:"initial,omitempty" fhir:"cardinality=0..*"`
	// Nested questionnaire items
	Item []QuestionnaireItemItem `json:"item,omitempty" fhir:"cardinality=0..*"`
}

// Questionnaire represents a FHIR Questionnaire.
type Questionnaire struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this questionnaire, represented as an absolute URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for questionnaire
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the questionnaire
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this questionnaire (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this questionnaire (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Based on Questionnaire
	DerivedFrom []string `json:"derivedFrom,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for DerivedFrom
	DerivedFromExt *primitives.PrimitiveExtension `json:"_derivedFrom,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Resource that can be subject of QuestionnaireResponse
	SubjectType []string `json:"subjectType,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for SubjectType
	SubjectTypeExt *primitives.PrimitiveExtension `json:"_subjectType,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the questionnaire
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for questionnaire (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this questionnaire is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// When the questionnaire was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// When the questionnaire was last reviewed by the publisher
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// When the questionnaire is expected to be used
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// Concept that represents the overall questionnaire
	Code []Coding `json:"code,omitempty" fhir:"cardinality=0..*,summary"`
	// Questions and sections within the Questionnaire
	Item []QuestionnaireItem `json:"item,omitempty" fhir:"cardinality=0..*"`
}
