// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// Reference represents a FHIR Reference.
type Reference struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Literal reference, Relative, internal or absolute URL
	Reference *string `json:"reference,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Reference
	ReferenceExt *primitives.PrimitiveExtension `json:"_reference,omitempty" fhir:"cardinality=0..1"`
	// Type the reference refers to (e.g. "Patient") - must be a resource in resources
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Logical reference, when literal reference is not known
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Text alternative for the resource
	Display *string `json:"display,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Display
	DisplayExt *primitives.PrimitiveExtension `json:"_display,omitempty" fhir:"cardinality=0..1"`
}
