// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeResearchStudy is the FHIR resource type name for ResearchStudy.
const ResourceTypeResearchStudy = "ResearchStudy"

// ResearchStudyLabel represents a FHIR BackboneElement for ResearchStudy.label.
type ResearchStudyLabel struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// primary | official | scientific | plain-language | subtitle | short-title | acronym | earlier-title | language | auto-translated | human-use | machine-use | duplicate-uid
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// The name
	Value *string `json:"value,omitempty" fhir:"cardinality=0..1"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// ResearchStudyAssociatedParty represents a FHIR BackboneElement for ResearchStudy.associatedParty.
type ResearchStudyAssociatedParty struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Name of associated party
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// sponsor | lead-sponsor | sponsor-investigator | primary-investigator | collaborator | funding-source | general-contact | recruitment-contact | sub-investigator | study-director | study-chair
	Role CodeableConcept `json:"role" fhir:"cardinality=1..1,required"`
	// When active in the role
	Period []Period `json:"period,omitempty" fhir:"cardinality=0..*"`
	// nih | fda | government | nonprofit | academic | industry
	Classifier []CodeableConcept `json:"classifier,omitempty" fhir:"cardinality=0..*"`
	// Individual or organization associated with study (use practitionerRole to specify their organisation)
	Party *Reference `json:"party,omitempty" fhir:"cardinality=0..1"`
}

// ResearchStudyProgressStatus represents a FHIR BackboneElement for ResearchStudy.progressStatus.
type ResearchStudyProgressStatus struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for status or state (e.g. recruitment status)
	State CodeableConcept `json:"state" fhir:"cardinality=1..1,required"`
	// Actual if true else anticipated
	Actual *bool `json:"actual,omitempty" fhir:"cardinality=0..1"`
	// Extension for Actual
	ActualExt *primitives.PrimitiveExtension `json:"_actual,omitempty" fhir:"cardinality=0..1"`
	// Date range
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
}

// ResearchStudyRecruitment represents a FHIR BackboneElement for ResearchStudy.recruitment.
type ResearchStudyRecruitment struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Estimated total number of participants to be enrolled
	TargetNumber *uint `json:"targetNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for TargetNumber
	TargetNumberExt *primitives.PrimitiveExtension `json:"_targetNumber,omitempty" fhir:"cardinality=0..1"`
	// Actual total number of participants enrolled in study
	ActualNumber *uint `json:"actualNumber,omitempty" fhir:"cardinality=0..1"`
	// Extension for ActualNumber
	ActualNumberExt *primitives.PrimitiveExtension `json:"_actualNumber,omitempty" fhir:"cardinality=0..1"`
	// Inclusion and exclusion criteria
	Eligibility *Reference `json:"eligibility,omitempty" fhir:"cardinality=0..1"`
	// Group of participants who were enrolled in study
	ActualGroup *Reference `json:"actualGroup,omitempty" fhir:"cardinality=0..1,summary"`
}

// ResearchStudyComparisonGroup represents a FHIR BackboneElement for ResearchStudy.comparisonGroup.
type ResearchStudyComparisonGroup struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Allows the comparisonGroup for the study and the comparisonGroup for the subject to be linked easily
	LinkId *string `json:"linkId,omitempty" fhir:"cardinality=0..1"`
	// Extension for LinkId
	LinkIdExt *primitives.PrimitiveExtension `json:"_linkId,omitempty" fhir:"cardinality=0..1"`
	// Label for study comparisonGroup
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Categorization of study comparisonGroup
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Short explanation of study path
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Interventions or exposures in this comparisonGroup or cohort
	IntendedExposure []Reference `json:"intendedExposure,omitempty" fhir:"cardinality=0..*"`
	// Group of participants who were enrolled in study comparisonGroup
	ObservedGroup *Reference `json:"observedGroup,omitempty" fhir:"cardinality=0..1"`
}

// ResearchStudyObjective represents a FHIR BackboneElement for ResearchStudy.objective.
type ResearchStudyObjective struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for the objective
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// primary | secondary | exploratory
	Type *CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Description of the objective
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// ResearchStudyOutcomeMeasure represents a FHIR BackboneElement for ResearchStudy.outcomeMeasure.
type ResearchStudyOutcomeMeasure struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for the outcome
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// primary | secondary | exploratory
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*"`
	// Description of the outcome
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Structured outcome definition
	Reference *Reference `json:"reference,omitempty" fhir:"cardinality=0..1"`
}

// ResearchStudy represents a FHIR ResearchStudy.
type ResearchStudy struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this study resource
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Business Identifier for study
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// The business version for the study record
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// Name for this study (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Human readable name of the study
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Additional names for the study
	Label []ResearchStudyLabel `json:"label,omitempty" fhir:"cardinality=0..*"`
	// Steps followed in executing study
	Protocol []Reference `json:"protocol,omitempty" fhir:"cardinality=0..*,summary"`
	// Part of larger study
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// References, URLs, and attachments
	RelatedArtifact []RelatedArtifact `json:"relatedArtifact,omitempty" fhir:"cardinality=0..*"`
	// Date the resource last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// treatment | prevention | diagnostic | supportive-care | screening | health-services-research | basic-science | device-feasibility
	PrimaryPurposeType *CodeableConcept `json:"primaryPurposeType,omitempty" fhir:"cardinality=0..1,summary"`
	// n-a | early-phase-1 | phase-1 | phase-1-phase-2 | phase-2 | phase-2-phase-3 | phase-3 | phase-4
	Phase *CodeableConcept `json:"phase,omitempty" fhir:"cardinality=0..1,summary"`
	// Classifications of the study design characteristics
	StudyDesign []CodeableConcept `json:"studyDesign,omitempty" fhir:"cardinality=0..*,summary"`
	// Drugs, devices, etc. under study
	Focus []CodeableReference `json:"focus,omitempty" fhir:"cardinality=0..*"`
	// Condition being studied
	Condition []CodeableConcept `json:"condition,omitempty" fhir:"cardinality=0..*,summary"`
	// Used to search for the study
	Keyword []CodeableConcept `json:"keyword,omitempty" fhir:"cardinality=0..*,summary"`
	// Geographic area for the study
	Region []CodeableConcept `json:"region,omitempty" fhir:"cardinality=0..*,summary"`
	// Brief text explaining the study
	DescriptionSummary *string `json:"descriptionSummary,omitempty" fhir:"cardinality=0..1"`
	// Extension for DescriptionSummary
	DescriptionSummaryExt *primitives.PrimitiveExtension `json:"_descriptionSummary,omitempty" fhir:"cardinality=0..1"`
	// Detailed narrative of the study
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// When the study began and ended
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Facility where study activities are conducted
	Site []Reference `json:"site,omitempty" fhir:"cardinality=0..*,summary"`
	// Comments made about the study
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Classification for the study
	Classifier []CodeableConcept `json:"classifier,omitempty" fhir:"cardinality=0..*"`
	// Sponsors, collaborators, and other parties
	AssociatedParty []ResearchStudyAssociatedParty `json:"associatedParty,omitempty" fhir:"cardinality=0..*"`
	// Status of study with time for that status
	ProgressStatus []ResearchStudyProgressStatus `json:"progressStatus,omitempty" fhir:"cardinality=0..*"`
	// accrual-goal-met | closed-due-to-toxicity | closed-due-to-lack-of-study-progress | temporarily-closed-per-study-design
	WhyStopped *CodeableConcept `json:"whyStopped,omitempty" fhir:"cardinality=0..1,summary"`
	// Target or actual group of participants enrolled in study
	Recruitment *ResearchStudyRecruitment `json:"recruitment,omitempty" fhir:"cardinality=0..1,summary"`
	// Defined path through the study for a subject
	ComparisonGroup []ResearchStudyComparisonGroup `json:"comparisonGroup,omitempty" fhir:"cardinality=0..*"`
	// A goal for the study
	Objective []ResearchStudyObjective `json:"objective,omitempty" fhir:"cardinality=0..*"`
	// A variable measured during the study
	OutcomeMeasure []ResearchStudyOutcomeMeasure `json:"outcomeMeasure,omitempty" fhir:"cardinality=0..*"`
	// Link to results generated during the study
	Result []Reference `json:"result,omitempty" fhir:"cardinality=0..*,summary"`
}
