// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeStructureMap is the FHIR resource type name for StructureMap.
const ResourceTypeStructureMap = "StructureMap"

// StructureMapStructure represents a FHIR BackboneElement for StructureMap.structure.
type StructureMapStructure struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Canonical reference to structure definition
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// source | queried | target | produced
	Mode string `json:"mode" fhir:"cardinality=1..1,required,summary"`
	// Extension for Mode
	ModeExt *primitives.PrimitiveExtension `json:"_mode,omitempty" fhir:"cardinality=0..1"`
	// Name for type in this map
	Alias *string `json:"alias,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Alias
	AliasExt *primitives.PrimitiveExtension `json:"_alias,omitempty" fhir:"cardinality=0..1"`
	// Documentation on use of structure
	Documentation *string `json:"documentation,omitempty" fhir:"cardinality=0..1"`
	// Extension for Documentation
	DocumentationExt *primitives.PrimitiveExtension `json:"_documentation,omitempty" fhir:"cardinality=0..1"`
}

// StructureMapConst represents a FHIR BackboneElement for StructureMap.const.
type StructureMapConst struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Constant name
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// FHIRPath exression - value of the constant
	Value *string `json:"value,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// StructureMapGroupInput represents a FHIR BackboneElement for StructureMap.group.input.
type StructureMapGroupInput struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Name for this instance of data
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Type for this instance of data
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// source | target
	Mode string `json:"mode" fhir:"cardinality=1..1,required,summary"`
	// Extension for Mode
	ModeExt *primitives.PrimitiveExtension `json:"_mode,omitempty" fhir:"cardinality=0..1"`
	// Documentation for this instance of data
	Documentation *string `json:"documentation,omitempty" fhir:"cardinality=0..1"`
	// Extension for Documentation
	DocumentationExt *primitives.PrimitiveExtension `json:"_documentation,omitempty" fhir:"cardinality=0..1"`
}

// StructureMapGroupRuleSource represents a FHIR BackboneElement for StructureMap.group.rule.source.
type StructureMapGroupRuleSource struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Type or variable this rule applies to
	Context string `json:"context" fhir:"cardinality=1..1,required,summary"`
	// Extension for Context
	ContextExt *primitives.PrimitiveExtension `json:"_context,omitempty" fhir:"cardinality=0..1"`
	// Specified minimum cardinality
	Min *int `json:"min,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Min
	MinExt *primitives.PrimitiveExtension `json:"_min,omitempty" fhir:"cardinality=0..1"`
	// Specified maximum cardinality (number or *)
	Max *string `json:"max,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Max
	MaxExt *primitives.PrimitiveExtension `json:"_max,omitempty" fhir:"cardinality=0..1"`
	// Rule only applies if source has this type
	Type *string `json:"type,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Type
	TypeExt *primitives.PrimitiveExtension `json:"_type,omitempty" fhir:"cardinality=0..1"`
	// Default value if no value exists
	DefaultValue *string `json:"defaultValue,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DefaultValue
	DefaultValueExt *primitives.PrimitiveExtension `json:"_defaultValue,omitempty" fhir:"cardinality=0..1"`
	// Optional field for this source
	Element *string `json:"element,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Element
	ElementExt *primitives.PrimitiveExtension `json:"_element,omitempty" fhir:"cardinality=0..1"`
	// first | not_first | last | not_last | only_one
	ListMode *string `json:"listMode,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ListMode
	ListModeExt *primitives.PrimitiveExtension `json:"_listMode,omitempty" fhir:"cardinality=0..1"`
	// Named context for field, if a field is specified
	Variable *string `json:"variable,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Variable
	VariableExt *primitives.PrimitiveExtension `json:"_variable,omitempty" fhir:"cardinality=0..1"`
	// FHIRPath expression  - must be true or the rule does not apply
	Condition *string `json:"condition,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Condition
	ConditionExt *primitives.PrimitiveExtension `json:"_condition,omitempty" fhir:"cardinality=0..1"`
	// FHIRPath expression  - must be true or the mapping engine throws an error instead of completing
	Check *string `json:"check,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Check
	CheckExt *primitives.PrimitiveExtension `json:"_check,omitempty" fhir:"cardinality=0..1"`
	// Message to put in log if source exists (FHIRPath)
	LogMessage *string `json:"logMessage,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for LogMessage
	LogMessageExt *primitives.PrimitiveExtension `json:"_logMessage,omitempty" fhir:"cardinality=0..1"`
}

// StructureMapGroupRuleTargetParameter represents a FHIR BackboneElement for StructureMap.group.rule.target.parameter.
type StructureMapGroupRuleTargetParameter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Parameter value - variable or literal - id option
	ValueID string `json:"valueID" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueID
	ValueIDExt *primitives.PrimitiveExtension `json:"_valueID,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - string option
	ValueString string `json:"valueString" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - boolean option
	ValueBoolean bool `json:"valueBoolean" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - integer option
	ValueInteger int `json:"valueInteger" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - decimal option
	ValueDecimal float64 `json:"valueDecimal" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueDecimal
	ValueDecimalExt *primitives.PrimitiveExtension `json:"_valueDecimal,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - date option
	ValueDate primitives.Date `json:"valueDate" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - time option
	ValueTime primitives.Time `json:"valueTime" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueTime
	ValueTimeExt *primitives.PrimitiveExtension `json:"_valueTime,omitempty" fhir:"cardinality=0..1"`
	// Parameter value - variable or literal - dateTime option
	ValueDateTime primitives.DateTime `json:"valueDateTime" fhir:"cardinality=1..1,required,summary,choice=value"`
	// Extension for ValueDateTime
	ValueDateTimeExt *primitives.PrimitiveExtension `json:"_valueDateTime,omitempty" fhir:"cardinality=0..1"`
}

// StructureMapGroupRuleTarget represents a FHIR BackboneElement for StructureMap.group.rule.target.
type StructureMapGroupRuleTarget struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Variable this rule applies to
	Context *string `json:"context,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Context
	ContextExt *primitives.PrimitiveExtension `json:"_context,omitempty" fhir:"cardinality=0..1"`
	// Field to create in the context
	Element *string `json:"element,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Element
	ElementExt *primitives.PrimitiveExtension `json:"_element,omitempty" fhir:"cardinality=0..1"`
	// Named context for field, if desired, and a field is specified
	Variable *string `json:"variable,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Variable
	VariableExt *primitives.PrimitiveExtension `json:"_variable,omitempty" fhir:"cardinality=0..1"`
	// first | share | last | single
	ListMode []string `json:"listMode,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for ListMode
	ListModeExt *primitives.PrimitiveExtension `json:"_listMode,omitempty" fhir:"cardinality=0..1"`
	// Internal rule reference for shared list items
	ListRuleId *string `json:"listRuleId,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ListRuleId
	ListRuleIdExt *primitives.PrimitiveExtension `json:"_listRuleId,omitempty" fhir:"cardinality=0..1"`
	// create | copy +
	Transform *string `json:"transform,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Transform
	TransformExt *primitives.PrimitiveExtension `json:"_transform,omitempty" fhir:"cardinality=0..1"`
	// Parameters to the transform
	Parameter []StructureMapGroupRuleTargetParameter `json:"parameter,omitempty" fhir:"cardinality=0..*,summary"`
}

// StructureMapGroupRuleRule represents a FHIR BackboneElement for StructureMap.group.rule.rule.
type StructureMapGroupRuleRule struct {
}

// StructureMapGroupRuleDependentParameter represents a FHIR BackboneElement for StructureMap.group.rule.dependent.parameter.
type StructureMapGroupRuleDependentParameter struct {
}

// StructureMapGroupRuleDependent represents a FHIR BackboneElement for StructureMap.group.rule.dependent.
type StructureMapGroupRuleDependent struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Name of a rule or group to apply
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Parameter to pass to the rule or group
	Parameter []StructureMapGroupRuleDependentParameter `json:"parameter,omitempty" fhir:"cardinality=1..*,required,summary"`
}

// StructureMapGroupRule represents a FHIR BackboneElement for StructureMap.group.rule.
type StructureMapGroupRule struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Name of the rule for internal references
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Source inputs to the mapping
	Source []StructureMapGroupRuleSource `json:"source,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Content to create because of this mapping rule
	Target []StructureMapGroupRuleTarget `json:"target,omitempty" fhir:"cardinality=0..*,summary"`
	// Rules contained in this rule
	Rule []StructureMapGroupRuleRule `json:"rule,omitempty" fhir:"cardinality=0..*,summary"`
	// Which other rules to apply in the context of this rule
	Dependent []StructureMapGroupRuleDependent `json:"dependent,omitempty" fhir:"cardinality=0..*,summary"`
	// Documentation for this instance of data
	Documentation *string `json:"documentation,omitempty" fhir:"cardinality=0..1"`
	// Extension for Documentation
	DocumentationExt *primitives.PrimitiveExtension `json:"_documentation,omitempty" fhir:"cardinality=0..1"`
}

// StructureMapGroup represents a FHIR BackboneElement for StructureMap.group.
type StructureMapGroup struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Human-readable label
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Another group that this group adds rules to
	Extends *string `json:"extends,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Extends
	ExtendsExt *primitives.PrimitiveExtension `json:"_extends,omitempty" fhir:"cardinality=0..1"`
	// types | type-and-types
	TypeMode *string `json:"typeMode,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for TypeMode
	TypeModeExt *primitives.PrimitiveExtension `json:"_typeMode,omitempty" fhir:"cardinality=0..1"`
	// Additional description/explanation for group
	Documentation *string `json:"documentation,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Documentation
	DocumentationExt *primitives.PrimitiveExtension `json:"_documentation,omitempty" fhir:"cardinality=0..1"`
	// Named instance provided when invoking the map
	Input []StructureMapGroupInput `json:"input,omitempty" fhir:"cardinality=1..*,required,summary"`
	// Transform Rule from source to target
	Rule []StructureMapGroupRule `json:"rule,omitempty" fhir:"cardinality=0..*,summary"`
}

// StructureMap represents a FHIR StructureMap.
type StructureMap struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this structure map, represented as a URI (globally unique)
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the structure map
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the structure map
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this structure map (computer friendly)
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this structure map (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the structure map
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for structure map (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this structure map is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Structure Definition used by this map
	Structure []StructureMapStructure `json:"structure,omitempty" fhir:"cardinality=0..*,summary"`
	// Other maps used by this map (canonical URLs)
	Import []string `json:"import,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Import
	ImportExt *primitives.PrimitiveExtension `json:"_import,omitempty" fhir:"cardinality=0..1"`
	// Definition of the constant value used in the map rules
	Const []StructureMapConst `json:"const,omitempty" fhir:"cardinality=0..*,summary"`
	// Named sections for reader convenience
	Group []StructureMapGroup `json:"group,omitempty" fhir:"cardinality=1..*,required,summary"`
}
