// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeSubscriptionTopic is the FHIR resource type name for SubscriptionTopic.
const ResourceTypeSubscriptionTopic = "SubscriptionTopic"

// SubscriptionTopicResourceTriggerQueryCriteria represents a FHIR BackboneElement for SubscriptionTopic.resourceTrigger.queryCriteria.
type SubscriptionTopicResourceTriggerQueryCriteria struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Rule applied to previous resource state
	Previous *string `json:"previous,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Previous
	PreviousExt *primitives.PrimitiveExtension `json:"_previous,omitempty" fhir:"cardinality=0..1"`
	// test-passes | test-fails
	ResultForCreate *string `json:"resultForCreate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ResultForCreate
	ResultForCreateExt *primitives.PrimitiveExtension `json:"_resultForCreate,omitempty" fhir:"cardinality=0..1"`
	// Rule applied to current resource state
	Current *string `json:"current,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Current
	CurrentExt *primitives.PrimitiveExtension `json:"_current,omitempty" fhir:"cardinality=0..1"`
	// test-passes | test-fails
	ResultForDelete *string `json:"resultForDelete,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ResultForDelete
	ResultForDeleteExt *primitives.PrimitiveExtension `json:"_resultForDelete,omitempty" fhir:"cardinality=0..1"`
	// Both must be true flag
	RequireBoth *bool `json:"requireBoth,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for RequireBoth
	RequireBothExt *primitives.PrimitiveExtension `json:"_requireBoth,omitempty" fhir:"cardinality=0..1"`
}

// SubscriptionTopicResourceTrigger represents a FHIR BackboneElement for SubscriptionTopic.resourceTrigger.
type SubscriptionTopicResourceTrigger struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Text representation of the resource trigger
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Data Type or Resource (reference to definition) for this trigger definition
	Resource string `json:"resource" fhir:"cardinality=1..1,required,summary"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
	// create | update | delete
	SupportedInteraction []string `json:"supportedInteraction,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for SupportedInteraction
	SupportedInteractionExt *primitives.PrimitiveExtension `json:"_supportedInteraction,omitempty" fhir:"cardinality=0..1"`
	// Query based trigger rule
	QueryCriteria *SubscriptionTopicResourceTriggerQueryCriteria `json:"queryCriteria,omitempty" fhir:"cardinality=0..1,summary"`
	// FHIRPath based trigger rule
	FhirPathCriteria *string `json:"fhirPathCriteria,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for FhirPathCriteria
	FhirPathCriteriaExt *primitives.PrimitiveExtension `json:"_fhirPathCriteria,omitempty" fhir:"cardinality=0..1"`
}

// SubscriptionTopicEventTrigger represents a FHIR BackboneElement for SubscriptionTopic.eventTrigger.
type SubscriptionTopicEventTrigger struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Text representation of the event trigger
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Event which can trigger a notification from the SubscriptionTopic
	Event CodeableConcept `json:"event" fhir:"cardinality=1..1,required,summary"`
	// Data Type or Resource (reference to definition) for this trigger definition
	Resource string `json:"resource" fhir:"cardinality=1..1,required,summary"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
}

// SubscriptionTopicCanFilterBy represents a FHIR BackboneElement for SubscriptionTopic.canFilterBy.
type SubscriptionTopicCanFilterBy struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Description of this filter parameter
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// URL of the triggering Resource that this filter applies to
	Resource *string `json:"resource,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
	// Human-readable and computation-friendly name for a filter parameter usable by subscriptions on this topic, via Subscription.filterBy.filterParameter
	FilterParameter string `json:"filterParameter" fhir:"cardinality=1..1,required,summary"`
	// Extension for FilterParameter
	FilterParameterExt *primitives.PrimitiveExtension `json:"_filterParameter,omitempty" fhir:"cardinality=0..1"`
	// Canonical URL for a filterParameter definition
	FilterDefinition *string `json:"filterDefinition,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for FilterDefinition
	FilterDefinitionExt *primitives.PrimitiveExtension `json:"_filterDefinition,omitempty" fhir:"cardinality=0..1"`
	// eq | ne | gt | lt | ge | le | sa | eb | ap
	Comparator []string `json:"comparator,omitempty" fhir:"cardinality=0..*"`
	// Extension for Comparator
	ComparatorExt *primitives.PrimitiveExtension `json:"_comparator,omitempty" fhir:"cardinality=0..1"`
	// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | of-type | code-text | text-advanced | iterate
	Modifier []string `json:"modifier,omitempty" fhir:"cardinality=0..*"`
	// Extension for Modifier
	ModifierExt *primitives.PrimitiveExtension `json:"_modifier,omitempty" fhir:"cardinality=0..1"`
}

// SubscriptionTopicNotificationShape represents a FHIR BackboneElement for SubscriptionTopic.notificationShape.
type SubscriptionTopicNotificationShape struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// URL of the Resource that is the focus (main) resource in a notification shape
	Resource string `json:"resource" fhir:"cardinality=1..1,required,summary"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
	// Include directives, rooted in the resource for this shape
	Include []string `json:"include,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Include
	IncludeExt *primitives.PrimitiveExtension `json:"_include,omitempty" fhir:"cardinality=0..1"`
	// Reverse include directives, rooted in the resource for this shape
	RevInclude []string `json:"revInclude,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for RevInclude
	RevIncludeExt *primitives.PrimitiveExtension `json:"_revInclude,omitempty" fhir:"cardinality=0..1"`
}

// SubscriptionTopic represents a FHIR SubscriptionTopic.
type SubscriptionTopic struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this subscription topic, represented as an absolute URI (globally unique)
	URL string `json:"url" fhir:"cardinality=1..1,required,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Business identifier for subscription topic
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the subscription topic
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this subscription topic (computer friendly)
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this subscription topic (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// Based on FHIR protocol or definition
	DerivedFrom []string `json:"derivedFrom,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for DerivedFrom
	DerivedFromExt *primitives.PrimitiveExtension `json:"_derivedFrom,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// If for testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date status first applied
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// The name of the individual or organization that published the SubscriptionTopic
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the SubscriptionTopic
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Content intends to support these contexts
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction of the SubscriptionTopic (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this SubscriptionTopic is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// When SubscriptionTopic is/was approved by publisher
	ApprovalDate *primitives.Date `json:"approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ApprovalDate
	ApprovalDateExt *primitives.PrimitiveExtension `json:"_approvalDate,omitempty" fhir:"cardinality=0..1"`
	// Date the Subscription Topic was last reviewed by the publisher
	LastReviewDate *primitives.Date `json:"lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastReviewDate
	LastReviewDateExt *primitives.PrimitiveExtension `json:"_lastReviewDate,omitempty" fhir:"cardinality=0..1"`
	// The effective date range for the SubscriptionTopic
	EffectivePeriod *Period `json:"effectivePeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// Definition of a resource-based trigger for the subscription topic
	ResourceTrigger []SubscriptionTopicResourceTrigger `json:"resourceTrigger,omitempty" fhir:"cardinality=0..*,summary"`
	// Event definitions the SubscriptionTopic
	EventTrigger []SubscriptionTopicEventTrigger `json:"eventTrigger,omitempty" fhir:"cardinality=0..*,summary"`
	// Properties by which a Subscription can filter notifications from the SubscriptionTopic
	CanFilterBy []SubscriptionTopicCanFilterBy `json:"canFilterBy,omitempty" fhir:"cardinality=0..*,summary"`
	// Properties for describing the shape of notifications generated by this topic
	NotificationShape []SubscriptionTopicNotificationShape `json:"notificationShape,omitempty" fhir:"cardinality=0..*,summary"`
}
