// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeSubscription is the FHIR resource type name for Subscription.
const ResourceTypeSubscription = "Subscription"

// SubscriptionFilterBy represents a FHIR BackboneElement for Subscription.filterBy.
type SubscriptionFilterBy struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Allowed Resource (reference to definition) for this Subscription filter
	ResourceType *string `json:"resourceType,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ResourceType
	ResourceTypeExt *primitives.PrimitiveExtension `json:"_resourceType,omitempty" fhir:"cardinality=0..1"`
	// Filter label defined in SubscriptionTopic
	FilterParameter string `json:"filterParameter" fhir:"cardinality=1..1,required,summary"`
	// Extension for FilterParameter
	FilterParameterExt *primitives.PrimitiveExtension `json:"_filterParameter,omitempty" fhir:"cardinality=0..1"`
	// eq | ne | gt | lt | ge | le | sa | eb | ap
	Comparator *string `json:"comparator,omitempty" fhir:"cardinality=0..1"`
	// Extension for Comparator
	ComparatorExt *primitives.PrimitiveExtension `json:"_comparator,omitempty" fhir:"cardinality=0..1"`
	// missing | exact | contains | not | text | in | not-in | below | above | type | identifier | of-type | code-text | text-advanced | iterate
	Modifier *string `json:"modifier,omitempty" fhir:"cardinality=0..1"`
	// Extension for Modifier
	ModifierExt *primitives.PrimitiveExtension `json:"_modifier,omitempty" fhir:"cardinality=0..1"`
	// Literal value or resource path
	Value string `json:"value" fhir:"cardinality=1..1,required,summary"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// SubscriptionParameter represents a FHIR BackboneElement for Subscription.parameter.
type SubscriptionParameter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Name (key) of the parameter
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Value of the parameter to use or pass through
	Value string `json:"value" fhir:"cardinality=1..1,required"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// Subscription represents a FHIR Subscription.
type Subscription struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Additional identifiers (business identifier)
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Human readable name for this subscription
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// requested | active | error | off | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reference to the subscription topic being subscribed to
	Topic string `json:"topic" fhir:"cardinality=1..1,required,summary"`
	// Extension for Topic
	TopicExt *primitives.PrimitiveExtension `json:"_topic,omitempty" fhir:"cardinality=0..1"`
	// Contact details for source (e.g. troubleshooting)
	Contact []ContactPoint `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// When to automatically delete the subscription
	End *primitives.Instant `json:"end,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for End
	EndExt *primitives.PrimitiveExtension `json:"_end,omitempty" fhir:"cardinality=0..1"`
	// Entity responsible for Subscription changes
	ManagingEntity *Reference `json:"managingEntity,omitempty" fhir:"cardinality=0..1,summary"`
	// Description of why this subscription was created
	Reason *string `json:"reason,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Reason
	ReasonExt *primitives.PrimitiveExtension `json:"_reason,omitempty" fhir:"cardinality=0..1"`
	// Criteria for narrowing the subscription topic stream
	FilterBy []SubscriptionFilterBy `json:"filterBy,omitempty" fhir:"cardinality=0..*,summary"`
	// Channel type for notifications
	ChannelType Coding `json:"channelType" fhir:"cardinality=1..1,required,summary"`
	// Where the channel points to
	Endpoint *string `json:"endpoint,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Endpoint
	EndpointExt *primitives.PrimitiveExtension `json:"_endpoint,omitempty" fhir:"cardinality=0..1"`
	// Channel type
	Parameter []SubscriptionParameter `json:"parameter,omitempty" fhir:"cardinality=0..*"`
	// Interval in seconds to send 'heartbeat' notification
	HeartbeatPeriod *uint `json:"heartbeatPeriod,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for HeartbeatPeriod
	HeartbeatPeriodExt *primitives.PrimitiveExtension `json:"_heartbeatPeriod,omitempty" fhir:"cardinality=0..1"`
	// Timeout in seconds to attempt notification delivery
	Timeout *uint `json:"timeout,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Timeout
	TimeoutExt *primitives.PrimitiveExtension `json:"_timeout,omitempty" fhir:"cardinality=0..1"`
	// MIME type to send, or omit for no payload
	ContentType *string `json:"contentType,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ContentType
	ContentTypeExt *primitives.PrimitiveExtension `json:"_contentType,omitempty" fhir:"cardinality=0..1"`
	// empty | id-only | full-resource
	Content *string `json:"content,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Content
	ContentExt *primitives.PrimitiveExtension `json:"_content,omitempty" fhir:"cardinality=0..1"`
	// Maximum number of events that can be combined in a single notification
	MaxCount *int `json:"maxCount,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for MaxCount
	MaxCountExt *primitives.PrimitiveExtension `json:"_maxCount,omitempty" fhir:"cardinality=0..1"`
}
