// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeSubstanceNucleicAcid is the FHIR resource type name for SubstanceNucleicAcid.
const ResourceTypeSubstanceNucleicAcid = "SubstanceNucleicAcid"

// SubstanceNucleicAcidSubunitLinkage represents a FHIR BackboneElement for SubstanceNucleicAcid.subunit.linkage.
type SubstanceNucleicAcidSubunitLinkage struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The entity that links the sugar residues together should also be captured for nearly all naturally occurring nucleic acid the linkage is a phosphate group. For many synthetic oligonucleotides phosphorothioate linkages are often seen. Linkage connectivity is assumed to be 3’-5’. If the linkage is either 3’-3’ or 5’-5’ this should be specified
	Connectivity *string `json:"connectivity,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Connectivity
	ConnectivityExt *primitives.PrimitiveExtension `json:"_connectivity,omitempty" fhir:"cardinality=0..1"`
	// Each linkage will be registered as a fragment and have an ID
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Each linkage will be registered as a fragment and have at least one name. A single name shall be assigned to each linkage
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Residues shall be captured as described in 5.3.6.8.3
	ResidueSite *string `json:"residueSite,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ResidueSite
	ResidueSiteExt *primitives.PrimitiveExtension `json:"_residueSite,omitempty" fhir:"cardinality=0..1"`
}

// SubstanceNucleicAcidSubunitSugar represents a FHIR BackboneElement for SubstanceNucleicAcid.subunit.sugar.
type SubstanceNucleicAcidSubunitSugar struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The Substance ID of the sugar or sugar-like component that make up the nucleotide
	Identifier *Identifier `json:"identifier,omitempty" fhir:"cardinality=0..1,summary"`
	// The name of the sugar or sugar-like component that make up the nucleotide
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// The residues that contain a given sugar will be captured. The order of given residues will be captured in the 5‘-3‘direction consistent with the base sequences listed above
	ResidueSite *string `json:"residueSite,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for ResidueSite
	ResidueSiteExt *primitives.PrimitiveExtension `json:"_residueSite,omitempty" fhir:"cardinality=0..1"`
}

// SubstanceNucleicAcidSubunit represents a FHIR BackboneElement for SubstanceNucleicAcid.subunit.
type SubstanceNucleicAcidSubunit struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Index of linear sequences of nucleic acids in order of decreasing length. Sequences of the same length will be ordered by molecular weight. Subunits that have identical sequences will be repeated and have sequential subscripts
	Subunit *int `json:"subunit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Subunit
	SubunitExt *primitives.PrimitiveExtension `json:"_subunit,omitempty" fhir:"cardinality=0..1"`
	// Actual nucleotide sequence notation from 5' to 3' end using standard single letter codes. In addition to the base sequence, sugar and type of phosphate or non-phosphate linkage should also be captured
	Sequence *string `json:"sequence,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Sequence
	SequenceExt *primitives.PrimitiveExtension `json:"_sequence,omitempty" fhir:"cardinality=0..1"`
	// The length of the sequence shall be captured
	Length *int `json:"length,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Length
	LengthExt *primitives.PrimitiveExtension `json:"_length,omitempty" fhir:"cardinality=0..1"`
	// (TBC)
	SequenceAttachment *Attachment `json:"sequenceAttachment,omitempty" fhir:"cardinality=0..1,summary"`
	// The nucleotide present at the 5’ terminal shall be specified based on a controlled vocabulary. Since the sequence is represented from the 5' to the 3' end, the 5’ prime nucleotide is the letter at the first position in the sequence. A separate representation would be redundant
	FivePrime *CodeableConcept `json:"fivePrime,omitempty" fhir:"cardinality=0..1,summary"`
	// The nucleotide present at the 3’ terminal shall be specified based on a controlled vocabulary. Since the sequence is represented from the 5' to the 3' end, the 5’ prime nucleotide is the letter at the last position in the sequence. A separate representation would be redundant
	ThreePrime *CodeableConcept `json:"threePrime,omitempty" fhir:"cardinality=0..1,summary"`
	// The linkages between sugar residues will also be captured
	Linkage []SubstanceNucleicAcidSubunitLinkage `json:"linkage,omitempty" fhir:"cardinality=0..*,summary"`
	// 5.3.6.8.1 Sugar ID (Mandatory)
	Sugar []SubstanceNucleicAcidSubunitSugar `json:"sugar,omitempty" fhir:"cardinality=0..*,summary"`
}

// SubstanceNucleicAcid represents a FHIR SubstanceNucleicAcid.
type SubstanceNucleicAcid struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// The type of the sequence shall be specified based on a controlled vocabulary
	SequenceType *CodeableConcept `json:"sequenceType,omitempty" fhir:"cardinality=0..1,summary"`
	// The number of linear sequences of nucleotides linked through phosphodiester bonds shall be described. Subunits would be strands of nucleic acids that are tightly associated typically through Watson-Crick base pairing. NOTE: If not specified in the reference source, the assumption is that there is 1 subunit
	NumberOfSubunits *int `json:"numberOfSubunits,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for NumberOfSubunits
	NumberOfSubunitsExt *primitives.PrimitiveExtension `json:"_numberOfSubunits,omitempty" fhir:"cardinality=0..1"`
	// The area of hybridisation shall be described if applicable for double stranded RNA or DNA. The number associated with the subunit followed by the number associated to the residue shall be specified in increasing order. The underscore “” shall be used as separator as follows: “Subunitnumber Residue”
	AreaOfHybridisation *string `json:"areaOfHybridisation,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AreaOfHybridisation
	AreaOfHybridisationExt *primitives.PrimitiveExtension `json:"_areaOfHybridisation,omitempty" fhir:"cardinality=0..1"`
	// (TBC)
	OligoNucleotideType *CodeableConcept `json:"oligoNucleotideType,omitempty" fhir:"cardinality=0..1,summary"`
	// Subunits are listed in order of decreasing length; sequences of the same length will be ordered by molecular weight; subunits that have identical sequences will be repeated multiple times
	Subunit []SubstanceNucleicAcidSubunit `json:"subunit,omitempty" fhir:"cardinality=0..*,summary"`
}
