// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeSupplyRequest is the FHIR resource type name for SupplyRequest.
const ResourceTypeSupplyRequest = "SupplyRequest"

// SupplyRequestParameter represents a FHIR BackboneElement for SupplyRequest.parameter.
type SupplyRequestParameter struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Item detail
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1"`
	// Value of detail - CodeableConcept option
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of detail - Quantity option
	ValueQuantity *Quantity `json:"valueQuantity,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of detail - Range option
	ValueRange *Range `json:"valueRange,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Value of detail - boolean option
	ValueBoolean *bool `json:"valueBoolean,omitempty" fhir:"cardinality=0..1,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
}

// SupplyRequest represents a FHIR SupplyRequest.
type SupplyRequest struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Business Identifier for SupplyRequest
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// draft | active | suspended +
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// What other request is fulfilled by this supply request
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// The kind of supply (central, non-stock, etc.)
	Category *CodeableConcept `json:"category,omitempty" fhir:"cardinality=0..1,summary"`
	// routine | urgent | asap | stat
	Priority *string `json:"priority,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// The patient for who the supply request is for
	DeliverFor *Reference `json:"deliverFor,omitempty" fhir:"cardinality=0..1"`
	// Medication, Substance, or Device requested to be supplied
	Item CodeableReference `json:"item" fhir:"cardinality=1..1,required,summary"`
	// The requested amount of the item indicated
	Quantity Quantity `json:"quantity" fhir:"cardinality=1..1,required,summary"`
	// Ordered item details
	Parameter []SupplyRequestParameter `json:"parameter,omitempty" fhir:"cardinality=0..*"`
	// When the request should be fulfilled - dateTime option
	OccurrenceDateTime *primitives.DateTime `json:"occurrenceDateTime,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// Extension for OccurrenceDateTime
	OccurrenceDateTimeExt *primitives.PrimitiveExtension `json:"_occurrenceDateTime,omitempty" fhir:"cardinality=0..1"`
	// When the request should be fulfilled - Period option
	OccurrencePeriod *Period `json:"occurrencePeriod,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When the request should be fulfilled - Timing option
	OccurrenceTiming *Timing `json:"occurrenceTiming,omitempty" fhir:"cardinality=0..1,summary,choice=occurrence"`
	// When the request was made
	AuthoredOn *primitives.DateTime `json:"authoredOn,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for AuthoredOn
	AuthoredOnExt *primitives.PrimitiveExtension `json:"_authoredOn,omitempty" fhir:"cardinality=0..1"`
	// Individual making the request
	Requester *Reference `json:"requester,omitempty" fhir:"cardinality=0..1,summary"`
	// Who is intended to fulfill the request
	Supplier []Reference `json:"supplier,omitempty" fhir:"cardinality=0..*,summary"`
	// The reason why the supply item was requested
	Reason []CodeableReference `json:"reason,omitempty" fhir:"cardinality=0..*"`
	// The origin of the supply
	DeliverFrom *Reference `json:"deliverFrom,omitempty" fhir:"cardinality=0..1"`
	// The destination of the supply
	DeliverTo *Reference `json:"deliverTo,omitempty" fhir:"cardinality=0..1"`
}
