// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeTestScript is the FHIR resource type name for TestScript.
const ResourceTypeTestScript = "TestScript"

// TestScriptOrigin represents a FHIR BackboneElement for TestScript.origin.
type TestScriptOrigin struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The index of the abstract origin server starting at 1
	Index int `json:"index" fhir:"cardinality=1..1,required"`
	// Extension for Index
	IndexExt *primitives.PrimitiveExtension `json:"_index,omitempty" fhir:"cardinality=0..1"`
	// FHIR-Client | FHIR-SDC-FormFiller
	Profile Coding `json:"profile" fhir:"cardinality=1..1,required"`
	// The url path of the origin server
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptDestination represents a FHIR BackboneElement for TestScript.destination.
type TestScriptDestination struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The index of the abstract destination server starting at 1
	Index int `json:"index" fhir:"cardinality=1..1,required"`
	// Extension for Index
	IndexExt *primitives.PrimitiveExtension `json:"_index,omitempty" fhir:"cardinality=0..1"`
	// FHIR-Server | FHIR-SDC-FormManager | FHIR-SDC-FormReceiver | FHIR-SDC-FormProcessor
	Profile Coding `json:"profile" fhir:"cardinality=1..1,required"`
	// The url path of the destination server
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptMetadataLink represents a FHIR BackboneElement for TestScript.metadata.link.
type TestScriptMetadataLink struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// URL to the specification
	URL string `json:"url" fhir:"cardinality=1..1,required"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Short description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptMetadataCapability represents a FHIR BackboneElement for TestScript.metadata.capability.
type TestScriptMetadataCapability struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Are the capabilities required?
	Required bool `json:"required" fhir:"cardinality=1..1,required"`
	// Extension for Required
	RequiredExt *primitives.PrimitiveExtension `json:"_required,omitempty" fhir:"cardinality=0..1"`
	// Are the capabilities validated?
	Validated bool `json:"validated" fhir:"cardinality=1..1,required"`
	// Extension for Validated
	ValidatedExt *primitives.PrimitiveExtension `json:"_validated,omitempty" fhir:"cardinality=0..1"`
	// The expected capabilities of the server
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Which origin server these requirements apply to
	Origin []int `json:"origin,omitempty" fhir:"cardinality=0..*"`
	// Extension for Origin
	OriginExt *primitives.PrimitiveExtension `json:"_origin,omitempty" fhir:"cardinality=0..1"`
	// Which server these requirements apply to
	Destination *int `json:"destination,omitempty" fhir:"cardinality=0..1"`
	// Extension for Destination
	DestinationExt *primitives.PrimitiveExtension `json:"_destination,omitempty" fhir:"cardinality=0..1"`
	// Links to the FHIR specification
	Link []string `json:"link,omitempty" fhir:"cardinality=0..*"`
	// Extension for Link
	LinkExt *primitives.PrimitiveExtension `json:"_link,omitempty" fhir:"cardinality=0..1"`
	// Required Capability Statement
	Capabilities string `json:"capabilities" fhir:"cardinality=1..1,required"`
	// Extension for Capabilities
	CapabilitiesExt *primitives.PrimitiveExtension `json:"_capabilities,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptMetadata represents a FHIR BackboneElement for TestScript.metadata.
type TestScriptMetadata struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Links to the FHIR specification
	Link []TestScriptMetadataLink `json:"link,omitempty" fhir:"cardinality=0..*"`
	// Capabilities  that are assumed to function correctly on the FHIR server being tested
	Capability []TestScriptMetadataCapability `json:"capability,omitempty" fhir:"cardinality=1..*,required"`
}

// TestScriptScope represents a FHIR BackboneElement for TestScript.scope.
type TestScriptScope struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The specific conformance artifact being tested
	Artifact string `json:"artifact" fhir:"cardinality=1..1,required"`
	// Extension for Artifact
	ArtifactExt *primitives.PrimitiveExtension `json:"_artifact,omitempty" fhir:"cardinality=0..1"`
	// required | optional | strict
	Conformance *CodeableConcept `json:"conformance,omitempty" fhir:"cardinality=0..1"`
	// unit | integration | production
	Phase *CodeableConcept `json:"phase,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptFixture represents a FHIR BackboneElement for TestScript.fixture.
type TestScriptFixture struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Whether or not to implicitly create the fixture during setup
	Autocreate bool `json:"autocreate" fhir:"cardinality=1..1,required"`
	// Extension for Autocreate
	AutocreateExt *primitives.PrimitiveExtension `json:"_autocreate,omitempty" fhir:"cardinality=0..1"`
	// Whether or not to implicitly delete the fixture during teardown
	Autodelete bool `json:"autodelete" fhir:"cardinality=1..1,required"`
	// Extension for Autodelete
	AutodeleteExt *primitives.PrimitiveExtension `json:"_autodelete,omitempty" fhir:"cardinality=0..1"`
	// Reference of the resource
	Resource *Reference `json:"resource,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptVariable represents a FHIR BackboneElement for TestScript.variable.
type TestScriptVariable struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Descriptive name for this variable
	Name string `json:"name" fhir:"cardinality=1..1,required"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Default, hard-coded, or user-defined value for this variable
	DefaultValue *string `json:"defaultValue,omitempty" fhir:"cardinality=0..1"`
	// Extension for DefaultValue
	DefaultValueExt *primitives.PrimitiveExtension `json:"_defaultValue,omitempty" fhir:"cardinality=0..1"`
	// Natural language description of the variable
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The FHIRPath expression against the fixture body
	Expression *string `json:"expression,omitempty" fhir:"cardinality=0..1"`
	// Extension for Expression
	ExpressionExt *primitives.PrimitiveExtension `json:"_expression,omitempty" fhir:"cardinality=0..1"`
	// HTTP header field name for source
	HeaderField *string `json:"headerField,omitempty" fhir:"cardinality=0..1"`
	// Extension for HeaderField
	HeaderFieldExt *primitives.PrimitiveExtension `json:"_headerField,omitempty" fhir:"cardinality=0..1"`
	// Hint help text for default value to enter
	Hint *string `json:"hint,omitempty" fhir:"cardinality=0..1"`
	// Extension for Hint
	HintExt *primitives.PrimitiveExtension `json:"_hint,omitempty" fhir:"cardinality=0..1"`
	// XPath or JSONPath against the fixture body
	Path *string `json:"path,omitempty" fhir:"cardinality=0..1"`
	// Extension for Path
	PathExt *primitives.PrimitiveExtension `json:"_path,omitempty" fhir:"cardinality=0..1"`
	// Fixture Id of source expression or headerField within this variable
	SourceId *string `json:"sourceId,omitempty" fhir:"cardinality=0..1"`
	// Extension for SourceId
	SourceIdExt *primitives.PrimitiveExtension `json:"_sourceId,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptSetupActionOperationRequestHeader represents a FHIR BackboneElement for TestScript.setup.action.operation.requestHeader.
type TestScriptSetupActionOperationRequestHeader struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// HTTP header field name
	Field string `json:"field" fhir:"cardinality=1..1,required"`
	// Extension for Field
	FieldExt *primitives.PrimitiveExtension `json:"_field,omitempty" fhir:"cardinality=0..1"`
	// HTTP headerfield value
	Value string `json:"value" fhir:"cardinality=1..1,required"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptSetupActionOperation represents a FHIR BackboneElement for TestScript.setup.action.operation.
type TestScriptSetupActionOperation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The operation code type that will be executed
	Type *Coding `json:"type,omitempty" fhir:"cardinality=0..1"`
	// Resource type
	Resource *string `json:"resource,omitempty" fhir:"cardinality=0..1"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
	// Tracking/logging operation label
	Label *string `json:"label,omitempty" fhir:"cardinality=0..1"`
	// Extension for Label
	LabelExt *primitives.PrimitiveExtension `json:"_label,omitempty" fhir:"cardinality=0..1"`
	// Tracking/reporting operation description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// Mime type to accept in the payload of the response, with charset etc
	Accept *string `json:"accept,omitempty" fhir:"cardinality=0..1"`
	// Extension for Accept
	AcceptExt *primitives.PrimitiveExtension `json:"_accept,omitempty" fhir:"cardinality=0..1"`
	// Mime type of the request payload contents, with charset etc
	ContentType *string `json:"contentType,omitempty" fhir:"cardinality=0..1"`
	// Extension for ContentType
	ContentTypeExt *primitives.PrimitiveExtension `json:"_contentType,omitempty" fhir:"cardinality=0..1"`
	// Server responding to the request
	Destination *int `json:"destination,omitempty" fhir:"cardinality=0..1"`
	// Extension for Destination
	DestinationExt *primitives.PrimitiveExtension `json:"_destination,omitempty" fhir:"cardinality=0..1"`
	// Whether or not to send the request url in encoded format
	EncodeRequestUrl bool `json:"encodeRequestUrl" fhir:"cardinality=1..1,required"`
	// Extension for EncodeRequestUrl
	EncodeRequestUrlExt *primitives.PrimitiveExtension `json:"_encodeRequestUrl,omitempty" fhir:"cardinality=0..1"`
	// delete | get | options | patch | post | put | head
	Method *string `json:"method,omitempty" fhir:"cardinality=0..1"`
	// Extension for Method
	MethodExt *primitives.PrimitiveExtension `json:"_method,omitempty" fhir:"cardinality=0..1"`
	// Server initiating the request
	Origin *int `json:"origin,omitempty" fhir:"cardinality=0..1"`
	// Extension for Origin
	OriginExt *primitives.PrimitiveExtension `json:"_origin,omitempty" fhir:"cardinality=0..1"`
	// Explicitly defined path parameters
	Params *string `json:"params,omitempty" fhir:"cardinality=0..1"`
	// Extension for Params
	ParamsExt *primitives.PrimitiveExtension `json:"_params,omitempty" fhir:"cardinality=0..1"`
	// Each operation can have one or more header elements
	RequestHeader []TestScriptSetupActionOperationRequestHeader `json:"requestHeader,omitempty" fhir:"cardinality=0..*"`
	// Fixture Id of mapped request
	RequestId *string `json:"requestId,omitempty" fhir:"cardinality=0..1"`
	// Extension for RequestId
	RequestIdExt *primitives.PrimitiveExtension `json:"_requestId,omitempty" fhir:"cardinality=0..1"`
	// Fixture Id of mapped response
	ResponseId *string `json:"responseId,omitempty" fhir:"cardinality=0..1"`
	// Extension for ResponseId
	ResponseIdExt *primitives.PrimitiveExtension `json:"_responseId,omitempty" fhir:"cardinality=0..1"`
	// Fixture Id of body for PUT and POST requests
	SourceId *string `json:"sourceId,omitempty" fhir:"cardinality=0..1"`
	// Extension for SourceId
	SourceIdExt *primitives.PrimitiveExtension `json:"_sourceId,omitempty" fhir:"cardinality=0..1"`
	// Id of fixture used for extracting the [id],  [type], and [vid] for GET requests
	TargetId *string `json:"targetId,omitempty" fhir:"cardinality=0..1"`
	// Extension for TargetId
	TargetIdExt *primitives.PrimitiveExtension `json:"_targetId,omitempty" fhir:"cardinality=0..1"`
	// Request URL
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptSetupActionAssertRequirement represents a FHIR BackboneElement for TestScript.setup.action.assert.requirement.
type TestScriptSetupActionAssertRequirement struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Link or reference to the testing requirement - uri option
	LinkURI *string `json:"linkURI,omitempty" fhir:"cardinality=0..1,choice=link"`
	// Extension for LinkURI
	LinkURIExt *primitives.PrimitiveExtension `json:"_linkURI,omitempty" fhir:"cardinality=0..1"`
	// Link or reference to the testing requirement - canonical option
	LinkCanonical *string `json:"linkCanonical,omitempty" fhir:"cardinality=0..1,choice=link"`
	// Extension for LinkCanonical
	LinkCanonicalExt *primitives.PrimitiveExtension `json:"_linkCanonical,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptSetupActionAssert represents a FHIR BackboneElement for TestScript.setup.action.assert.
type TestScriptSetupActionAssert struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Tracking/logging assertion label
	Label *string `json:"label,omitempty" fhir:"cardinality=0..1"`
	// Extension for Label
	LabelExt *primitives.PrimitiveExtension `json:"_label,omitempty" fhir:"cardinality=0..1"`
	// Tracking/reporting assertion description
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// response | request
	Direction *string `json:"direction,omitempty" fhir:"cardinality=0..1"`
	// Extension for Direction
	DirectionExt *primitives.PrimitiveExtension `json:"_direction,omitempty" fhir:"cardinality=0..1"`
	// Id of the source fixture to be evaluated
	CompareToSourceId *string `json:"compareToSourceId,omitempty" fhir:"cardinality=0..1"`
	// Extension for CompareToSourceId
	CompareToSourceIdExt *primitives.PrimitiveExtension `json:"_compareToSourceId,omitempty" fhir:"cardinality=0..1"`
	// The FHIRPath expression to evaluate against the source fixture
	CompareToSourceExpression *string `json:"compareToSourceExpression,omitempty" fhir:"cardinality=0..1"`
	// Extension for CompareToSourceExpression
	CompareToSourceExpressionExt *primitives.PrimitiveExtension `json:"_compareToSourceExpression,omitempty" fhir:"cardinality=0..1"`
	// XPath or JSONPath expression to evaluate against the source fixture
	CompareToSourcePath *string `json:"compareToSourcePath,omitempty" fhir:"cardinality=0..1"`
	// Extension for CompareToSourcePath
	CompareToSourcePathExt *primitives.PrimitiveExtension `json:"_compareToSourcePath,omitempty" fhir:"cardinality=0..1"`
	// Mime type to compare against the 'Content-Type' header
	ContentType *string `json:"contentType,omitempty" fhir:"cardinality=0..1"`
	// Extension for ContentType
	ContentTypeExt *primitives.PrimitiveExtension `json:"_contentType,omitempty" fhir:"cardinality=0..1"`
	// fail | pass | skip | stop
	DefaultManualCompletion *string `json:"defaultManualCompletion,omitempty" fhir:"cardinality=0..1"`
	// Extension for DefaultManualCompletion
	DefaultManualCompletionExt *primitives.PrimitiveExtension `json:"_defaultManualCompletion,omitempty" fhir:"cardinality=0..1"`
	// The FHIRPath expression to be evaluated
	Expression *string `json:"expression,omitempty" fhir:"cardinality=0..1"`
	// Extension for Expression
	ExpressionExt *primitives.PrimitiveExtension `json:"_expression,omitempty" fhir:"cardinality=0..1"`
	// HTTP header field name
	HeaderField *string `json:"headerField,omitempty" fhir:"cardinality=0..1"`
	// Extension for HeaderField
	HeaderFieldExt *primitives.PrimitiveExtension `json:"_headerField,omitempty" fhir:"cardinality=0..1"`
	// Fixture Id of minimum content resource
	MinimumId *string `json:"minimumId,omitempty" fhir:"cardinality=0..1"`
	// Extension for MinimumId
	MinimumIdExt *primitives.PrimitiveExtension `json:"_minimumId,omitempty" fhir:"cardinality=0..1"`
	// Perform validation on navigation links?
	NavigationLinks *bool `json:"navigationLinks,omitempty" fhir:"cardinality=0..1"`
	// Extension for NavigationLinks
	NavigationLinksExt *primitives.PrimitiveExtension `json:"_navigationLinks,omitempty" fhir:"cardinality=0..1"`
	// equals | notEquals | in | notIn | greaterThan | lessThan | empty | notEmpty | contains | notContains | eval | manualEval
	Operator *string `json:"operator,omitempty" fhir:"cardinality=0..1"`
	// Extension for Operator
	OperatorExt *primitives.PrimitiveExtension `json:"_operator,omitempty" fhir:"cardinality=0..1"`
	// XPath or JSONPath expression
	Path *string `json:"path,omitempty" fhir:"cardinality=0..1"`
	// Extension for Path
	PathExt *primitives.PrimitiveExtension `json:"_path,omitempty" fhir:"cardinality=0..1"`
	// delete | get | options | patch | post | put | head
	RequestMethod *string `json:"requestMethod,omitempty" fhir:"cardinality=0..1"`
	// Extension for RequestMethod
	RequestMethodExt *primitives.PrimitiveExtension `json:"_requestMethod,omitempty" fhir:"cardinality=0..1"`
	// Request URL comparison value
	RequestURL *string `json:"requestURL,omitempty" fhir:"cardinality=0..1"`
	// Extension for RequestURL
	RequestURLExt *primitives.PrimitiveExtension `json:"_requestURL,omitempty" fhir:"cardinality=0..1"`
	// Resource type
	Resource *string `json:"resource,omitempty" fhir:"cardinality=0..1"`
	// Extension for Resource
	ResourceExt *primitives.PrimitiveExtension `json:"_resource,omitempty" fhir:"cardinality=0..1"`
	// continue | switchingProtocols | okay | created | accepted | nonAuthoritativeInformation | noContent | resetContent | partialContent | multipleChoices | movedPermanently | found | seeOther | notModified | useProxy | temporaryRedirect | permanentRedirect | badRequest | unauthorized | paymentRequired | forbidden | notFound | methodNotAllowed | notAcceptable | proxyAuthenticationRequired | requestTimeout | conflict | gone | lengthRequired | preconditionFailed | contentTooLarge | uriTooLong | unsupportedMediaType | rangeNotSatisfiable | expectationFailed | misdirectedRequest | unprocessableContent | upgradeRequired | internalServerError | notImplemented | badGateway | serviceUnavailable | gatewayTimeout | httpVersionNotSupported
	Response *string `json:"response,omitempty" fhir:"cardinality=0..1"`
	// Extension for Response
	ResponseExt *primitives.PrimitiveExtension `json:"_response,omitempty" fhir:"cardinality=0..1"`
	// HTTP response code to test
	ResponseCode *string `json:"responseCode,omitempty" fhir:"cardinality=0..1"`
	// Extension for ResponseCode
	ResponseCodeExt *primitives.PrimitiveExtension `json:"_responseCode,omitempty" fhir:"cardinality=0..1"`
	// Fixture Id of source expression or headerField
	SourceId *string `json:"sourceId,omitempty" fhir:"cardinality=0..1"`
	// Extension for SourceId
	SourceIdExt *primitives.PrimitiveExtension `json:"_sourceId,omitempty" fhir:"cardinality=0..1"`
	// If this assert fails, will the current test execution stop?
	StopTestOnFail bool `json:"stopTestOnFail" fhir:"cardinality=1..1,required"`
	// Extension for StopTestOnFail
	StopTestOnFailExt *primitives.PrimitiveExtension `json:"_stopTestOnFail,omitempty" fhir:"cardinality=0..1"`
	// Profile Id of validation profile reference
	ValidateProfileId *string `json:"validateProfileId,omitempty" fhir:"cardinality=0..1"`
	// Extension for ValidateProfileId
	ValidateProfileIdExt *primitives.PrimitiveExtension `json:"_validateProfileId,omitempty" fhir:"cardinality=0..1"`
	// The value to compare to
	Value *string `json:"value,omitempty" fhir:"cardinality=0..1"`
	// Extension for Value
	ValueExt *primitives.PrimitiveExtension `json:"_value,omitempty" fhir:"cardinality=0..1"`
	// Will this assert produce a warning only on error?
	WarningOnly bool `json:"warningOnly" fhir:"cardinality=1..1,required"`
	// Extension for WarningOnly
	WarningOnlyExt *primitives.PrimitiveExtension `json:"_warningOnly,omitempty" fhir:"cardinality=0..1"`
	// Links or references to the testing requirements
	Requirement []TestScriptSetupActionAssertRequirement `json:"requirement,omitempty" fhir:"cardinality=0..*"`
}

// TestScriptSetupAction represents a FHIR BackboneElement for TestScript.setup.action.
type TestScriptSetupAction struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The setup operation to perform
	Operation *TestScriptSetupActionOperation `json:"operation,omitempty" fhir:"cardinality=0..1"`
	// The assertion to perform
	Assert *TestScriptSetupActionAssert `json:"assert,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptSetup represents a FHIR BackboneElement for TestScript.setup.
type TestScriptSetup struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// A setup operation or assert to perform
	Action []TestScriptSetupAction `json:"action,omitempty" fhir:"cardinality=1..*,required"`
}

// TestScriptTestActionOperation represents a FHIR BackboneElement for TestScript.test.action.operation.
type TestScriptTestActionOperation struct {
}

// TestScriptTestActionAssert represents a FHIR BackboneElement for TestScript.test.action.assert.
type TestScriptTestActionAssert struct {
}

// TestScriptTestAction represents a FHIR BackboneElement for TestScript.test.action.
type TestScriptTestAction struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The setup operation to perform
	Operation *TestScriptTestActionOperation `json:"operation,omitempty" fhir:"cardinality=0..1"`
	// The setup assertion to perform
	Assert *TestScriptTestActionAssert `json:"assert,omitempty" fhir:"cardinality=0..1"`
}

// TestScriptTest represents a FHIR BackboneElement for TestScript.test.
type TestScriptTest struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Tracking/logging name of this test
	Name *string `json:"name,omitempty" fhir:"cardinality=0..1"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Tracking/reporting short description of the test
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// A test operation or assert to perform
	Action []TestScriptTestAction `json:"action,omitempty" fhir:"cardinality=1..*,required"`
}

// TestScriptTeardownActionOperation represents a FHIR BackboneElement for TestScript.teardown.action.operation.
type TestScriptTeardownActionOperation struct {
}

// TestScriptTeardownAction represents a FHIR BackboneElement for TestScript.teardown.action.
type TestScriptTeardownAction struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The teardown operation to perform
	Operation TestScriptTeardownActionOperation `json:"operation" fhir:"cardinality=1..1,required"`
}

// TestScriptTeardown represents a FHIR BackboneElement for TestScript.teardown.
type TestScriptTeardown struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// One or more teardown operations to perform
	Action []TestScriptTeardownAction `json:"action,omitempty" fhir:"cardinality=1..*,required"`
}

// TestScript represents a FHIR TestScript.
type TestScript struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// Canonical identifier for this test script, represented as a URI (globally unique)
	URL *string `json:"url,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for URL
	URLExt *primitives.PrimitiveExtension `json:"_url,omitempty" fhir:"cardinality=0..1"`
	// Additional identifier for the test script
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*,summary"`
	// Business version of the test script
	Version *string `json:"version,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Version
	VersionExt *primitives.PrimitiveExtension `json:"_version,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - string option
	VersionAlgorithmString *string `json:"versionAlgorithmString,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Extension for VersionAlgorithmString
	VersionAlgorithmStringExt *primitives.PrimitiveExtension `json:"_versionAlgorithmString,omitempty" fhir:"cardinality=0..1"`
	// How to compare versions - Coding option
	VersionAlgorithmCoding *Coding `json:"versionAlgorithmCoding,omitempty" fhir:"cardinality=0..1,summary,choice=versionAlgorithm"`
	// Name for this test script (computer friendly)
	Name string `json:"name" fhir:"cardinality=1..1,required,summary"`
	// Extension for Name
	NameExt *primitives.PrimitiveExtension `json:"_name,omitempty" fhir:"cardinality=0..1"`
	// Name for this test script (human friendly)
	Title *string `json:"title,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Title
	TitleExt *primitives.PrimitiveExtension `json:"_title,omitempty" fhir:"cardinality=0..1"`
	// draft | active | retired | unknown
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// For testing purposes, not real usage
	Experimental *bool `json:"experimental,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Experimental
	ExperimentalExt *primitives.PrimitiveExtension `json:"_experimental,omitempty" fhir:"cardinality=0..1"`
	// Date last changed
	Date *primitives.DateTime `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// Name of the publisher/steward (organization or individual)
	Publisher *string `json:"publisher,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Publisher
	PublisherExt *primitives.PrimitiveExtension `json:"_publisher,omitempty" fhir:"cardinality=0..1"`
	// Contact details for the publisher
	Contact []ContactDetail `json:"contact,omitempty" fhir:"cardinality=0..*,summary"`
	// Natural language description of the test script
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// The context that the content is intended to support
	UseContext []UsageContext `json:"useContext,omitempty" fhir:"cardinality=0..*,summary"`
	// Intended jurisdiction for test script (if applicable)
	Jurisdiction []CodeableConcept `json:"jurisdiction,omitempty" fhir:"cardinality=0..*,summary"`
	// Why this test script is defined
	Purpose *string `json:"purpose,omitempty" fhir:"cardinality=0..1"`
	// Extension for Purpose
	PurposeExt *primitives.PrimitiveExtension `json:"_purpose,omitempty" fhir:"cardinality=0..1"`
	// Use and/or publishing restrictions
	Copyright *string `json:"copyright,omitempty" fhir:"cardinality=0..1"`
	// Extension for Copyright
	CopyrightExt *primitives.PrimitiveExtension `json:"_copyright,omitempty" fhir:"cardinality=0..1"`
	// Copyright holder and year(s)
	CopyrightLabel *string `json:"copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// Extension for CopyrightLabel
	CopyrightLabelExt *primitives.PrimitiveExtension `json:"_copyrightLabel,omitempty" fhir:"cardinality=0..1"`
	// An abstract server representing a client or sender in a message exchange
	Origin []TestScriptOrigin `json:"origin,omitempty" fhir:"cardinality=0..*"`
	// An abstract server representing a destination or receiver in a message exchange
	Destination []TestScriptDestination `json:"destination,omitempty" fhir:"cardinality=0..*"`
	// Required capability that is assumed to function correctly on the FHIR server being tested
	Metadata *TestScriptMetadata `json:"metadata,omitempty" fhir:"cardinality=0..1"`
	// Indication of the artifact(s) that are tested by this test case
	Scope []TestScriptScope `json:"scope,omitempty" fhir:"cardinality=0..*"`
	// Fixture in the test script - by reference (uri)
	Fixture []TestScriptFixture `json:"fixture,omitempty" fhir:"cardinality=0..*"`
	// Reference of the validation profile
	Profile []string `json:"profile,omitempty" fhir:"cardinality=0..*"`
	// Extension for Profile
	ProfileExt *primitives.PrimitiveExtension `json:"_profile,omitempty" fhir:"cardinality=0..1"`
	// Placeholder for evaluated elements
	Variable []TestScriptVariable `json:"variable,omitempty" fhir:"cardinality=0..*"`
	// A series of required setup operations before tests are executed
	Setup *TestScriptSetup `json:"setup,omitempty" fhir:"cardinality=0..1"`
	// A test in this script
	Test []TestScriptTest `json:"test,omitempty" fhir:"cardinality=0..*"`
	// A series of required clean up steps
	Teardown *TestScriptTeardown `json:"teardown,omitempty" fhir:"cardinality=0..1"`
}
