// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// TimingRepeat represents a FHIR BackboneElement for Timing.repeat.
type TimingRepeat struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Length/Range of lengths, or (Start and/or end) limits - Duration option
	BoundsDuration *Duration `json:"boundsDuration,omitempty" fhir:"cardinality=0..1,summary,choice=bounds"`
	// Length/Range of lengths, or (Start and/or end) limits - Range option
	BoundsRange *Range `json:"boundsRange,omitempty" fhir:"cardinality=0..1,summary,choice=bounds"`
	// Length/Range of lengths, or (Start and/or end) limits - Period option
	BoundsPeriod *Period `json:"boundsPeriod,omitempty" fhir:"cardinality=0..1,summary,choice=bounds"`
	// Number of times to repeat
	Count *int `json:"count,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Count
	CountExt *primitives.PrimitiveExtension `json:"_count,omitempty" fhir:"cardinality=0..1"`
	// Maximum number of times to repeat
	CountMax *int `json:"countMax,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for CountMax
	CountMaxExt *primitives.PrimitiveExtension `json:"_countMax,omitempty" fhir:"cardinality=0..1"`
	// How long when it happens
	Duration *float64 `json:"duration,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Duration
	DurationExt *primitives.PrimitiveExtension `json:"_duration,omitempty" fhir:"cardinality=0..1"`
	// How long when it happens (Max)
	DurationMax *float64 `json:"durationMax,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DurationMax
	DurationMaxExt *primitives.PrimitiveExtension `json:"_durationMax,omitempty" fhir:"cardinality=0..1"`
	// s | min | h | d | wk | mo | a - unit of time (UCUM)
	DurationUnit *string `json:"durationUnit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for DurationUnit
	DurationUnitExt *primitives.PrimitiveExtension `json:"_durationUnit,omitempty" fhir:"cardinality=0..1"`
	// Indicates the number of repetitions that should occur within a period. I.e. Event occurs frequency times per period
	Frequency *int `json:"frequency,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Frequency
	FrequencyExt *primitives.PrimitiveExtension `json:"_frequency,omitempty" fhir:"cardinality=0..1"`
	// Event occurs up to frequencyMax times per period
	FrequencyMax *int `json:"frequencyMax,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for FrequencyMax
	FrequencyMaxExt *primitives.PrimitiveExtension `json:"_frequencyMax,omitempty" fhir:"cardinality=0..1"`
	// The duration to which the frequency applies. I.e. Event occurs frequency times per period
	Period *float64 `json:"period,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Period
	PeriodExt *primitives.PrimitiveExtension `json:"_period,omitempty" fhir:"cardinality=0..1"`
	// Upper limit of period (3-4 hours)
	PeriodMax *float64 `json:"periodMax,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for PeriodMax
	PeriodMaxExt *primitives.PrimitiveExtension `json:"_periodMax,omitempty" fhir:"cardinality=0..1"`
	// s | min | h | d | wk | mo | a - unit of time (UCUM)
	PeriodUnit *string `json:"periodUnit,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for PeriodUnit
	PeriodUnitExt *primitives.PrimitiveExtension `json:"_periodUnit,omitempty" fhir:"cardinality=0..1"`
	// mon | tue | wed | thu | fri | sat | sun
	DayOfWeek []string `json:"dayOfWeek,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for DayOfWeek
	DayOfWeekExt *primitives.PrimitiveExtension `json:"_dayOfWeek,omitempty" fhir:"cardinality=0..1"`
	// Time of day for action
	TimeOfDay []primitives.Time `json:"timeOfDay,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for TimeOfDay
	TimeOfDayExt *primitives.PrimitiveExtension `json:"_timeOfDay,omitempty" fhir:"cardinality=0..1"`
	// Code for time period of occurrence
	When []string `json:"when,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for When
	WhenExt *primitives.PrimitiveExtension `json:"_when,omitempty" fhir:"cardinality=0..1"`
	// Minutes from event (before or after)
	Offset *uint `json:"offset,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Offset
	OffsetExt *primitives.PrimitiveExtension `json:"_offset,omitempty" fhir:"cardinality=0..1"`
}

// Timing represents a FHIR Timing.
type Timing struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// When the event occurs
	Event []primitives.DateTime `json:"event,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for Event
	EventExt *primitives.PrimitiveExtension `json:"_event,omitempty" fhir:"cardinality=0..1"`
	// When the event is to occur
	Repeat *TimingRepeat `json:"repeat,omitempty" fhir:"cardinality=0..1,summary"`
	// C | BID | TID | QID | AM | PM | QD | QOD | +
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
}
