// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeTransport is the FHIR resource type name for Transport.
const ResourceTypeTransport = "Transport"

// TransportRestriction represents a FHIR BackboneElement for Transport.restriction.
type TransportRestriction struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// How many times to repeat
	Repetitions *int `json:"repetitions,omitempty" fhir:"cardinality=0..1"`
	// Extension for Repetitions
	RepetitionsExt *primitives.PrimitiveExtension `json:"_repetitions,omitempty" fhir:"cardinality=0..1"`
	// When fulfillment sought
	Period *Period `json:"period,omitempty" fhir:"cardinality=0..1"`
	// For whom is fulfillment sought?
	Recipient []Reference `json:"recipient,omitempty" fhir:"cardinality=0..*"`
}

// TransportInput represents a FHIR BackboneElement for Transport.input.
type TransportInput struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for the input
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required"`
	// Content to use in performing the transport - base64Binary option
	ValueBase64Binary string `json:"valueBase64Binary" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBase64Binary
	ValueBase64BinaryExt *primitives.PrimitiveExtension `json:"_valueBase64Binary,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - boolean option
	ValueBoolean bool `json:"valueBoolean" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - canonical option
	ValueCanonical string `json:"valueCanonical" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueCanonical
	ValueCanonicalExt *primitives.PrimitiveExtension `json:"_valueCanonical,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - code option
	ValueCode string `json:"valueCode" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueCode
	ValueCodeExt *primitives.PrimitiveExtension `json:"_valueCode,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - date option
	ValueDate primitives.Date `json:"valueDate" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - dateTime option
	ValueDateTime primitives.DateTime `json:"valueDateTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDateTime
	ValueDateTimeExt *primitives.PrimitiveExtension `json:"_valueDateTime,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - decimal option
	ValueDecimal float64 `json:"valueDecimal" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDecimal
	ValueDecimalExt *primitives.PrimitiveExtension `json:"_valueDecimal,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - id option
	ValueID string `json:"valueID" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueID
	ValueIDExt *primitives.PrimitiveExtension `json:"_valueID,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - instant option
	ValueInstant primitives.Instant `json:"valueInstant" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInstant
	ValueInstantExt *primitives.PrimitiveExtension `json:"_valueInstant,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - integer option
	ValueInteger int `json:"valueInteger" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - integer64 option
	ValueInteger64 int64 `json:"valueInteger64" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInteger64
	ValueInteger64Ext *primitives.PrimitiveExtension `json:"_valueInteger64,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - markdown option
	ValueMarkdown string `json:"valueMarkdown" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueMarkdown
	ValueMarkdownExt *primitives.PrimitiveExtension `json:"_valueMarkdown,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - oid option
	ValueOid string `json:"valueOid" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueOid
	ValueOidExt *primitives.PrimitiveExtension `json:"_valueOid,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - positiveInt option
	ValuePositiveInt int `json:"valuePositiveInt" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValuePositiveInt
	ValuePositiveIntExt *primitives.PrimitiveExtension `json:"_valuePositiveInt,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - string option
	ValueString string `json:"valueString" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - time option
	ValueTime primitives.Time `json:"valueTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueTime
	ValueTimeExt *primitives.PrimitiveExtension `json:"_valueTime,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - unsignedInt option
	ValueUnsignedInt uint `json:"valueUnsignedInt" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueUnsignedInt
	ValueUnsignedIntExt *primitives.PrimitiveExtension `json:"_valueUnsignedInt,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - uri option
	ValueURI string `json:"valueURI" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueURI
	ValueURIExt *primitives.PrimitiveExtension `json:"_valueURI,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - url option
	ValueURL string `json:"valueURL" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueURL
	ValueURLExt *primitives.PrimitiveExtension `json:"_valueURL,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - uuid option
	ValueUUID string `json:"valueUUID" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueUUID
	ValueUUIDExt *primitives.PrimitiveExtension `json:"_valueUUID,omitempty" fhir:"cardinality=0..1"`
	// Content to use in performing the transport - Address option
	ValueAddress Address `json:"valueAddress" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Age option
	ValueAge Age `json:"valueAge" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Annotation option
	ValueAnnotation Annotation `json:"valueAnnotation" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Attachment option
	ValueAttachment Attachment `json:"valueAttachment" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - CodeableConcept option
	ValueCodeableConcept CodeableConcept `json:"valueCodeableConcept" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - CodeableReference option
	ValueCodeableReference CodeableReference `json:"valueCodeableReference" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Coding option
	ValueCoding Coding `json:"valueCoding" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - ContactPoint option
	ValueContactPoint ContactPoint `json:"valueContactPoint" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Count option
	ValueCount Count `json:"valueCount" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Distance option
	ValueDistance Distance `json:"valueDistance" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Duration option
	ValueDuration Duration `json:"valueDuration" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - HumanName option
	ValueHumanName HumanName `json:"valueHumanName" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Identifier option
	ValueIdentifier Identifier `json:"valueIdentifier" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Money option
	ValueMoney Money `json:"valueMoney" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Period option
	ValuePeriod Period `json:"valuePeriod" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Quantity option
	ValueQuantity Quantity `json:"valueQuantity" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Range option
	ValueRange Range `json:"valueRange" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Ratio option
	ValueRatio Ratio `json:"valueRatio" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - RatioRange option
	ValueRatioRange RatioRange `json:"valueRatioRange" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Reference option
	ValueReference Reference `json:"valueReference" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - SampledData option
	ValueSampledData SampledData `json:"valueSampledData" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Signature option
	ValueSignature Signature `json:"valueSignature" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Timing option
	ValueTiming Timing `json:"valueTiming" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - ContactDetail option
	ValueContactDetail ContactDetail `json:"valueContactDetail" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - DataRequirement option
	ValueDataRequirement DataRequirement `json:"valueDataRequirement" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Expression option
	ValueExpression Expression `json:"valueExpression" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - ParameterDefinition option
	ValueParameterDefinition ParameterDefinition `json:"valueParameterDefinition" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - RelatedArtifact option
	ValueRelatedArtifact RelatedArtifact `json:"valueRelatedArtifact" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - TriggerDefinition option
	ValueTriggerDefinition TriggerDefinition `json:"valueTriggerDefinition" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - UsageContext option
	ValueUsageContext UsageContext `json:"valueUsageContext" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Availability option
	ValueAvailability Availability `json:"valueAvailability" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - ExtendedContactDetail option
	ValueExtendedContactDetail ExtendedContactDetail `json:"valueExtendedContactDetail" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Dosage option
	ValueDosage Dosage `json:"valueDosage" fhir:"cardinality=1..1,required,choice=value"`
	// Content to use in performing the transport - Meta option
	ValueMeta Meta `json:"valueMeta" fhir:"cardinality=1..1,required,choice=value"`
}

// TransportOutput represents a FHIR BackboneElement for Transport.output.
type TransportOutput struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Label for output
	Type CodeableConcept `json:"type" fhir:"cardinality=1..1,required"`
	// Result of output - base64Binary option
	ValueBase64Binary string `json:"valueBase64Binary" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBase64Binary
	ValueBase64BinaryExt *primitives.PrimitiveExtension `json:"_valueBase64Binary,omitempty" fhir:"cardinality=0..1"`
	// Result of output - boolean option
	ValueBoolean bool `json:"valueBoolean" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueBoolean
	ValueBooleanExt *primitives.PrimitiveExtension `json:"_valueBoolean,omitempty" fhir:"cardinality=0..1"`
	// Result of output - canonical option
	ValueCanonical string `json:"valueCanonical" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueCanonical
	ValueCanonicalExt *primitives.PrimitiveExtension `json:"_valueCanonical,omitempty" fhir:"cardinality=0..1"`
	// Result of output - code option
	ValueCode string `json:"valueCode" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueCode
	ValueCodeExt *primitives.PrimitiveExtension `json:"_valueCode,omitempty" fhir:"cardinality=0..1"`
	// Result of output - date option
	ValueDate primitives.Date `json:"valueDate" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDate
	ValueDateExt *primitives.PrimitiveExtension `json:"_valueDate,omitempty" fhir:"cardinality=0..1"`
	// Result of output - dateTime option
	ValueDateTime primitives.DateTime `json:"valueDateTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDateTime
	ValueDateTimeExt *primitives.PrimitiveExtension `json:"_valueDateTime,omitempty" fhir:"cardinality=0..1"`
	// Result of output - decimal option
	ValueDecimal float64 `json:"valueDecimal" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueDecimal
	ValueDecimalExt *primitives.PrimitiveExtension `json:"_valueDecimal,omitempty" fhir:"cardinality=0..1"`
	// Result of output - id option
	ValueID string `json:"valueID" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueID
	ValueIDExt *primitives.PrimitiveExtension `json:"_valueID,omitempty" fhir:"cardinality=0..1"`
	// Result of output - instant option
	ValueInstant primitives.Instant `json:"valueInstant" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInstant
	ValueInstantExt *primitives.PrimitiveExtension `json:"_valueInstant,omitempty" fhir:"cardinality=0..1"`
	// Result of output - integer option
	ValueInteger int `json:"valueInteger" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInteger
	ValueIntegerExt *primitives.PrimitiveExtension `json:"_valueInteger,omitempty" fhir:"cardinality=0..1"`
	// Result of output - integer64 option
	ValueInteger64 int64 `json:"valueInteger64" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueInteger64
	ValueInteger64Ext *primitives.PrimitiveExtension `json:"_valueInteger64,omitempty" fhir:"cardinality=0..1"`
	// Result of output - markdown option
	ValueMarkdown string `json:"valueMarkdown" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueMarkdown
	ValueMarkdownExt *primitives.PrimitiveExtension `json:"_valueMarkdown,omitempty" fhir:"cardinality=0..1"`
	// Result of output - oid option
	ValueOid string `json:"valueOid" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueOid
	ValueOidExt *primitives.PrimitiveExtension `json:"_valueOid,omitempty" fhir:"cardinality=0..1"`
	// Result of output - positiveInt option
	ValuePositiveInt int `json:"valuePositiveInt" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValuePositiveInt
	ValuePositiveIntExt *primitives.PrimitiveExtension `json:"_valuePositiveInt,omitempty" fhir:"cardinality=0..1"`
	// Result of output - string option
	ValueString string `json:"valueString" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueString
	ValueStringExt *primitives.PrimitiveExtension `json:"_valueString,omitempty" fhir:"cardinality=0..1"`
	// Result of output - time option
	ValueTime primitives.Time `json:"valueTime" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueTime
	ValueTimeExt *primitives.PrimitiveExtension `json:"_valueTime,omitempty" fhir:"cardinality=0..1"`
	// Result of output - unsignedInt option
	ValueUnsignedInt uint `json:"valueUnsignedInt" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueUnsignedInt
	ValueUnsignedIntExt *primitives.PrimitiveExtension `json:"_valueUnsignedInt,omitempty" fhir:"cardinality=0..1"`
	// Result of output - uri option
	ValueURI string `json:"valueURI" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueURI
	ValueURIExt *primitives.PrimitiveExtension `json:"_valueURI,omitempty" fhir:"cardinality=0..1"`
	// Result of output - url option
	ValueURL string `json:"valueURL" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueURL
	ValueURLExt *primitives.PrimitiveExtension `json:"_valueURL,omitempty" fhir:"cardinality=0..1"`
	// Result of output - uuid option
	ValueUUID string `json:"valueUUID" fhir:"cardinality=1..1,required,choice=value"`
	// Extension for ValueUUID
	ValueUUIDExt *primitives.PrimitiveExtension `json:"_valueUUID,omitempty" fhir:"cardinality=0..1"`
	// Result of output - Address option
	ValueAddress Address `json:"valueAddress" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Age option
	ValueAge Age `json:"valueAge" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Annotation option
	ValueAnnotation Annotation `json:"valueAnnotation" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Attachment option
	ValueAttachment Attachment `json:"valueAttachment" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - CodeableConcept option
	ValueCodeableConcept CodeableConcept `json:"valueCodeableConcept" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - CodeableReference option
	ValueCodeableReference CodeableReference `json:"valueCodeableReference" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Coding option
	ValueCoding Coding `json:"valueCoding" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - ContactPoint option
	ValueContactPoint ContactPoint `json:"valueContactPoint" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Count option
	ValueCount Count `json:"valueCount" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Distance option
	ValueDistance Distance `json:"valueDistance" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Duration option
	ValueDuration Duration `json:"valueDuration" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - HumanName option
	ValueHumanName HumanName `json:"valueHumanName" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Identifier option
	ValueIdentifier Identifier `json:"valueIdentifier" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Money option
	ValueMoney Money `json:"valueMoney" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Period option
	ValuePeriod Period `json:"valuePeriod" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Quantity option
	ValueQuantity Quantity `json:"valueQuantity" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Range option
	ValueRange Range `json:"valueRange" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Ratio option
	ValueRatio Ratio `json:"valueRatio" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - RatioRange option
	ValueRatioRange RatioRange `json:"valueRatioRange" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Reference option
	ValueReference Reference `json:"valueReference" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - SampledData option
	ValueSampledData SampledData `json:"valueSampledData" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Signature option
	ValueSignature Signature `json:"valueSignature" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Timing option
	ValueTiming Timing `json:"valueTiming" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - ContactDetail option
	ValueContactDetail ContactDetail `json:"valueContactDetail" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - DataRequirement option
	ValueDataRequirement DataRequirement `json:"valueDataRequirement" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Expression option
	ValueExpression Expression `json:"valueExpression" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - ParameterDefinition option
	ValueParameterDefinition ParameterDefinition `json:"valueParameterDefinition" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - RelatedArtifact option
	ValueRelatedArtifact RelatedArtifact `json:"valueRelatedArtifact" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - TriggerDefinition option
	ValueTriggerDefinition TriggerDefinition `json:"valueTriggerDefinition" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - UsageContext option
	ValueUsageContext UsageContext `json:"valueUsageContext" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Availability option
	ValueAvailability Availability `json:"valueAvailability" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - ExtendedContactDetail option
	ValueExtendedContactDetail ExtendedContactDetail `json:"valueExtendedContactDetail" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Dosage option
	ValueDosage Dosage `json:"valueDosage" fhir:"cardinality=1..1,required,choice=value"`
	// Result of output - Meta option
	ValueMeta Meta `json:"valueMeta" fhir:"cardinality=1..1,required,choice=value"`
}

// Transport represents a FHIR Transport.
type Transport struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// External identifier
	Identifier []Identifier `json:"identifier,omitempty" fhir:"cardinality=0..*"`
	// Formal definition of transport
	InstantiatesCanonical *string `json:"instantiatesCanonical,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for InstantiatesCanonical
	InstantiatesCanonicalExt *primitives.PrimitiveExtension `json:"_instantiatesCanonical,omitempty" fhir:"cardinality=0..1"`
	// Formal definition of transport
	InstantiatesUri *string `json:"instantiatesUri,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for InstantiatesUri
	InstantiatesUriExt *primitives.PrimitiveExtension `json:"_instantiatesUri,omitempty" fhir:"cardinality=0..1"`
	// Request fulfilled by this transport
	BasedOn []Reference `json:"basedOn,omitempty" fhir:"cardinality=0..*,summary"`
	// Requisition or grouper id
	GroupIdentifier *Identifier `json:"groupIdentifier,omitempty" fhir:"cardinality=0..1,summary"`
	// Part of referenced event
	PartOf []Reference `json:"partOf,omitempty" fhir:"cardinality=0..*,summary"`
	// in-progress | completed | abandoned | cancelled | planned | entered-in-error
	Status *string `json:"status,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// Reason for current status
	StatusReason *CodeableConcept `json:"statusReason,omitempty" fhir:"cardinality=0..1,summary"`
	// unknown | proposal | plan | order | original-order | reflex-order | filler-order | instance-order | option
	Intent string `json:"intent" fhir:"cardinality=1..1,required,summary"`
	// Extension for Intent
	IntentExt *primitives.PrimitiveExtension `json:"_intent,omitempty" fhir:"cardinality=0..1"`
	// routine | urgent | asap | stat
	Priority *string `json:"priority,omitempty" fhir:"cardinality=0..1"`
	// Extension for Priority
	PriorityExt *primitives.PrimitiveExtension `json:"_priority,omitempty" fhir:"cardinality=0..1"`
	// Transport Type
	Code *CodeableConcept `json:"code,omitempty" fhir:"cardinality=0..1,summary"`
	// Human-readable explanation of transport
	Description *string `json:"description,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Description
	DescriptionExt *primitives.PrimitiveExtension `json:"_description,omitempty" fhir:"cardinality=0..1"`
	// What transport is acting on
	Focus *Reference `json:"focus,omitempty" fhir:"cardinality=0..1,summary"`
	// Beneficiary of the Transport
	For *Reference `json:"for,omitempty" fhir:"cardinality=0..1,summary"`
	// Healthcare event during which this transport originated
	Encounter *Reference `json:"encounter,omitempty" fhir:"cardinality=0..1,summary"`
	// Completion time of the event (the occurrence)
	CompletionTime *primitives.DateTime `json:"completionTime,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for CompletionTime
	CompletionTimeExt *primitives.PrimitiveExtension `json:"_completionTime,omitempty" fhir:"cardinality=0..1"`
	// Transport Creation Date
	AuthoredOn *primitives.DateTime `json:"authoredOn,omitempty" fhir:"cardinality=0..1"`
	// Extension for AuthoredOn
	AuthoredOnExt *primitives.PrimitiveExtension `json:"_authoredOn,omitempty" fhir:"cardinality=0..1"`
	// Transport Last Modified Date
	LastModified *primitives.DateTime `json:"lastModified,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for LastModified
	LastModifiedExt *primitives.PrimitiveExtension `json:"_lastModified,omitempty" fhir:"cardinality=0..1"`
	// Who is asking for transport to be done
	Requester *Reference `json:"requester,omitempty" fhir:"cardinality=0..1,summary"`
	// Requested performer
	PerformerType []CodeableConcept `json:"performerType,omitempty" fhir:"cardinality=0..*"`
	// Responsible individual
	Owner *Reference `json:"owner,omitempty" fhir:"cardinality=0..1,summary"`
	// Where transport occurs
	Location *Reference `json:"location,omitempty" fhir:"cardinality=0..1,summary"`
	// Associated insurance coverage
	Insurance []Reference `json:"insurance,omitempty" fhir:"cardinality=0..*"`
	// Comments made about the transport
	Note []Annotation `json:"note,omitempty" fhir:"cardinality=0..*"`
	// Key events in history of the Transport
	RelevantHistory []Reference `json:"relevantHistory,omitempty" fhir:"cardinality=0..*"`
	// Constraints on fulfillment transports
	Restriction *TransportRestriction `json:"restriction,omitempty" fhir:"cardinality=0..1"`
	// Information used to perform transport
	Input []TransportInput `json:"input,omitempty" fhir:"cardinality=0..*"`
	// Information produced as part of transport
	Output []TransportOutput `json:"output,omitempty" fhir:"cardinality=0..*"`
	// The desired location
	RequestedLocation Reference `json:"requestedLocation" fhir:"cardinality=1..1,required,summary"`
	// The entity current location
	CurrentLocation Reference `json:"currentLocation" fhir:"cardinality=1..1,required,summary"`
	// Why transport is needed
	Reason *CodeableReference `json:"reason,omitempty" fhir:"cardinality=0..1"`
	// Parent (or preceding) transport
	History *Reference `json:"history,omitempty" fhir:"cardinality=0..1"`
}
