// Code generated by fhirgen v0.2.0. DO NOT EDIT.
// Generated at: 2026-02-15T13:05:01Z
// FHIR Version: RESOURCES
// Source: FHIR StructureDefinitions from https://hl7.org/fhir/RESOURCES/

package r5

import (
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir"
	"github.com/zarishsphere/zs-core-fhir-engine/pkg/fhir/primitives"
)

// ResourceTypeVerificationResult is the FHIR resource type name for VerificationResult.
const ResourceTypeVerificationResult = "VerificationResult"

// VerificationResultPrimarySource represents a FHIR BackboneElement for VerificationResult.primarySource.
type VerificationResultPrimarySource struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Reference to the primary source
	Who *Reference `json:"who,omitempty" fhir:"cardinality=0..1"`
	// Type of primary source (License Board; Primary Education; Continuing Education; Postal Service; Relationship owner; Registration Authority; legal source; issuing source; authoritative source)
	Type []CodeableConcept `json:"type,omitempty" fhir:"cardinality=0..*,summary"`
	// Method for exchanging information with the primary source
	CommunicationMethod []CodeableConcept `json:"communicationMethod,omitempty" fhir:"cardinality=0..*,summary"`
	// successful | failed | unknown
	ValidationStatus *CodeableConcept `json:"validationStatus,omitempty" fhir:"cardinality=0..1"`
	// When the target was validated against the primary source
	ValidationDate *primitives.DateTime `json:"validationDate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ValidationDate
	ValidationDateExt *primitives.PrimitiveExtension `json:"_validationDate,omitempty" fhir:"cardinality=0..1"`
	// yes | no | undetermined
	CanPushUpdates *CodeableConcept `json:"canPushUpdates,omitempty" fhir:"cardinality=0..1,summary"`
	// specific | any | source
	PushTypeAvailable []CodeableConcept `json:"pushTypeAvailable,omitempty" fhir:"cardinality=0..*"`
}

// VerificationResultAttestation represents a FHIR BackboneElement for VerificationResult.attestation.
type VerificationResultAttestation struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// The individual or organization attesting to information
	Who *Reference `json:"who,omitempty" fhir:"cardinality=0..1,summary"`
	// When the who is asserting on behalf of another (organization or individual)
	OnBehalfOf *Reference `json:"onBehalfOf,omitempty" fhir:"cardinality=0..1,summary"`
	// The method by which attested information was submitted/retrieved
	CommunicationMethod *CodeableConcept `json:"communicationMethod,omitempty" fhir:"cardinality=0..1,summary"`
	// The date the information was attested to
	Date *primitives.Date `json:"date,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for Date
	DateExt *primitives.PrimitiveExtension `json:"_date,omitempty" fhir:"cardinality=0..1"`
	// A digital identity certificate associated with the attestation source
	SourceIdentityCertificate *string `json:"sourceIdentityCertificate,omitempty" fhir:"cardinality=0..1"`
	// Extension for SourceIdentityCertificate
	SourceIdentityCertificateExt *primitives.PrimitiveExtension `json:"_sourceIdentityCertificate,omitempty" fhir:"cardinality=0..1"`
	// A digital identity certificate associated with the proxy entity submitting attested information on behalf of the attestation source
	ProxyIdentityCertificate *string `json:"proxyIdentityCertificate,omitempty" fhir:"cardinality=0..1"`
	// Extension for ProxyIdentityCertificate
	ProxyIdentityCertificateExt *primitives.PrimitiveExtension `json:"_proxyIdentityCertificate,omitempty" fhir:"cardinality=0..1"`
	// Proxy signature (digital or image)
	ProxySignature *Signature `json:"proxySignature,omitempty" fhir:"cardinality=0..1"`
	// Attester signature (digital or image)
	SourceSignature *Signature `json:"sourceSignature,omitempty" fhir:"cardinality=0..1"`
}

// VerificationResultValidator represents a FHIR BackboneElement for VerificationResult.validator.
type VerificationResultValidator struct {
	// Unique id for inter-element referencing
	ID *string `json:"id,omitempty" fhir:"cardinality=0..1"`
	// Extension for ID
	IDExt *primitives.PrimitiveExtension `json:"_id,omitempty" fhir:"cardinality=0..1"`
	// Additional content defined by implementations
	Extension []Extension `json:"extension,omitempty" fhir:"cardinality=0..*"`
	// Extensions that cannot be ignored even if unrecognized
	ModifierExtension []Extension `json:"modifierExtension,omitempty" fhir:"cardinality=0..*,summary"`
	// Reference to the organization validating information
	Organization Reference `json:"organization" fhir:"cardinality=1..1,required"`
	// A digital identity certificate associated with the validator
	IdentityCertificate *string `json:"identityCertificate,omitempty" fhir:"cardinality=0..1"`
	// Extension for IdentityCertificate
	IdentityCertificateExt *primitives.PrimitiveExtension `json:"_identityCertificate,omitempty" fhir:"cardinality=0..1"`
	// Validator signature (digital or image)
	AttestationSignature *Signature `json:"attestationSignature,omitempty" fhir:"cardinality=0..1"`
}

// VerificationResult represents a FHIR VerificationResult.
type VerificationResult struct {
	fhir.DomainResource
	// Extension for Contained
	ContainedExt *primitives.PrimitiveExtension `json:"_contained,omitempty" fhir:"cardinality=0..1"`
	// A resource that was validated
	Target []Reference `json:"target,omitempty" fhir:"cardinality=0..*,summary"`
	// The fhirpath location(s) within the resource that was validated
	TargetLocation []string `json:"targetLocation,omitempty" fhir:"cardinality=0..*,summary"`
	// Extension for TargetLocation
	TargetLocationExt *primitives.PrimitiveExtension `json:"_targetLocation,omitempty" fhir:"cardinality=0..1"`
	// none | initial | periodic
	Need *CodeableConcept `json:"need,omitempty" fhir:"cardinality=0..1,summary"`
	// attested | validated | in-process | req-revalid | val-fail | reval-fail | entered-in-error
	Status string `json:"status" fhir:"cardinality=1..1,required,summary"`
	// Extension for Status
	StatusExt *primitives.PrimitiveExtension `json:"_status,omitempty" fhir:"cardinality=0..1"`
	// When the validation status was updated
	StatusDate *primitives.DateTime `json:"statusDate,omitempty" fhir:"cardinality=0..1,summary"`
	// Extension for StatusDate
	StatusDateExt *primitives.PrimitiveExtension `json:"_statusDate,omitempty" fhir:"cardinality=0..1"`
	// nothing | primary | multiple
	ValidationType *CodeableConcept `json:"validationType,omitempty" fhir:"cardinality=0..1,summary"`
	// The primary process by which the target is validated (edit check; value set; primary source; multiple sources; standalone; in context)
	ValidationProcess []CodeableConcept `json:"validationProcess,omitempty" fhir:"cardinality=0..*,summary"`
	// Frequency of revalidation
	Frequency *Timing `json:"frequency,omitempty" fhir:"cardinality=0..1"`
	// The date/time validation was last completed (including failed validations)
	LastPerformed *primitives.DateTime `json:"lastPerformed,omitempty" fhir:"cardinality=0..1"`
	// Extension for LastPerformed
	LastPerformedExt *primitives.PrimitiveExtension `json:"_lastPerformed,omitempty" fhir:"cardinality=0..1"`
	// The date when target is next validated, if appropriate
	NextScheduled *primitives.Date `json:"nextScheduled,omitempty" fhir:"cardinality=0..1"`
	// Extension for NextScheduled
	NextScheduledExt *primitives.PrimitiveExtension `json:"_nextScheduled,omitempty" fhir:"cardinality=0..1"`
	// fatal | warn | rec-only | none
	FailureAction *CodeableConcept `json:"failureAction,omitempty" fhir:"cardinality=0..1,summary"`
	// Information about the primary source(s) involved in validation
	PrimarySource []VerificationResultPrimarySource `json:"primarySource,omitempty" fhir:"cardinality=0..*"`
	// Information about the entity attesting to information
	Attestation *VerificationResultAttestation `json:"attestation,omitempty" fhir:"cardinality=0..1"`
	// Information about the entity validating information
	Validator []VerificationResultValidator `json:"validator,omitempty" fhir:"cardinality=0..*"`
}
